### ISSUE TITLE
Signalr 2.2.0 No interface to the specified assembly for scanning

### ISSUE THREAD

**Issue by qiufengilove** [SignalR/SignalR#3733] opened 2016-07-10 12:45 UTC
When I want to scan the specified assembly or the specified type, I find that there is no such interface, and can provide these two methods or interfaces.

**Comment by moozzyk** [comment] 2016-07-11 16:38
It's not clear what you are asking and how it is related to SignalR. If it is not a bug or a feature request I would recommend asking on stackoverflow.com. I am closing this issue. Feel free to reopen but provide more details otherwise it is not actionable.

**Closed by moozzyk** 2016-07-11 16:38 UTC
