### ISSUE TITLE
WebSocket Error: Incorrect HTTP response. Status code 400, Bad Request

### ISSUE THREAD

**Issue by mbeckenbach** [SignalR/SignalR#3990] opened 2017-08-16 07:47 UTC
### Expected  behavior
Should connect using websockets instead of fallback

### Actual behavior
It gives the "WebSocket Error: Incorrect HTTP response. Status code 400, Bad Request" mesaage and then falls back to long polling.

Server is Win 2012 and the IIS websocket feature is installed. No Proxy or Reverse Proxy is used at any place between the client and the server.

Dosn't kill me, but it would be cool to know why this could happen.

### Steps to reproduce
???

**Comment by aspnet-hello** [comment] 2018-09-20 21:49
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Closed by aspnet-hello** 2018-09-20 21:49 UTC

**Comment by Gopichandar** [comment] 2020-07-14 08:24
I'm facing similar issue.  Any workaround for this.  What is the root cause?
