### ISSUE TITLE
SingnalR Client connection breaks on Xamarin.iOS 12.2.1.10 with exception

### ISSUE THREAD

**Issue by wcoder** [SignalR/SignalR#4268] opened 2018-11-15 18:02 UTC
### Expected  behavior
`StartAsync` method will be called without exception. As on previous Xamarin.iOS version 12.1.0.15.

### Actual Behavior
Exception after call `StartAsync` method:
```
Method not found: void System.Threading.Tasks.ValueTask`1..ctor(System.Threading.Tasks.Sources.IValueTaskSource`1<!0>,int16)
```
StackTrace:
```
  at System.IO.Pipelines.Pipe+DefaultPipeWriter.FlushAsync (System.Threading.CancellationToken cancellationToken) [0x00000] in <15ef00bc425842ceab342d03d837ed41>:0 
  at Microsoft.AspNetCore.SignalR.Client.HubConnection+<HandshakeAsync>d__45.MoveNext () [0x00075] in <d63a12cba2854e5f913565673038699b>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.SignalR.Client.HubConnection+<StartAsyncCore>d__31.MoveNext () [0x001d2] in <d63a12cba2854e5f913565673038699b>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.SignalR.Client.HubConnection+<StartAsyncCore>d__31.MoveNext () [0x00298] in <d63a12cba2854e5f913565673038699b>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Threading.Tasks.ForceAsyncAwaiter.GetResult () [0x0000c] in <d63a12cba2854e5f913565673038699b>:0 
  at Microsoft.AspNetCore.SignalR.Client.HubConnection+<StartAsync>d__24.MoveNext () [0x00076] in <d63a12cba2854e5f913565673038699b>:0 
--- End of stack trace from previous location where exception was thrown ---
  at SignalRConnectIssue.Core.Class1+<Connect>d__0.MoveNext () [0x00043] in /Users/yauhenipakala/Examples/SingalRConnectIssue/SignalRConnectIssue.Core/Class1.cs:34 
--- End of stack trace from previous location where exception was thrown ---
  at SingalRConnectIssue.ViewController+<>c+<<ViewDidLoad>b__1_0>d.MoveNext () [0x00028] in /Users/yauhenipakala/Examples/SingalRConnectIssue/SingalRConnectIssue/ViewController.cs:31 
```

### Steps to Reproduce

1. Create an empty iOS project
2. Add the latest version of SignalR `Microsoft.AspNetCore.SignalR.Client` (1.0.4)
3. Add this simple code:

```csharp
var hubConnection = new HubConnectionBuilder()
    .WithUrl("http://<some-site>")
    .Build();

await hubConnection.StartAsync();
```

Logs: https://github.com/xamarin/xamarin-macios/issues/5133

**Comment by anurse** [comment] 2018-11-15 18:48
This repo is for ASP.NET SignalR (not ASP.NET Core SignalR), but it looks like what you're seeing is the same as aspnet/SignalR#3307 and that the issue is in Xamarin itself. Closing this issue as a duplicate of that one.

**Closed by anurse** 2018-11-15 18:48 UTC
