### ISSUE TITLE
Profile 111

### ISSUE THREAD

**Issue by tofutim** [SignalR/SignalR#3586] opened 2015-10-29 22:16 UTC
Hi, I am trying to install SignalR into my PCL, it has .NET 4.5, Win 8 (well, I really only need Win10), iOS and Android from Xamarin and Windows Phone. This is profile 111 but the nuget installer fails. Any tips?

Severity	Code	Description	Project	File	Line
Error		Could not install package 'Microsoft.AspNet.SignalR.Client 2.2.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by tofutim** [comment] 2015-10-29 23:21
The mystery continues. I am able to install SignalR Client 2.1.2 into PCL with profile 111. It must be an issue with the latest version (2.2.0). Can someone speak to it? For now I will stick with SignalR 2.1.2.

**Comment by moozzyk** [comment] 2015-10-30 15:19
Can it be #3393?

**Comment by tofutim** [comment] 2015-10-30 15:44
I think so, thanks.

**Comment by moozzyk** [comment] 2015-12-03 20:21
@tofutim - I just verified that this is fixed after 9951d04631e092bdad2287615dcfbff14619396c so it is a dupe of #3393 indeed. The fix will be in the next release.

**Closed by moozzyk** 2015-12-03 20:21 UTC

**Comment by tofutim** [comment] 2016-01-20 21:53
Hi, I still have this issue. When does 2.2.1 come out?

**Comment by mydevpartner** [comment] 2016-05-19 16:51
I have this issue as well. Any updates?

**Comment by emilianomon** [comment] 2016-07-12 23:21
I've just ran into this issue as well. Thanks for saying that it works with the 2.1.2 up there @tofutim. I usually don't try earlier versions when the current one is stable.
