### ISSUE TITLE
System.Web.HttpException: The remote host closed the connection. The error code is 0x800704CD

### ISSUE THREAD

**Issue by davidfowl** [SignalR/SignalR#4217] opened 2018-09-25 14:48 UTC
_From @jinek on Tuesday, 25 September 2018 10:04:49_

* Versions of Server-Side NuGet Packages: 2.3.0
* Versions of Client-Side NuGet/NPM Packages: 2.3.0
* C# client
* Azure Web App
* Windows on server and client

Exception happening during server deployment
[SignalRStackTrace.txt](https://github.com/aspnet/SignalR/files/2414737/SignalRStackTrace.txt)

_Copied from original issue: aspnet/SignalR#3008_

**Comment by davidfowl** [comment] 2018-09-25 14:50
Pasting the error here for conveniece.

```
System.Web.HttpException: The remote host closed the connection. The error code is 0x800704CD.
  at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
  at System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush()
  at System.Web.HttpResponse.Flush(Boolean finalFlush, Boolean async)
  at System.Web.HttpWriter.WriteFromStream(Byte[] data, Int32 offset, Int32 size)
  at Microsoft.Owin.Host.SystemWeb.CallStreams.OutputStream.Write(Byte[] buffer, Int32 offset, Int32 count)
  at Microsoft.AspNet.SignalR.Owin.ServerResponse.Write(ArraySegment`1 data)
  at Microsoft.AspNet.SignalR.Hosting.ResponseExtensions.End(IResponse response, String data)
  at Microsoft.AspNet.SignalR.PersistentConnection.ProcessNegotiationRequest(HostContext context)
  at Microsoft.AspNet.SignalR.PersistentConnection.ProcessRequest(HostContext context)
  at Microsoft.Owin.Mapping.MapMiddleware.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar)
  at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
  at System.Web.HttpApplication.<>c__DisplayClass285_0.<ExecuteStepImpl>b__0()
  at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
  at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
  --- End of inner exception stack trace ---
```

This is by design. The connection drops and there's an exception that happens when the response is written. We *could* swallow the exception but it can be safely ignored.

**Comment by anurse** [comment] 2018-09-25 16:06
To be clear, we can only prevent this exception in very specific cases. There are a number of places where this exception can occur (other parts in the OWIN stack) that we can't prevent in SignalR. If the client disconnects abruptly, we throw an exception, this is by design so that you can log this information.

I'm going to close this as it's by-design but feel free to comment further if you have questions.

**Closed by anurse** 2018-09-25 16:06 UTC

**Comment by jinek** [comment] 2018-09-25 18:00
> This is by design. The connection drops and there's an exception that happens when the response is written. We could swallow the exception but it can be safely ignored

If you expect exception you should not allow it to go up the stack as caller code thinks your code does not work. Exception can't be ignored at global level as it has type System.Web.HttpException that can be thrown from other parts of the code and no possibility to distinguish this one from others.

**Comment by jinek** [comment] 2018-09-25 18:28
> To be clear, we can only prevent this exception in very specific cases. There are a number of places where this exception can occur (other parts in the OWIN stack) that we can't prevent in SignalR. If the client disconnects abruptly, we throw an exception, this is by design so that you can log this information.

**OWIN** is asking you to process request, you asking **OWIN** to write response and during writing **OWIN** answers it can not write. You don't consider this situation and allow your code to rethrow the exception, reporting the caller code your method did not success (but in fact it did success).

At first I'm going to create an issue in .NET Framework about **HttpResponseStream.Write** throws **HttpException** that is not declared in documentation of **Stream.Write**.

Btw there are few posts with same problem:  https://stackoverflow.com/questions/23761851/how-to-catch-this-signalr-exception and  https://github.com/SignalR/SignalR/issues/2632 . Usually developers don't consider disconnected clients as a problem that needs to be logged. Furthermore that could not be logged - as I said we can't understand if this exception happened because of disconnected client or anything else.

**Comment by anurse** [comment] 2018-09-25 19:26
> You don't consider this situation and allow your code to rethrow the exception, reporting the caller code your method did not success (but in fact it did success).

We definitely consider this situation, it's a standard Exception scenario. The method **has failed**, and SignalR is letting this failure flow up because SignalR has no way to recover from this error. Exceptions should only be caught by those who can recover from them. The exception **is** caught when it gets all the way to the top of the stack for that request because the server simply considers that request failed and recovers. This isn't a case of an exception occurring but actually everything succeeded. The write failed because the socket was closed. We could hide this from you, but it would be inaccurate since we'd be reporting that the message was sent when actually it couldn't be sent because the client disconnected.

> as I said we can't understand if this exception happened because of disconnected client or anything else.

SignalR doesn't know this either, which is why we report it. All we know is that the remote end of the socket disconnected. We don't know if this is because the client disconnected, or the server lost network connection, or the operating system failed to write the data.

For us to suppress this it would be all or nothing, we don't have the ability to determine which errors are caused by the client disconnecting and which are caused by other network failures along the way. So you'd also lose information about exceptions triggered by misconfiguration of your server causing the connection to be closed. This is the nature of networking, we don't know why the send failed, just that it failed.

If that would be useful for you, I'm not necessarily opposed to adding an option to suppress all write errors, but I think that would risk pretty significant problems if you do encounter an error that is in your control which is hidden from you because we're suppressing these exceptions.

**Comment by jinek** [comment] 2018-09-25 23:40
>  the app stays active

True, as with almost any other exception)

And again thanks, probably i understood my mistake and you helped me a lot. **HttpException** is supposed to be thrown from **IHttpHandlers** or anything else being processed by **HttpApplication**. Probably this information won't be useful for you, but hope will be for somebody else.

**HttpApplication** expects **HttpException** and will transform it to response with appropriate http code:
![exceptioninhttpresponse](https://user-images.githubusercontent.com/10516222/46048925-1764bd80-c12c-11e8-84fc-a9634aa35707.png)


And in case this transformation failed (exactly our case, when socket was closed) it will try to just to log information (again, our case, we cant write to response). (The only problem here is if logging failed the application just skip everything and continue to work):

![raiseruntimeerror](https://user-images.githubusercontent.com/10516222/46048929-1d5a9e80-c12c-11e8-99bf-03c7dd7861b3.png)

The thing is **Global.Application_Error** will be called anyway. It means if our handler is trying to return HTTP 403 by throwing **new HttpException (403, "Not found")** it will go to **Global.Application_Error** first. All over internet we can see **Global.Application_Error** is  suggested for logging, like logging of unpredictable situations  for example:
[MSDN suggestion to catch HttpUnhandledException](https://docs.microsoft.com/en-us/aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/aspnet-error-handling)
[Stackoverflow suggestion to catch ThreadAbort](https://stackoverflow.com/questions/434859/handling-application-error-in-asp-net-apps-global-asax)

Neither **IHttpHandler.ProcessRequest** nor **HttpException** documentation gives idea they are going together.

There is only some brief explanation [in msdn here](https://msdn.microsoft.com/en-us/library/24395wz3.aspx)
and less useful:
[MSDN suggestion to catch HttpUnhandledException](https://docs.microsoft.com/en-us/aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/aspnet-error-handling)
[Stackoverflow suggestion to catch ThreadAbort](https://stackoverflow.com/questions/434859/handling-application-error-in-asp-net-apps-global-asax)


So finally, I assume we can ignore all **HttpException** instances that came to **HttpApplication** from handlers (in case we don't care was client disconnected or no, which status was returned and so on) or at least we can ignore some range of **HttpException.ErrorCode**.
