### ISSUE TITLE
Optional Parameters

### ISSUE THREAD

**Issue by voidmonk** [SignalR/SignalR#324] opened 2012-04-18 22:52 UTC
A minor issue I came across today. The client fails to make a call to a server method (error: Value cannot be null), if the server method accepts optional parameters and the client call excludes the optional parameter:

Server:

```
public void GetAll(long Id, bool DoSomething=false)
```

Client:

```
myHub.GetAll(12);
```

**Comment by moozzyk** [comment] 2015-12-08 19:32
@JasonBSteele - I know it's been a while but the issue you are mentioning was just fixed. Expect to see it in the next release.

**Comment by paulirwin** [comment] 2016-05-27 15:35
I'm confused as to the status of this issue. Has it been fixed in any SignalR release?

**Comment by moozzyk** [comment] 2016-05-27 17:00
@paulirwin No

**Comment by snekbaev** [comment] 2016-11-07 14:54
...

**Comment by moozzyk** [comment] 2016-11-07 17:40
The fix is in 2.2.1 that shipped in July (https://github.com/SignalR/SignalR/releases/tag/2.2.1)

**Comment by snekbaev** [comment] 2016-11-08 12:39
I retested what I can into yesterday, here are my findings:
Hub method that client will call
```
public async Task EpicMethod( int? daysTillNETStandard20 ) {}
```

.NET client server method invocation attempts:
```
1. await _serviceRequestHubProxy.Invoke(nameof(ISomethingOnServerSide.EpicMethod), null).ConfigureAwait(false);

System.ArgumentNullException: Value cannot be null.
Parameter name: args
   at Microsoft.AspNet.SignalR.Client.Hubs.HubProxy.Invoke[TResult,TProgress](String method, Action`1 onProgress, Object[] args)
   at Microsoft.AspNet.SignalR.Client.Hubs.HubProxy.Invoke(String method, Object[] args)

2. await _serviceRequestHubProxy.Invoke(nameof(ISomethingOnServerSide.EpicMethod), null, null).ConfigureAwait(false);

System.InvalidOperationException: 'EpicMethod' method could not be resolved. Potential candidates are: 
EpicMethod(daysTillNETStandard20:Nullable`1):Task

3. await _serviceRequestHubProxy.Invoke(nameof(ISomethingOnServerSide.EpicMethod), null, new object[] {}).ConfigureAwait(false);

System.InvalidOperationException: 'EpicMethod' method could not be resolved. Potential candidates are: 
EpicMethod(daysTillNETStandard20:Nullable`1):Task
4. await _serviceRequestHubProxy.Invoke(nameof(ISomethingOnServerSide.EpicMethod), null, new object[] {null}).ConfigureAwait(false);
System.InvalidOperationException: 'EpicMethod' method could not be resolved. Potential candidates are: 
EpicMethod(daysTillNETStandard20:Nullable`1):Task
```

so for now I removed nullability from the hub method and passing 0 from the client side

**Comment by moozzyk** [comment] 2016-11-08 18:59
Reopening as per your finding...

**Comment by clarghi** [comment] 2016-11-22 10:13
I have this problem too. Will be resolved?

**Comment by anurse** [comment] 2017-01-25 00:42
Sounds like a simple matter of the binder not converting `null` to a `Nullable<T>`. I'll investigate.

**Comment by mikaelm12** [comment] 2017-01-27 20:07
So turns out that this is actually by design. How you should actually be passing in an object array with the value of null. Like this using your example
`await _serviceRequestHubProxy.Invoke(nameof(ISomethingOnServerSide.EpicMethod), new object[] {null}).ConfigureAwait(false);`

What you were doing was setting the params array that the parameter resolver was using to null instead of passing in a null value into a params array.

**Closed by mikaelm12** 2017-01-27 20:07 UTC
Labels: bug, investigate

**Comment by AlameerAshraf** [comment] 2017-11-04 08:59
Is the problem supposed to be solved in the current version? Since the Issue date was 5 years ago, But Optional parameters still doesn't work for me?

**Comment by IanIsFluent** [comment] 2019-10-16 12:10
Yeah this feature doesn't work as intended I don't think. We had a call with no parameters, which I'm looking to add a parameter to.

Unfortunately there's no way to do this without breaking backwards compatibility, because if I call with no arguments I get System.IO.InvalidDataException: Invocation provides 0 argument(s) but target expects 1. Even with a single nullable optional parameter.

If I have to change my client to pass a null, then I can't maintain backwards compatibility, and may as well not use the optional parameter at all :(

Workaround: Add and call a new method with a different name, which forwards back to the original one if no parameter passed. Disappointing 👎

**Comment by MichelArendt** [comment] 2019-10-22 11:55
I really think that optional method parameters and overloading should be supported - this might be overdue already.

**Comment by sulemanmuqeed** [comment] 2020-08-07 10:16
Here in 2020 method overloading works but optional parameters don't, anyway I think it is still easy to simply call parametrized method from non parametrized and keeping backward compatibility.

**Comment by Deel96** [comment] 2021-03-05 09:37
I face the same problem, that I can't leave out an optional parameter/ setting it to null without resulting in an error in the signalr hub
