### ISSUE TITLE
Decouple from jQuery?

### ISSUE THREAD

**Issue by amcdnl** [SignalR/SignalR#3658] opened 2016-03-10 14:22 UTC
Is there any plans to decouple Signalr from jQuery?

More and more people are discontinuing use of jQuery as browser apis get better and frameworks like angular do jq-lite implementations.

I plan to prune jQuery from my project but can't because of this.

**Comment by raybooysen** [comment] 2016-03-26 11:32
This is a dupe of #372

**Closed** 2016-03-28 12:11 UTC
