### ISSUE TITLE
Mocking Hub<T>.Clients is not mockable

### ISSUE THREAD

**Issue by YakupIpek** [SignalR/SignalR#3388] opened 2015-01-18 16:45 UTC
None generic `Hub.Clients` property which has getter and setter but `Hub<T>.Clients` has only getter so i couldn't able to mock it.Here is the Hub contracts
```c#
public abstract class Hub : HubBase
{
        protected Hub();
        public IHubCallerConnectionContext<dynamic> Clients { get; set; }
}

public abstract class Hub<T> : HubBase where T : class
{
        protected Hub();
        public IHubCallerConnectionContext<T> Clients { get; }
}
```
As you see Clients property sign is not same with eachother. It would be better design to keep Hub and `Hub<T>` classes similar or at least providing a way override or settable Clients property for `Hub<T>` .

**Comment by YakupIpek** [comment] 2015-01-18 22:26
Request clarified

**Comment by DamianEdwards** [comment] 2015-01-20 00:47
Dupe of #3299

**Closed by DamianEdwards** 2015-01-20 00:47 UTC
Labels: dupe
