### ISSUE TITLE
Load test

### ISSUE THREAD

**Issue by daoqiang** [SignalR/SignalR#4140] opened 2018-06-27 07:50 UTC
I use your crank testing tools to test.
When I test it with this command:
.\crank.exe /Connections:10000 /BatchSize:100 /SendBytes:5120 /Url:http://mysignalr.xxx
The number of connections can reach 6000，But in the sending phase, there is an exception
Exception:System.InvalidOperationException: Data cannot be sent because the WebSocket connection is reconnecting

When I test it with this command:
.\crank.exe /Connections:500 /BatchSize:100 /SendBytes:5120 /Url:http://mysignalr.xxx
The number of connections can reach 800,But in the sending phase，there was an exception after two minutes of test
Exception:System.InvalidOperationException: Data cannot be sent because the WebSocket connection is reconnecting

Why, where is the problem, is my server performance is not enough, or test tool problem?

**Comment by anurse** [comment] 2018-06-27 16:01
What is your server running on? Can you provide more detailed specs?

**Comment by daoqiang** [comment] 2018-06-28 02:51
My signalr service sends data to the client at all times,Detailed information is what it means

**Comment by daoqiang** [comment] 2018-06-28 14:12
hello？

**Comment by anurse** [comment] 2018-06-28 16:28
What kind of server is it though? Physical machine? Virtual machine? Azure App Service?

**Comment by daoqiang** [comment] 2018-06-29 00:55
AWS cloud host，It should be a cloud virtual machine

**Comment by anurse** [comment] 2018-06-29 15:58
I'm not aware of any explicit limitations on that kind of machine. Have you investigated the CPU/Memory/Network consumption at the time that failures begin occurring? Can you provide code from your sample application? With the numbers you provided, I don't believe it's a problem with the test tool.

We need a lot more detail if we're going be able to help identify performance issues in your application. We've run test applications in benchmark environments and gotten as high as 150,000 concurrent connections on a machine with 10GB memory ([source](https://twitter.com/DamianEdwards/status/486642486350061568)) but those are very controlled environments, so they aren't guaranteed to apply to your scenario.

**Comment by daoqiang** [comment] 2018-06-30 03:04
This signalr service takes up about cpu28% and memory about 800m when the connection reaches 6000.
test url:52.192.58.82:7181/signalr

**Comment by daoqiang** [comment] 2018-06-30 03:08
The technology used by the server is self-host+signalr+owin.

**Comment by anurse** [comment] 2018-07-02 15:46
Those loads don't seem out of the ordinary or excessive. I don't really have any suggestion here right now. Perhaps something in your application is causing the timeout (maybe you could try a very simple application in the same hosting environment and see if it reproduces the issue?). Or perhaps a load balancer (since you're in AWS, are you using the "Classic" Load Balancer or the Application Load Balancer) causing an issue?

**Comment by anurse** [comment] 2018-08-08 18:53
Closing this as the discussion appears to have concluded. Feel free to comment further if you have additional concerns, we can always open new issues to track work to do.

**Closed by anurse** 2018-08-08 18:53 UTC
Labels: review-investigate
