### ISSUE TITLE
SignalR connection Negotiate in Load Balancing env and then Stops connection

### ISSUE THREAD

**Issue by enjoyflying** [SignalR/SignalR#3427] opened 2015-03-12 06:34 UTC
Hello There,

I have setup BeanStalk Auto Scaling environment with load balancer.

The following is the architecture.

1. Load balancer
2. Two EC2 instance
3. RDS for SQL Server Express Database

Basically my application is build with Asp.Net MVC.

We are using SignalR for real time web application. ( http://signalr.net/ )

Now I have very strange issue when I deploy my application in Multi server environment i.e. with Load Balancing environment.

The issue is my app when deployed in multi-server environment SignalR is not working.
While app is working perfectly fine with single server.

I am getting following message in my browser's developer console.

SignalR: Client subscribed to hub 'livebidhub'
SignalR: Negotiating with '/signalr/negotiate?connectionData=%5B%7B%22name%22%3A%22livebidhub%22%7D%5D&clientProtocol=1.3'
...
...
...
SignalR: Stopping connection.

This goes on... it doesn't go further.

Please review attached screenshot for the reference.

I have already tried may tweaks and solutions available from Internet however nothing works with Multiserver environment.
I have tried following example from Microsoft for Scaling out SignalR. 
http://www.asp.net/signalr/overview/performance/scaleout-with-sql-server 

I would really appreciate if I can get any kind of assistance with this issue.

Thanks
![signalr issue](https://cloud.githubusercontent.com/assets/11436130/6613228/91a0deb8-c8af-11e4-9d81-c04464e20dfc.png)

**Comment by akempe** [comment] 2015-03-12 20:26
I'm having a similar issue with the following environment and it's driving me nuts:

- Azure LB
- 2x webserver .NET 4.5.1 on Azure
- Redis scaleout
- VERY low traffic
- StackExchange.Redis (1.0.394)

Everything starts off fine after recycling IIS. Then just leaving it there doing a very simple ping/pong every 5 seconds. After about 10-30 mins, if you refresh the page, it fails to negotiate a websocket connection and falls back to long poll. If you refresh again, sometimes within seconds, it will fail to negotiate anything and simply stops trying to connect. Nothing fixes this except recycling IIS.

What is also alarming is that left to its own devices, with no more than 1-3 clients connected, the Redis memory usage will randomly rocket to 200MB (at which point my Redis cluster on Azure maxes out on RAM). Nothing fixes this until you delete the redis cluster and start over.

**Comment by enjoyflying** [comment] 2015-03-13 06:18
I have used SQL Server Backplane and looks like its working fine as of now. Yet I have to go through the actual Load Testing on AWS. You can try SQL Backplane its very easy to configure if you are not that much concerned about performance as of now.

**My problem is solved when I comment out the Machine Key in web.config.**

My be you can try with that, besides now I am back tracking all the solutions that I applied to resolve this issue. So that I can conclude the actual issue.

I will post here once I come across anything. Till now you can try the solution removing Machine Key.

**Comment by akempe** [comment] 2015-03-13 09:14
Thanks for the insight. commenting out the machine key is a bit of an issue because it's going to cause issues with authentication in a load balanced environment.

I've tried servicebus and it seems to be more stable. I've seen a number of redis connection issues in the logs that simply don't go away until restarted. Reading a number of other threads, it appears that the StackExchange.Redis lib may not be very stable at the moment as other people are also having issues with connections that just die.

 Look forward to further details.

**Comment by moozzyk** [comment] 2015-03-13 19:06
Instead of commenting out the machine key you should use the same machine key on all machines.

**Comment by enjoyflying** [comment] 2015-03-16 11:22
Well, there is a new turn in the issue.

First, Thank you for the comments, that drive me to re-think about machine key and investigate further about it.

Putting same machine keys in both instance once again didn't work well, however re-generating a new machine key and updating it into both webconfig files worked.

This time I generated machine key from online forum, while previously I was using the machine key generated from IIS.

@akempe... There are ways to throttle bottleneck performance of the SignalR from Global.asax file.
I will share that information here soon... I strongly suggest to switch over to SQL Backplane. it working really well for me and looks like it will work for more than 1000 concurrent users without any issue, although I have to go through the load testing.

But configuring SQL back plane is really simple, I would assist you if you stuck anywhere with it.

@moozzyk thank you for the suggestion.
I am wondering why machine key is essential in Load balancing environment, what is the significant usage of it?

Thanks All.

**Comment by akempe** [comment] 2015-03-16 11:51
@enjoyflying unfortunately Azure SQL Databases isn't an option as a backplane because it lacks the necessary message broker support. I don't want to have to run my own SQL VM - which is why I'm using Redis/Service Bus

**Comment by moozzyk** [comment] 2015-03-16 18:02
@enjoyflying - the machine key is used when generating the connection token which is then sent to the server from the client with each request. The server validates the token and If the connectionToken does not match the request will be rejected. If you have different machineKey the token created on one machine cannot be decrypted on a different machine hence the token validation fails. Here is more details on how this works: http://www.asp.net/signalr/overview/security/introduction-to-security#connectiontoken

**Comment by moozzyk** [comment] 2015-03-16 18:05
A dupe of #2292

**Closed by moozzyk** 2015-03-16 18:05 UTC
