### ISSUE TITLE
Multiple hub, single dispose error

### ISSUE THREAD

**Issue by atlantim** [SignalR/SignalR#3988] opened 2017-08-12 06:32 UTC
I have two hubs named MainHub and TempHub. When I want to turn off TempHub using the Dispose method, it is also affected by MainHub and all clients on MainHub are ReConnected.

I can not find the reason for  this.

**Comment by davidfowl** [comment] 2017-08-14 06:03
You cant "turn off" a hub, not sure what you mean.

**Comment by atlantim** [comment] 2017-08-14 07:00
There is a library to provide turn off a hub as written; "SignalR.Dispose()" That't what I am trying to do.

I am temporarily creating a new hub when I send a large amount of data to the server for prevent the denial. I want to turn off the port  when I'm done with this temporary hub. Shortly means that I want to kill the second hub.

I wouuld like to share code which I applied;
public class OpenedHubs
    {
        public IDisposable SignalR { get; set; }
        public string url { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
    }

`using (OpenedHubses.Find(u => u.Name == hubName).**SignalR**) ;

 OpenedHubses.Find(u => u.Name == hubName).**SignalR**.Dispose();`


Both codes did not work. I just want to turn off the second hub, but the main hub drops to ReConnected status. I will be appricated if you handle this stutation. Thank you so much already for your help.

**Comment by davidfowl** [comment] 2017-08-14 07:33
> There is a library to provide turn off a hub as written; "SignalR.Dispose()" That't what I am trying to do.

What library is that?

> I am temporarily creating a new hub when I send a large amount of data to the server for prevent the denial. I want to turn off the port when I'm done with this temporary hub. Shortly means that I want to kill the second hub.

Is this on the client side? Did you try calling Stop on the hub connection (assuming it's the client)?

**Comment by atlantim** [comment] 2017-08-14 07:54
I did not try to stop anything on the client side.  I'm just doing it on the server side.

**Comment by davidfowl** [comment] 2017-08-14 08:01
@atlantim then I don't understand what you're doing:

- Disposing a hub does nothing, hubs exist for a single invocation (unless you did something bad to keep it alive).
- You can't turn off hubs dynamically. Hubs are route through a single http end point and are multiplexed.
- You seem to be storing a list of open hubs. What are those and what makes them "open".

Can you push your ode to a github repository?

**Comment by atlantim** [comment] 2017-08-14 10:36
Unfortunately I don`t have authorization to share the project`s code. I`ll try to explain the issue more clear as long as I can. Let`s suppose I have client and server sides of hubs and I make connection to communicate with each other. Client side always listen to server(you can asuume that, send and receive messages between them) I am also able to create new another hub except mainhub. We create second hub because we dont want mainhub gets busy, we use second hub for send big stack of data from client to server or opposite. When second hub finish its transaction, we stop to secondhub run. The issue is when I stop it, client connection get lost in mainhub then client reconnect to mainhub by itself. I want client always keep connect to mainhub even I stop to secondhub`s run.

**Comment by atlantim** [comment] 2017-08-14 11:55
Shared code snippets in stackoverflow : https://stackoverflow.com/questions/45673968/c-sharp-signalr-multiple-hub-single-hub-dispose

**Comment by davidfowl** [comment] 2017-08-15 10:22
I still don't understand what you're doing. Are you starting multiple web applications? At this point I think running code would be best. An end to end sample that is runnable and an explanation of what the problem is and what the expected behavior is.

**Comment by atlantim** [comment] 2017-08-15 11:24
No, I am using the windows form application. I have two hub connections on the same server application. The client can connect to both. The first hub is chatting with the second hub and sending the file contents with log records. When the log records are finished sending, the client sends a message to shut down the second hub connection and I want the server to shut down the second hub.

But after the second hub shutdown, the connection on the first hub goes back to reconnect.

**Comment by atlantim** [comment] 2017-08-17 07:12
Hi **David**,


I created a simple example of project and shared it on Github Profile. I created two projects as client and server.

Best Regards....

**Comment by aspnet-hello** [comment] 2018-09-20 21:49
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Closed by aspnet-hello** 2018-09-20 21:49 UTC
