### ISSUE TITLE
OnDisconnect() Event is fired delayed / Client not sending disconnect event

### ISSUE THREAD

**Issue by dannybucks** [SignalR/SignalR#4579] opened 2021-08-10 09:25 UTC
I inherited from Hub and overwrote OnDisconnect(). 
In Verison 2.4.1 OnDisconnect() was invoked immediately when a tab/browser was closed. In version 2.4.2 it takes up to several seconds until OnDisconnect() is called and stopCalled parameter is always false. It almost looks like the client is not sending the disconnect event at all. 

Is this a bug or a breaking change? Is there a way to be notified immediately when the tab/browser disconnects?
The behaviour can be reproduced by simply putting a break point in OnDisconnect() and then close the connected tab / browser.

**Comment by BrennanConroy** [comment] 2021-09-02 22:46
Possibly a dupe of https://github.com/SignalR/SignalR/issues/4567

**Comment by BrennanConroy** [comment] 2021-10-14 22:21
Closing as dupe

**Closed by BrennanConroy** 2021-10-14 22:21 UTC
