### ISSUE TITLE
Exception on browser close

### ISSUE THREAD

**Issue by ArjunPathak** [SignalR/SignalR#3358] opened 2014-12-05 12:16 UTC
Hey guys, as I have already found one sibling who was facing same issue and i posted there.
(https://github.com/SignalR/SignalR/issues/2804)
Since it was closed thread I am putting it here to bring it to the notice and could get more information. Here are the details.

We have setup SignalR (2.1.1) server and client in 2 different virtual directories on IIS. We are hosting them on Amazon servers that also configured with ELB (load balancing)

Our requirement is : When user close or refresh the browser/tab then we need to make a hub call to  notify server and back to back 2nd call to stop its current hub. ie. this line : $.connection.hub.stop();
We have keep both calls as follows:

window.onbeforeunload = function (e) {
                if (!isCloseAppInvoked) {   InvokeCloseApp();  }
                return undefined; //To avoid native js message that asks "Are you sure you want to leave this page" };

function onBeforeUnload_Success(response) { $.connection.hub.stop(); }
function onBeforeUnload_Error(response) {   }

Now, the scenario is- Referring the same closed post - If we remove window.onbeforeunload from respective pages, we don't see any instance of exception. We have confirmed this in many test cycles. Also we see these in chrome and firefox also regardless IE.
And as we re-enable this, we get following exceptions. 

Global.asax.cs:: Application_Error() :: System.Web.HttpException</br>The client disconnected.</br>   at System.Web.Hosting.IIS7WorkerRequest.EndRead(IAsyncResult asyncResult)
   at System.Web.HttpBufferlessInputStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<BeginEndReadAsync>b__e(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.StreamReader.<ReadBufferAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.StreamReader.<ReadToEndAsyncInternal>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.OwinRequest.<ReadFormAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.Owin.ServerRequest.<ReadForm>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.Transports.LongPollingTransport.<ProcessSendRequest>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Mapping.MapMiddleware.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)</br>/beastappscore/signalr/send?transport=longPolling&clientProtocol=1.4&connectionToken=tB9RjeQKi3ZQVa%2FaoJQeWvYoAykSJGi4vWvWAm5VRBGQjYp5bj4IEI2je%2FVqDzMJpnuTI614AGnVAyJz1HOrEZARVK0vuhpPkama%2B6Ebq9DuOSAgZI8gV3ZU2UECkvKI&connectionData=%5B%7B%22name%22%3A%22marketdatahub%22%7D%5D

> > IIS side event viewer shows 
> > Event Id = 1309 and 
> > Eventcode = 3005 (for signalr server virtual directory)
> > Eventcode = 3012 (for signalr client virtual directory)

Please let us know your thoughts. We are more happy to give you further configuration details whatever you want.

Thanks in advance..

**Comment by ArjunPathak** [comment] 2015-01-20 06:45
Has anyone got any fix or workaround for this ?

**Comment by aspnet-hello** [comment] 2018-09-20 22:10
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Closed by aspnet-hello** 2018-09-20 22:10 UTC

**Comment by jzabroski** [comment] 2018-09-20 22:18
Last I recall, this issue was a wont fix and by design. THIS ISSUE is why I don't use SignalR.

**Comment by anurse** [comment] 2018-09-20 22:49
Unfortunately this issue is beyond SignalR's control since it is coming from the ASP.NET hosting infrastructure. The underlying TCP connection is being closed by the browser while SignalR is in the middle of invoking a method so the exception occurs. Browsers don't provide us a way to guarantee the connection stays open (they don't want JavaScript to be able to hold on to resources after the page is unloaded) so the browser forcibly closes the connection and triggers this exception on the server.

**Comment by jzabroski** [comment] 2018-09-21 02:08
Then don't host it in ASP.NET.

**Comment by anurse** [comment] 2018-09-21 16:11
You're welcome to not host your app on ASP.NET, SignalR supports Owin self-host just fine.

**Comment by jzabroski** [comment] 2018-09-21 22:03
Does the exception on browser close behavior change if you change the host?

**Comment by anurse** [comment] 2018-09-21 23:33
To be clear, SignalR isn't really in control of the events that trigger this exception. Calling `.stop` in an `onbeforeunload` handler is an inherant race between the stop request completing and the browser unloading the page. We can't stop the browser from continuing to unload the page, and if the stop request doesn't get all the way through before the browser unloads the page (and terminates the TCP connection) then most hosts will raise some kind of error for that request since the TCP connection was terminated out from under it.
