### ISSUE TITLE
SignalR CORS not working in AZURE

### ISSUE THREAD

**Issue by theoporto** [SignalR/SignalR#3709] opened 2016-06-08 01:43 UTC
I need use CORS with Signalr in AZURE but it doesn't work. I tryed set CorsOptions.All, then I tried configure in AZURE CORS config only, but I had no success.
In the same project, I use CORS in the WebApi and works fine.

Somebody help me?

My Startup.cs

  ```
app.UseCors(CorsOptions.AllowAll);

            //config.Routes.MapHubs(new HubConfiguration()
            //{
            //    EnableCrossDomain = true
            //});

            app.MapSignalR();
            
            //app.Map("/signalr", map =>
            //{
            //    map.UseCors(SignalrCorsOptions.Value);
            //    var hubConfiguration = new HubConfiguration {  };
            //    map.RunSignalR(hubConfiguration);
            //});

            GlobalConfiguration.Configure(WebApiConfig.Register);
```

**Comment by vensa-lzhang** [comment] 2016-07-22 04:48
My project doesn't have an issue with CORS. In addition to app.UserCors, I also kept the map.UseCors inside app.Map. Maybe the issue is there?

**Comment by moozzyk** [comment] 2016-09-02 19:13
Closing as per @vensa-lzhang comment.

**Closed by moozzyk** 2016-09-02 19:13 UTC
