### ISSUE TITLE
Running SignalR on mono version >4

### ISSUE THREAD

**Issue by wmmihaa** [SignalR/SignalR#3499] opened 2015-06-05 11:57 UTC
Hi, i had my application (which is using SignalR) running on mono running just fine. But after updating mono from 3.something to the latest (4.something) the application stopped working, saying it couldn't establish connection. I tried to recompile the signalR solution but it seams that is not possible, as I get the following error:

/SignalR/.nuget/NuGet.targets: error : Command 'mono --runtime=v4.0.30319/SignalR/.nuget/NuGet.exe install "packages.config" -source "https://nuget.org/api/v2/;http://www.myget.org/F/aspnetwebstacknightly/"   -RequireConsent -solutionDir "/SignalR/" -nocache' exited with code: 2.

I know the latest update of mono was pretty big, adding all the .Net libraries from MS. Has anyone tried using SignalR with the latest build of mono?

**Comment by moozzyk** [comment] 2015-06-05 17:44
This is most likely a duplicate of https://github.com/aspnet/SignalR-Server/issues/93

**Closed by moozzyk** 2015-06-05 17:44 UTC
