### ISSUE TITLE
The NullReferenceException generated by Connection.Stop caused the client console program to crash

### ISSUE THREAD

**Issue by cysnet** [SignalR/SignalR#4519] opened 2021-01-07 01:43 UTC
### Expected  behavior
No NullReferenceException
### Actual behavior
```
System.NullReferenceException
   Microsoft.AspNet.SignalR.Client.Connection.Stop(System.TimeSpan) 
   Microsoft.AspNet.SignalR.Client.Connection.Stop(System.Exception, System.TimeSpan) 
   Microsoft.AspNet.SignalR.Client.Transports.TransportHelper.VerifyLastActive(Microsoft.AspNet.SignalR.Client.IConnection) 
   Microsoft.AspNet.SignalR.Client.Connection.Microsoft.AspNet.SignalR.Client.IConnection.MarkActive() 
   Microsoft.AspNet.SignalR.Client.HeartbeatMonitor.Beat(System.TimeSpan) 
   System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) 
   System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) 
   System.Threading.TimerQueueTimer.CallCallback() 
   System.Threading.TimerQueueTimer.Fire() 
   System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() 
   System.Threading.ThreadPoolWorkQueue.Dispatch() 
```

**Comment by BrennanConroy** [comment] 2021-01-07 02:01
Looks like a dupe of https://github.com/SignalR/SignalR/issues/4458

**Closed** 2021-01-20 22:42 UTC
