### ISSUE TITLE
No transport could be initialized successfully. Try specifying a different transport or none at all for auto initialization. 

### ISSUE THREAD

**Issue by Mds92** [SignalR/SignalR#3148] opened 2014-07-22 06:00 UTC
I'm using MVC5 and SignalR 2.1.0 & Chrome 36
The following is my javascript code in webpage:

<pre>
        $.connection.hub.logging = true;
        $.connection.hub.error(function (error) {
            console.log('SignalR Error: ' + error);
        });

        $.connection.hub.start().done(function () {
            alert('connected');
        });</pre>

The following is auto generated script by ASP.NET & SignalR

<pre>
/*!
 * ASP.NET SignalR JavaScript Library v2.1.0
 * http://signalr.net/
 *
 * Copyright Microsoft Open Technologies, Inc. All rights reserved.
 * Licensed under the Apache 2.0
 * https://github.com/SignalR/SignalR/blob/master/LICENSE.md
 *
 */

/// <reference path="..\..\SignalR.Client.JS\Scripts\jquery-1.6.4.js" />
/// <reference path="jquery.signalR.js" />
(function ($, window, undefined) {
    /// <param name="$" type="jQuery" />
    "use strict";

    if (typeof ($.signalR) !== "function") {
        throw new Error("SignalR: SignalR is not loaded. Please ensure jquery.signalR-x.js is referenced before ~/signalr/js.");
    }

    var signalR = $.signalR;

    function makeProxyCallback(hub, callback) {
        return function () {
            // Call the client hub method
            callback.apply(hub, $.makeArray(arguments));
        };
    }

    function registerHubProxies(instance, shouldSubscribe) {
        var key, hub, memberKey, memberValue, subscriptionMethod;

        for (key in instance) {
            if (instance.hasOwnProperty(key)) {
                hub = instance[key];

                if (!(hub.hubName)) {
                    // Not a client hub
                    continue;
                }

                if (shouldSubscribe) {
                    // We want to subscribe to the hub events
                    subscriptionMethod = hub.on;
                } else {
                    // We want to unsubscribe from the hub events
                    subscriptionMethod = hub.off;
                }

                // Loop through all members on the hub and find client hub functions to subscribe/unsubscribe
                for (memberKey in hub.client) {
                    if (hub.client.hasOwnProperty(memberKey)) {
                        memberValue = hub.client[memberKey];

                        if (!$.isFunction(memberValue)) {
                            // Not a client hub function
                            continue;
                        }

                        subscriptionMethod.call(hub, memberKey, makeProxyCallback(hub, memberValue));
                    }
                }
            }
        }
    }

    $.hubConnection.prototype.createHubProxies = function () {
        var proxies = {};
        this.starting(function () {
            // Register the hub proxies as subscribed
            // (instance, shouldSubscribe)
            registerHubProxies(proxies, true);

            this._registerSubscribedHubs();
        }).disconnected(function () {
            // Unsubscribe all hub proxies when we "disconnect".  This is to ensure that we do not re-add functional call backs.
            // (instance, shouldSubscribe)
            registerHubProxies(proxies, false);
        });

        proxies['baseHub'] = this.createHubProxy('baseHub'); 
        proxies['baseHub'].client = { };
        proxies['baseHub'].server = {
        };

        proxies['fileDownloaderHub'] = this.createHubProxy('fileDownloaderHub'); 
        proxies['fileDownloaderHub'].client = { };
        proxies['fileDownloaderHub'].server = {
            getFileFromWeb: function (fileUrl, deviceId, wikiId, contentId, proxy) {
                return proxies['fileDownloaderHub'].invoke.apply(proxies['fileDownloaderHub'], $.merge(["GetFileFromWeb"], $.makeArray(arguments)));
             }
        };

        proxies['leecherHub'] = this.createHubProxy('leecherHub'); 
        proxies['leecherHub'].client = { };
        proxies['leecherHub'].server = {
            getDevice: function (devicePageUrl, proxy, leechingImages) {
                return proxies['leecherHub'].invoke.apply(proxies['leecherHub'], $.merge(["GetDevice"], $.makeArray(arguments)));
             },

            getDevices: function (manufacturerName, fromPage, toPage, leechingImages, proxy) {
                return proxies['leecherHub'].invoke.apply(proxies['leecherHub'], $.merge(["GetDevices"], $.makeArray(arguments)));
             },

            getManufacturers: function (proxy) {
                return proxies['leecherHub'].invoke.apply(proxies['leecherHub'], $.merge(["GetManufacturers"], $.makeArray(arguments)));
             },

            setDevice: function (relativeXmlPath, submitImages) {
                return proxies['leecherHub'].invoke.apply(proxies['leecherHub'], $.merge(["SetDevice"], $.makeArray(arguments)));
             },

            setDevices: function (relativeXmlPath, submitImages) {
                return proxies['leecherHub'].invoke.apply(proxies['leecherHub'], $.merge(["SetDevices"], $.makeArray(arguments)));
             },

            setManufacturers: function (relativeXmlPath) {
                return proxies['leecherHub'].invoke.apply(proxies['leecherHub'], $.merge(["SetManufacturers"], $.makeArray(arguments)));
             },

            testProxy: function (fileUrl, proxy) {
                return proxies['leecherHub'].invoke.apply(proxies['leecherHub'], $.merge(["TestProxy"], $.makeArray(arguments)));
             }
        };

        proxies['performanceHub'] = this.createHubProxy('performanceHub'); 
        proxies['performanceHub'].client = { };
        proxies['performanceHub'].server = {
            getData: function () {
                return proxies['performanceHub'].invoke.apply(proxies['performanceHub'], $.merge(["GetData"], $.makeArray(arguments)));
             }
        };

        return proxies;
    };

    signalR.hub = $.hubConnection("/signalr", { useDefaultPath: false });
    $.extend(signalR, signalR.hub.createHubProxies());

}(window.jQuery, window));</pre>

It worked before, and now work sometimes, but most of the times the following error concurred:

<pre>No transport could be initialized successfully. Try specifying a different transport or none at all for auto initialization. </pre>
 

The following is SignalR log:

<pre>[10:12:23 GMT+0330 (Iran Standard Time)] SignalR: Client subscribed to hub 'leecherhub'. jquery.signalR-2.1.0.js:81
[10:12:23 GMT+0330 (Iran Standard Time)] SignalR: Negotiating with '/signalr/negotiate?clientProtocol=1.4&connectionData=%5B%7B%22name%22%3A%22leecherhub%22%7D%5D'. jquery.signalR-2.1.0.js:81
[10:12:23 GMT+0330 (Iran Standard Time)] SignalR: Connecting to websocket endpoint 'ws://localhost:1758/signalr/connect?transport=webSockets&clientProtocol=1.4&connectionToken=Jkvy8rbNQEjgC1pOYdntnedTm2%2BqjlMz9s6Nqt7pgII8J32kePObvocylcBELeYQPvWK3C%2FvXsuwyHMHqgzUaekhXYIH4C%2B0dDD5lAaWcwUYqskGfKJelfx4N3JeyMJ8&connectionData=%5B%7B%22name%22%3A%22leecherhub%22%7D%5D&tid=5'. jquery.signalR-2.1.0.js:81
[10:12:23 GMT+0330 (Iran Standard Time)] SignalR: Websocket opened. jquery.signalR-2.1.0.js:81
[10:12:28 GMT+0330 (Iran Standard Time)] SignalR: webSockets timed out when trying to connect. jquery.signalR-2.1.0.js:81
[10:12:28 GMT+0330 (Iran Standard Time)] SignalR: Closing the Websocket. jquery.signalR-2.1.0.js:81
[10:12:28 GMT+0330 (Iran Standard Time)] SignalR: Attempting to connect to SSE endpoint 'http://localhost:1758/signalr/connect?transport=serverSentEvents&clientProt…fx4N3JeyMJ8&connectionData=%5B%7B%22name%22%3A%22leecherhub%22%7D%5D&tid=3'. jquery.signalR-2.1.0.js:81
[10:12:28 GMT+0330 (Iran Standard Time)] SignalR: EventSource connected. jquery.signalR-2.1.0.js:81
[10:12:33 GMT+0330 (Iran Standard Time)] SignalR: serverSentEvents timed out when trying to connect. jquery.signalR-2.1.0.js:81
[10:12:33 GMT+0330 (Iran Standard Time)] SignalR: EventSource calling close(). jquery.signalR-2.1.0.js:81
[10:12:33 GMT+0330 (Iran Standard Time)] SignalR: This browser supports SSE, skipping Forever Frame. jquery.signalR-2.1.0.js:81
[10:12:34 GMT+0330 (Iran Standard Time)] SignalR: Opening long polling request to 'http://localhost:1758/signalr/connect?transport=longPolling&clientProtocol=…fx4N3JeyMJ8&connectionData=%5B%7B%22name%22%3A%22leecherhub%22%7D%5D&tid=2'. jquery.signalR-2.1.0.js:81
[10:12:34 GMT+0330 (Iran Standard Time)] SignalR: Long poll complete. jquery.signalR-2.1.0.js:81
[10:12:34 GMT+0330 (Iran Standard Time)] SignalR: Opening long polling request to 'http://localhost:1758/signalr/poll?transport=longPolling&messageId=d-5F1D51…fx4N3JeyMJ8&connectionData=%5B%7B%22name%22%3A%22leecherhub%22%7D%5D&tid=4'. jquery.signalR-2.1.0.js:81
[10:12:39 GMT+0330 (Iran Standard Time)] SignalR: longPolling timed out when trying to connect. jquery.signalR-2.1.0.js:81
[10:12:39 GMT+0330 (Iran Standard Time)] SignalR: Aborted xhr request. jquery.signalR-2.1.0.js:81
SignalR Error: Error: No transport could be initialized successfully. Try specifying a different transport or none at all for auto initialization. Device:337
[10:12:39 GMT+0330 (Iran Standard Time)] SignalR: Stopping connection. jquery.signalR-2.1.0.js:81
[10:12:39 GMT+0330 (Iran Standard Time)] SignalR: Fired ajax abort async = true. </pre>

**Comment by niemyjski** [comment] 2015-07-15 15:14
I'm still running into this issue in 2.2. I have over 2.5 million of these errors (yes million). Any ideas on what is causing this?

**Comment by mortenalbring** [comment] 2015-07-21 13:59
Yeah I'm having this issue as well. I'm not specifying any transport and it still often says 

Error: No transport could be initialized successfully. Try specifying a different transport or none at all for auto initialization

However, sometimes it doesn't, and I can't at all figure out why it happens sometimes and why it doesn't happen other times.

**Comment by niemyjski** [comment] 2015-07-21 15:28
@mortenalbring Yep, we aren't specifying a transport either.. https://github.com/exceptionless/Exceptionless/search?utf8=%E2%9C%93&q=signalr

**Comment by mortenalbring** [comment] 2015-07-22 14:39
@niemyjski  For what it's worth, it seems only to happen to me when my web application is running locally. When it's published to Azure, it doesn't seem to happen. It's still quite a nuisance when trying to debug things.

**Comment by niemyjski** [comment] 2015-07-23 14:18
@mortenalbring we've only seen this when we are deployed in Azure :\.

**Comment by durjanh** [comment] 2015-07-28 16:20
@niemyjski do you have the fixed for Azure?

**Comment by vikpai** [comment] 2015-08-04 17:32
I have a similar issue too. It seems to occur on IE 9. 
I cannot reproduce it locally but I can when it gets deployed.
I am using signalr 2.2.
Any thoughts?
I did try increasing the TransportConnectTimeout timeout, but that didnt fix it for me as well.

Thanks
VIkram

**Comment by BraveIT** [comment] 2015-09-01 06:04
I also have the same error too. my signalr version is 2.2.0 and Jquery version is 2.1.4. Because This project is our first try to use signalr to implement real-time. so we don't have suffice knowledge to fix this kind of issues

**Comment by Robert-Sun** [comment] 2015-09-01 06:18
Anyone please help

**Comment by garysharp** [comment] 2015-09-01 06:23
@BraveIT & @Robert-Sun You've provided very little information here about your project/s and scenarios. Consider running through the troubleshooting steps found on the asp.net/signalr website:
http://www.asp.net/signalr/overview/testing-and-debugging/troubleshooting
Also, add JavaScript tracing to get more insight into what's happening:
http://www.asp.net/signalr/overview/testing-and-debugging/enabling-signalr-tracing#javascript
If you still haven't resolved the issue, consider providing specific information about your project, diagnostic information (traces), hosting information, and anything else you feel might be relevant.

**Comment by BraveIT** [comment] 2015-09-01 06:32
@garysharp 
there is the detailed info
[13:57:35 GMT+0800 (China Standard Time)] SignalR: Client subscribed to hub 'checkin'.
jquery.signalR-2.2.0.min.js:8 [13:57:35 GMT+0800 (China Standard Time)] SignalR: Negotiating with '/signalr/negotiate?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22checkin%22%7D%5D'.
jquery.signalR-2.2.0.min.js:8 [13:57:35 GMT+0800 (China Standard Time)] SignalR: webSockets transport starting.
jquery.signalR-2.2.0.min.js:8 [13:57:35 GMT+0800 (China Standard Time)] SignalR: Connecting to websocket endpoint 'wss://f1data.qa.fellowshipone.com/signalr/connect?transport=webSockets&clie…33N5QviXjIeBT0&connectionData=%5B%7B%22name%22%3A%22checkin%22%7D%5D&tid=2'.
jquery.signalR-2.2.0.min.js:8 [13:57:36 GMT+0800 (China Standard Time)] SignalR: Websocket opened.
jquery.signalR-2.2.0.min.js:8 [13:57:40 GMT+0800 (China Standard Time)] SignalR: webSockets transport timed out when trying to connect.
jquery.signalR-2.2.0.min.js:8 [13:57:40 GMT+0800 (China Standard Time)] SignalR: Closing the Websocket.
jquery.signalR-2.2.0.min.js:8 [13:57:40 GMT+0800 (China Standard Time)] SignalR: webSockets transport failed to connect. Attempting to fall back.
jquery.signalR-2.2.0.min.js:8 [13:57:40 GMT+0800 (China Standard Time)] SignalR: serverSentEvents transport starting.
jquery.signalR-2.2.0.min.js:8 [13:57:40 GMT+0800 (China Standard Time)] SignalR: Attempting to connect to SSE endpoint 'https://f1data.qa.fellowshipone.com/signalr/connect?transport=serverSentEve…33N5QviXjIeBT0&connectionData=%5B%7B%22name%22%3A%22checkin%22%7D%5D&tid=6'.
jquery.signalR-2.2.0.min.js:8 [13:57:40 GMT+0800 (China Standard Time)] SignalR: EventSource connected.
jquery.signalR-2.2.0.min.js:8 [13:57:45 GMT+0800 (China Standard Time)] SignalR: serverSentEvents transport timed out when trying to connect.
jquery.signalR-2.2.0.min.js:8 [13:57:45 GMT+0800 (China Standard Time)] SignalR: EventSource calling close().
jquery.signalR-2.2.0.min.js:8 [13:57:45 GMT+0800 (China Standard Time)] SignalR: serverSentEvents transport failed to connect. Attempting to fall back.
jquery.signalR-2.2.0.min.js:8 [13:57:45 GMT+0800 (China Standard Time)] SignalR: foreverFrame transport starting.
jquery.signalR-2.2.0.min.js:8 [13:57:45 GMT+0800 (China Standard Time)] SignalR: Forever Frame is not supported by SignalR on browsers with SSE support.
jquery.signalR-2.2.0.min.js:8 [13:57:45 GMT+0800 (China Standard Time)] SignalR: foreverFrame transport failed to connect. Attempting to fall back.
jquery.signalR-2.2.0.min.js:8 [13:57:45 GMT+0800 (China Standard Time)] SignalR: longPolling transport starting.
jquery.signalR-2.2.0.min.js:8 [13:57:45 GMT+0800 (China Standard Time)] SignalR: Opening long polling request to 'https://f1data.qa.fellowshipone.com/signalr/connect?transport=longPolling&c…hRA94K33N5QviXjIeBT0&connectionData=%5B%7B%22name%22%3A%22checkin%22%7D%5D'.
jquery.signalR-2.2.0.min.js:8 [13:57:50 GMT+0800 (China Standard Time)] SignalR: longPolling transport timed out when trying to connect.
jquery.signalR-2.2.0.min.js:8 [13:57:50 GMT+0800 (China Standard Time)] SignalR: Aborted xhr request.
jquery.signalR-2.2.0.min.js:8 [13:57:50 GMT+0800 (China Standard Time)] SignalR: longPolling transport failed to connect. Attempting to fall back.
jquery.signalR-2.2.0.min.js:8 [13:57:50 GMT+0800 (China Standard Time)] SignalR: Fallback transports exhausted.
index.html:515 SignalR Connecting: Error: No transport could be initialized successfully. Try specifying a different transport or none at all for auto initialization.
jquery.signalR-2.2.0.min.js:8 [13:57:50 GMT+0800 (China Standard Time)] SignalR: Stopping connection.
jquery.signalR-2.2.0.min.js:8 [13:57:50 GMT+0800 (China Standard Time)] SignalR: Fired ajax abort async = true.

**Comment by BraveIT** [comment] 2015-09-01 06:37
About this problem, it's very unstable, sometimes it won't show up. but sometime, it's show up again and again. it's very weird, seems this issue has been fixed after the 2.1.1. but now I use the latest version, namely 2.2.0. there still exist this kind of issue. 

I also longed the TransportTimeOut time from default 5 seconds to 15 seconds. Now I am building and deploy it to our server to have a test

**Comment by radu-matei** [comment] 2015-09-21 14:37
@BraveIT Any developments on this issue? I am experiencing the same issue with SignalR Redis backplane using Autofac as dependency resolver. The issue only appears once I use `resolver.UseRedis();`

I have setup a side project where I use basic SignalR and Autofac and I introduced the Redis scaleout. Strangely, in this project it works without any issues. 

Basically, this is the same code, in the same order. (the only difference is that in the project where it doesn't work I have also WebAPI.   https://github.com/radu-matei/SignalRDependencyInjection

Any development in this issue would be great.

Thanks!

**Comment by niemyjski** [comment] 2015-09-21 15:02
+1

**Comment by radu-matei** [comment] 2015-09-21 16:20
@niemyjski, @BraveIT  Make sure that your packages are up-to-date. For example, I am using Autoafac and WebAPI and my `Autofac.WebApi2` integration was not up-to-date. Simply updating this package made the connection issues go away. Hope this helps!

**Comment by niemyjski** [comment] 2015-09-22 15:14
I'm running all the latest packages.

Thanks
-Blake Niemyjski

**Comment by radu-matei** [comment] 2015-09-23 12:25
Do you install `StackExchange.Redis.StrongName` as a dependency when installing `Microsoft.AspNet.SignalR.Redis`? I found that when I don't install this, this behavior appears. Best of luck.

**Comment by niemyjski** [comment] 2015-09-23 12:31
Yes

**Comment by radu-matei** [comment] 2015-09-23 12:34
Also, make sure that the Redis instance you are using is not part of a cluster, since it wil bounce messages from one instance to the other (using a cluster for pub/sub also caused me some tens of thousands of errors)

**Comment by erico64** [comment] 2015-10-23 21:19
Experiencing the same issue with a new JavaScript client app. and SignalR 2.2.  Happens whether or not a transport protocol is specified

**Comment by Dakoina** [comment] 2015-10-29 18:30
Experiencing the same issue with version 2.2.0 now. Previously I experienced less problems with version 2.0.0. Now the production server is completely useless. All connections to the clients get dropped after one or more hours, resulting in the same error.

Did v2.1.1 help for you or not?

**Comment by erico64** [comment] 2015-10-30 00:12
In my case, it turned out to be an oversight, albeit, not a very straight forward oversight.   
In my initialization code, I specified a SQL connection string, in order to use MS SQL as my backplane.   The problem was, I forgot to create the database specified in my connection string.  Once I created the backplane database, no more errors.

**Comment by cjprieb** [comment] 2016-02-05 20:07
I had this same issue using version 2.2 where it would fail with the error "No transport could be initialized successfully. Try specifying a different transport or none at all for auto initialization." 

I found a StackExchange question (http://stackoverflow.com/questions/19848605/signalr-2-long-polling-protocol-request-actually-times-out-when-not-ran-locall) which was able to help me resolve the issue by increasing the timeout in both the JavaScript:
`$.connection.hub.transportConnectTimeout = 3000;`
and in my C# startup code:
`GlobalHost.Configuration.TransportConnectTimeout = TimeSpan.FromSeconds(10);`

I haven't experimented yet to see how short of a timeout I need or whether both timeouts are needed.

**Comment by SwintDC** [comment] 2016-06-10 11:50
I have the same issue with version 2.2.0.
I have tried the fixes from @cjprieb without succes.

**Comment by sohilww** [comment] 2016-08-11 12:04
Hello! 

I've got some good news for you,  read more  about it here <http://triumph.5n0w.com/e3pdgzdz>

Good wishes, sohil_ww



-- 
Esta mensagem foi verificada pelo sistema de antiv�rus e
 acredita-se estar livre de perigo.

**Comment by sohilww** [comment] 2016-08-26 00:37
Dear, 

I've  met such a cool couple  recently and wanted to share some of their thoughts with you,  they are really interesting and so unusual, here is  the  link  <http://muferogy.bostonburgerbar.com/e3xsvjf>

Cheers, sohil_ww

**Comment by chrisaut** [comment] 2016-08-26 02:24
I reported this spam 15 days ago...why is nothing being done?

**Comment by netsrotr** [comment] 2016-10-25 07:40
This issue still exists in the newest version(s). It might be related to dynamic appending an iframe within a div HTML element and removing them later on: at or immediatly after removing this iframe from HTML DOM, the javascript error is shown, pointing somewhere into SignalR client javascript. Maybe this is of any help.

**Comment by netsrotr** [comment] 2016-10-25 10:46
Long time I belived the error I got was somehow related to SignalR, but finally it was caused by the "browserlink" "_feature_" in newer versions of VS.IDE (2015 in my case). If you test outside your IDE calling your web app and the error is gone, it is very likely an issue with "browserlink". To disable / enable browserlink, see [Using Browser Link in Visual Studio 2013](https://www.asp.net/visual-studio/overview/2013/using-browser-link).

**Comment by elgerm** [comment] 2017-07-21 10:38
I can reproduce this error by turning on redis scaleout in the startup of the signalr server (v2.2.2). When turned on, no transport can be initialized. I'm using the following code:

` RedisScaleoutConfiguration config = new RedisScaleoutConfiguration(ConfigurationManager.ConnectionStrings["RedisConnectionString"].ConnectionString, "website");
                GlobalHost.DependencyResolver.UseRedis(config);`

The connectionstring looks like this:

`<add name="RedisConnectionString" connectionString="localhost:6379,ssl=False,abortConnect=False,connectTimeout=30000,SyncTimeout=15000"/>`

I'm using Stackexchange.Redis.Strongname v 1.2.3

It's odd, because this exact same configuration did work on azure. We recently moved from azure to a VPS, with windows server 2016.

**Comment by moozzyk** [comment] 2017-07-21 16:01
@elgerm - Are you sure SignalR is able to connect to Redis? I did run SignalR with Redis Scalout both locally and on Azure and did not encounter this problem.

**Comment by elgerm** [comment] 2017-07-21 21:07
@moozzyk Locally and azure yes, it works, but not on the VPS running 2016. I'll investigate further this weekend, the connectionstring I mentioned above is the same for redis caching in the API (stackexchange.redis) as for scaling out, I can confirm Redis is working fine with web API on the VPS, only signalr stops working when I uncomment the config section.

**Comment by AndreyGrunyov** [comment] 2017-11-03 22:26
I'm getting the same issue in 2.2.2 (and it appears randomly), but everything was working perfectly during at least last 3 years before I implemented Scaleout with Redis
I added the latest NuGet package Microsoft.AspNet.SignalR.Redis with StackExchange.Redis.StrongName (1.1.608)
And setup it in the same order as described [here](https://github.com/SignalR/SignalR/issues/3148#issuecomment-316968547)
But in my case Redis is standalone on Linux (not in Azure), website with SignalR on Widnows Server 2012
The issue appears randomly

**Comment by FabioGCMagalhaes** [comment] 2018-01-09 12:21
+1 on 2.2.2

> 00:00:31.8838066 - XXXX - WS Connecting to: ws://localhost:8000/signalr/connect?clientProtocol=1.4&transport=webSockets&connectionData=[{"Name":"eventNotificationHub"}]&connectionToken=XXXXXX
> 
> 00:00:36.8940132 - XXXX - WS: OnClose()
> 
> 00:00:36.8950154 - XXXX - Auto: Failed to connect to using transport webSockets. System.TimeoutException: Transport timed out trying to connect
> 
> 00:00:36.8960190 - XXXX - SSE: GET http://localhost:8000/signalr/connect?clientProtocol=1.4&transport=serverSentEvents&connectionData=[{"Name":"eventNotificationHub"}]&connectionToken=XXXXXX
> 
> 00:00:36.9256022 - XXXX - SSE: OnMessage(Data: initialized)
> 
> 00:00:41.9074870 - XXXX - Auto: Failed to connect to using transport serverSentEvents. System.TimeoutException: Transport timed out trying to connect
> 
> 00:00:41.9255364 - XXXX - LP Connect: http://localhost:8000/signalr/connect?clientProtocol=1.4&transport=longPolling&connectionData=[{"Name":"eventNotificationHub"}]&connectionToken=XXXXXX
> 
> 00:00:46.9311243 - XXXX - Auto: Failed to connect to using transport longPolling. System.TimeoutException: Transport timed out trying to connect
> 
> 00:00:46.9562573 - XXXX - Disconnected
> 
> 00:00:46.9567600 - XXXX - Transport.Dispose(XXXX)
> 
> 00:00:46.9580938 - XXXX - Closed
> Exception thrown: 'System.TimeoutException' in mscorlib.dll

Any help is very much appreciated.

**Comment by muratg** [comment] 2018-01-09 18:53
cc @anurse

**Comment by anurse** [comment] 2018-01-09 23:07
@FabioGCMagalhaes can you collect server-side traces using the instructions here: https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing ? You can log traces to the Windows Event Log or to Text Files. Once you've got a trace, can you share it on this issue (preferably via a [Gist](https://gist.github.com/) to avoid a long comment here on this thread). Also, when configuring tracing, I suggest using the `<sources>` section from this config because it has more detailed tracing enabled: https://gist.github.com/moozzyk/5abdc2ff439c179832e143c6a72a3e0a

That will help to identify what is different about your scenario and why we can't reproduce it. Generally the error you are seeing (failing to connect any transport) happens because some error is happening on the server that isn't being exposed to the client.

**Comment by FabioGCMagalhaes** [comment] 2018-01-10 08:35
@anurse Thanks for getting back to me!

I ran my server outside of the Service Fabric to be able to expose all that was going on inside and was able to figure out my problem.
I was using _**GlobalHost.DependencyResolver.UseSqlServer(connectionString);**_, and connecting to a SQL Azure DB that was launching a _**System.PlatformNotSupportedException**_. Changing the DB to a non SQL Azure worked instantly.

**Comment by anurse** [comment] 2018-01-10 20:27
Glad to hear you got it sorted out!

I'm going to close this issue as I don't see any further action items or questions here. For anyone on this thread who is still having an issue, feel free to open a new issue or comment further on this issue if you need assistance!

**Closed by anurse** 2018-01-10 20:27 UTC
Labels: needs repro

**Comment by anurse** [comment] 2018-01-10 20:28
@AndreyGrunyov If you are still seeing an issue, can you collect server traces (see [my comment above](https://github.com/SignalR/SignalR/issues/3148#issuecomment-356443890)) and open a new issue for that? I just don't want it to get lost in this long thread :)

**Comment by FloriAll** [comment] 2018-02-08 16:54
Hi Guys, some good tips in here. However, we are having this issue still and a high frequency. We are running our instance of Redis (v 4.4.2-35) and signalR (v 2.2.1). Any help on how to resolve this issue is appreciated.

SignalR Error: No transport could be initialized successfully. Try specifying a different transport or none at all for auto initialization.
    at Object.error (https://toyotars.dealer-fx.com/Scripts/vendors/jquery.signalR.js:178:12) [angular]
    at initialize (https://toyotars.dealer-fx.com/Scripts/vendors/jquery.signalR.js:554:38) [angular]
    at onFallback (https://toyotars.dealer-fx.com/Scripts/vendors/jquery.signalR.js:582:22) [angular]
    at InitHandler.transportFailed (https://toyotars.dealer-fx.com/Scripts/vendors/jquery.signalR.js:1133:5) [angular]
    at https://toyotars.dealer-fx.com/Scripts/vendors/jquery.signalR.js:1068:11 [angular]
    at Object.onInvokeTask (webpack-internal:///206:266:37) [angular]
    at ZoneDelegate.invokeTask (webpack-internal:///754:274:40) [angular]
    at Zone.runTask (webpack-internal:///754:151:47) [<root> => angular]
    at ZoneTask.invoke (webpack-internal:///754:345:33) [<root>]
    at data.args.(anonymous function) (webpack-internal:///754:1224:25) [<root>]
(anonymous) @ angular.js?3437:14195
angular.js?3437:14195 Could not Connect!

**Comment by anurse** [comment] 2018-02-08 17:01
Have you collected the server traces I referenced above? This issue is generally masking a server-side issue that's preventing the transports from initializing, thus causing the client to fail to find a working transport.

**Comment by FloriAll** [comment] 2018-02-08 22:35
Thank you @anurse ! We are enabling the traces tonight and will send it in the morning.

**Comment by FloriAll** [comment] 2018-02-12 18:58
@anurse Here is what we see in the logs:

"_index": "cwl-2018.02.12",
  "_type": "prod2",
  "_id": "33862482539801661846243226071627628985197178478719664128",
  "_version": 1,
  "_score": null,
  "_source": {
    "Message": "OnError(a4f23c26-c11b-4a4c-8804-c74e67e73c9c, System.Net.WebSockets.WebSocketException (0x80070026): Reached the end of the file\r\n   at System.Web.WebSockets.WebSocketPipe.<>c__DisplayClass9_0.<ReadFragmentAsync>b__0(Int32 hrError, Int32 cbIO, Boolean fUtf8Encoded, Boolean fFinalFragment, Boolean fClose)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.WebSockets.AspNetWebSocket.<DoWork>d__45`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.WebSockets.AspNetWebSocket.<>c__DisplayClass36_0.<<ReceiveAsyncImpl>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNet.SignalR.WebSockets.WebSocketMessageReader.<ReadMessageAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.<ProcessWebSocketRequestAsync>d__25.MoveNext())",
    "EventLog": "Application",
    "EventID": 0,
    "Application": "SignalRTransportLog",
    "LogLevel": "Error",
    "Source": "API03.prod2.dealer-fx.com",
    "@id": "33862482539801661846243226071627628985197178478719664128",
    "@timestamp": "2018-02-12T14:37:13.000Z",
    "@message": "[Application] [Error] [0] [SignalRTransportLog] [API03.prod2.dealer-fx.com] [OnError(a4f23c26-c11b-4a4c-8804-c74e67e73c9c, System.Net.WebSockets.WebSocketException (0x80070026): Reached the end of the file\r\n   at System.Web.WebSockets.WebSocketPipe.<>c__DisplayClass9_0.<ReadFragmentAsync>b__0(Int32 hrError, Int32 cbIO, Boolean fUtf8Encoded, Boolean fFinalFragment, Boolean fClose)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.WebSockets.AspNetWebSocket.<DoWork>d__45`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.WebSockets.AspNetWebSocket.<>c__DisplayClass36_0.<<ReceiveAsyncImpl>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNet.SignalR.WebSockets.WebSocketMessageReader.<ReadMessageAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.<ProcessWebSocketRequestAsync>d__25.MoveNext())]",
    "@owner": "477751613945",
    "@log_group": "prod2",
    "@log_stream": "API03"
  },
  "fields": {
    "@timestamp": [
      "2018-02-12T14:37:13.000Z"
    ]
  },
  "sort": [
    1518446233000
  ]
}

**Comment by FloriAll** [comment] 2018-02-12 20:15
More captures of the error
[SignalR.txt](https://github.com/SignalR/SignalR/files/1717617/SignalR.txt)

**Comment by FloriAll** [comment] 2018-02-13 14:26
Good morning @anurse! Did you have a chance to review the trace? Is the information provided enough to do a first analysis? Thanks in advance for your help.

**Comment by anurse** [comment] 2018-02-13 17:03
This is an error that occurs external to SignalR. Something is terminate the underlying TCP connection out from under the WebSocket. As an example, see https://github.com/SignalR/SignalR/issues/3823 (though it could be something else causing the issue on your machine).

**Comment by monkey2046** [comment] 2021-01-28 19:27
what's the final solution? Thanks.
