### ISSUE TITLE
Chrome (80) blocking signalr abort request as its a Synchronous XMLHttpRequest

### ISSUE THREAD

**Issue by karimsgithub** [SignalR/SignalR#4448] opened 2020-02-26 22:33 UTC
The latest version of Chrome browser (v80.0.xxxx) is blocking the /signalr/abort requests that are triggered on Page Unload. This is because, Chrome doesn't allow sync XHR in page dismissal. Below is Chrome's feature link: https://chromestatus.com/feature/4664843055398912.

### Expected  behavior
/signalr/abort requests shouldn't be blocked. 

### Actual behavior
/signalr/abort requests are blocked.

### Steps to reproduce
1. Load any web application using SignalR in Chrome latest version (v80.0.xxxx).
2. Wait until the SignalR connection is established. Verify this with /signalr/negotiate, /signalr/connect and /signalr/start requests in network tab. 
3. Refresh the page or navigate to a different page in the app, to trigger Page Unload event which initiates an /signalr/abort call. 
4. Observe in the Console tab of Chrome Developer Tools, the following warning:
**[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.**
5. And notice, no /signalr/abort request being made in Network tab.

**Comment by BrennanConroy** [comment] 2021-02-02 23:41
dupe of https://github.com/SignalR/SignalR/issues/4365

**Closed by BrennanConroy** 2021-02-02 23:41 UTC
