### ISSUE TITLE
Initial messages are not always delivered to reconnecting clients after application pool restart

### ISSUE THREAD

**Issue by xsov** [SignalR/SignalR#3245] opened 2014-08-28 08:57 UTC
We have JavaScript SSE clients reconnecting to a server using persistent connections after an application pool restart. Some clients will miss the initial messages sent from the server. 

This is the scenario:
1. A number of JavaScript clients connect to a server (persistent connection) using server sent events and start receiving data from the server.
2. The application pool that hosts the SignalR service is stopped and then immediately started.
3. PersistentConnection.OnReconnected is invoked from 1 to 3 times for each of the reconnecting clients. When a client is reconnected, the server checks to see if it knows the client (which it does not in the first OnReconnected because it was just restarted), and then immediately starts delivering messages to that client. 
4. Some clients miss the first messages that are sent (using Connection.Send(string,object)). Clients that request the reconnection more than once are prone to miss the first message(s) sent. 

We think that the problem is that the client does not know that the server has accepted the reconnection before it makes another attempt. Messages sent from the server between those attempts are lost.

We have tried increasing connection.reconnectDelay to 5000. Fewer of the clients fail to get the initial message but it does not solve the problem. We have also tried minimizing the work done in OnReconnected (which is very little) to serve the reconnect requests faster, but without luck. We think this is a bug, but can you suggest any workarounds (we can't put sequence numbers on our messages)?

The setup is:
- The number of clients has been varied from 10 to 100.
- PhantomJS 1.9.7 simulates clients
- Windows Server 2012 with IIS 8
- We have tried both SignalR 2.0.3 and SignalR 2.1.1.

Here is the log from one of the clients that fail to get all messages. We have added logging (prefix: "SSE data") of the message received from the event source. Note that the client state changes from reconnecting to connected and then to reconnecting and connected again.
## Last message before application pool restart is received here

```
[13:04:21 GMT+0000 (Coordinated Universal Time)] SignalR: EventSource readyState: 1.
[13:04:21 GMT+0000 (Coordinated Universal Time)] SignalR: EventSource reconnecting due to the server connection ending.
[13:04:23 GMT+0000 (Coordinated Universal Time)] SignalR: EventSource calling close().
##From connection.stateChanged##Connection State Changed from: 'Connected' to 'Reconnecting'
[13:04:23 GMT+0000 (Coordinated Universal Time)] SignalR: serverSentEvents reconnecting.
[13:04:23 GMT+0000 (Coordinated Universal Time)] SignalR: Attempting to connect to SSE endpoint 'http://myserver/Streaming/connection/reconnect?transport=serverSentEvents&messageId=d-9FFA7789-A%2C0%7CX%2C4C%7CY%2C0&clientProtocol=1.4&authorization=eyJhbGciOiJSUzI1NiIsIng1dCI6IkU3QTJEMEE4MDYyQ0IzOUM2RTI4MEVCNDIzOEZGNTUxMUJFOUI0ODkifQ.eyJpc3MiOiJvYSIsImFpZCI6IjciLCJpc2EiOiJUcnVlIiwidGlkIjoiMCIsIm9hYSI6Ijc3Nzc3Iiwic2lkIjoiM2QwYmJkOTFjZTE0NGYzODliOGE5YTExMWIyMWVkZWUiLCJkZ2kiOiIxIiwiZXhwIjoiMTQwOTc0OTM4MyJ9.FC8FYQPrTmas6PMQWL0TsuH_oAtVF7FOo6DbhYIJQYkB-BGIz8WPnZzk7eZxpw8SozycEbvjJV579VcE-A0oEdukN9MnybAZ833rKULMgotXuA5G78qtLHjbsySus3tk26HdPyfnSGJtC_KJQf7PFKOST1GdXZ8JF56XoPMqYfOfXfg_v7QvVsMjkjuxMrQij5snaXUha82x63Xyiwjo4AjZpfKiSSvpKNwwIYq5HfUX5L5YqqHHZPtcI7TqNarRuknB7m3WfLMcc7avMsgMVfDKvZVdvL6hG7P1apTYqccvUep3TY2qasB47vxpqC81ORBXQNnNFAd-AxjXgXn1vw&context=201407271302589361&connectionToken=hG1RNaFtk8T5IF8E%2BDcCvq1X4bJ1wGwEBSbUrd8MpBQG%2BUmA%2FHWO6WIxP1lx95Vjo4p8I7%2Bp8hUFPSRD%2BmonIgIzqqGdLq8iwXoF%2FkFFEcZTUGa7QVMIR5GrkqKd9pM9&tid=0'.
[13:04:28 GMT+0000 (Coordinated Universal Time)] SignalR: EventSource calling close().
[13:04:28 GMT+0000 (Coordinated Universal Time)] SignalR: serverSentEvents reconnecting.
[13:04:28 GMT+0000 (Coordinated Universal Time)] SignalR: Attempting to connect to SSE endpoint 'http://myserver/Streaming/connection/reconnect?transport=serverSentEvents&messageId=d-9FFA7789-A%2C0%7CX%2C4C%7CY%2C0&clientProtocol=1.4&authorization=eyJhbGciOiJSUzI1NiIsIng1dCI6IkU3QTJEMEE4MDYyQ0IzOUM2RTI4MEVCNDIzOEZGNTUxMUJFOUI0ODkifQ.eyJpc3MiOiJvYSIsImFpZCI6IjciLCJpc2EiOiJUcnVlIiwidGlkIjoiMCIsIm9hYSI6Ijc3Nzc3Iiwic2lkIjoiM2QwYmJkOTFjZTE0NGYzODliOGE5YTExMWIyMWVkZWUiLCJkZ2kiOiIxIiwiZXhwIjoiMTQwOTc0OTM4MyJ9.FC8FYQPrTmas6PMQWL0TsuH_oAtVF7FOo6DbhYIJQYkB-BGIz8WPnZzk7eZxpw8SozycEbvjJV579VcE-A0oEdukN9MnybAZ833rKULMgotXuA5G78qtLHjbsySus3tk26HdPyfnSGJtC_KJQf7PFKOST1GdXZ8JF56XoPMqYfOfXfg_v7QvVsMjkjuxMrQij5snaXUha82x63Xyiwjo4AjZpfKiSSvpKNwwIYq5HfUX5L5YqqHHZPtcI7TqNarRuknB7m3WfLMcc7avMsgMVfDKvZVdvL6hG7P1apTYqccvUep3TY2qasB47vxpqC81ORBXQNnNFAd-AxjXgXn1vw&context=201407271302589361&connectionToken=hG1RNaFtk8T5IF8E%2BDcCvq1X4bJ1wGwEBSbUrd8MpBQG%2BUmA%2FHWO6WIxP1lx95Vjo4p8I7%2Bp8hUFPSRD%2BmonIgIzqqGdLq8iwXoF%2FkFFEcZTUGa7QVMIR5GrkqKd9pM9&tid=5'.
[13:04:33 GMT+0000 (Coordinated Universal Time)] SignalR: EventSource calling close().
[13:04:33 GMT+0000 (Coordinated Universal Time)] SignalR: serverSentEvents reconnecting.
[13:04:33 GMT+0000 (Coordinated Universal Time)] SignalR: Attempting to connect to SSE endpoint 'http://myserver/Streaming/connection/reconnect?transport=serverSentEvents&messageId=d-9FFA7789-A%2C0%7CX%2C4C%7CY%2C0&clientProtocol=1.4&authorization=eyJhbGciOiJSUzI1NiIsIng1dCI6IkU3QTJEMEE4MDYyQ0IzOUM2RTI4MEVCNDIzOEZGNTUxMUJFOUI0ODkifQ.eyJpc3MiOiJvYSIsImFpZCI6IjciLCJpc2EiOiJUcnVlIiwidGlkIjoiMCIsIm9hYSI6Ijc3Nzc3Iiwic2lkIjoiM2QwYmJkOTFjZTE0NGYzODliOGE5YTExMWIyMWVkZWUiLCJkZ2kiOiIxIiwiZXhwIjoiMTQwOTc0OTM4MyJ9.FC8FYQPrTmas6PMQWL0TsuH_oAtVF7FOo6DbhYIJQYkB-BGIz8WPnZzk7eZxpw8SozycEbvjJV579VcE-A0oEdukN9MnybAZ833rKULMgotXuA5G78qtLHjbsySus3tk26HdPyfnSGJtC_KJQf7PFKOST1GdXZ8JF56XoPMqYfOfXfg_v7QvVsMjkjuxMrQij5snaXUha82x63Xyiwjo4AjZpfKiSSvpKNwwIYq5HfUX5L5YqqHHZPtcI7TqNarRuknB7m3WfLMcc7avMsgMVfDKvZVdvL6hG7P1apTYqccvUep3TY2qasB47vxpqC81ORBXQNnNFAd-AxjXgXn1vw&context=201407271302589361&connectionToken=hG1RNaFtk8T5IF8E%2BDcCvq1X4bJ1wGwEBSbUrd8MpBQG%2BUmA%2FHWO6WIxP1lx95Vjo4p8I7%2Bp8hUFPSRD%2BmonIgIzqqGdLq8iwXoF%2FkFFEcZTUGa7QVMIR5GrkqKd9pM9&tid=7'.
[13:04:34 GMT+0000 (Coordinated Universal Time)] SignalR: EventSource connected.
##From connection.stateChanged##Connection State Changed from: 'Reconnecting' to 'Connected'
[13:04:34 GMT+0000 (Coordinated Universal Time)] SignalR: SSE data: {"data":"initialized","origin":"file://","ports":null,"source":null,"lastEventId":"","returnValue":true,"timeStamp":1409144674472,"eventPhase":2,"target":{"readyState":1,"onopen":null,"onerror":null,"URL":"http://myserver/Streaming/connection/reconnect?transport=serverSentEvents&messageId=d-9FFA7789-A%2C0%7CX%2C4C%7CY%2C0&clientProtocol=1.4&authorization=eyJhbGciOiJSUzI1NiIsIng1dCI6IkU3QTJEMEE4MDYyQ0IzOUM2RTI4MEVCNDIzOEZGNTUxMUJFOUI0ODkifQ.eyJpc3MiOiJvYSIsImFpZCI6IjciLCJpc2EiOiJUcnVlIiwidGlkIjoiMCIsIm9hYSI6Ijc3Nzc3Iiwic2lkIjoiM2QwYmJkOTFjZTE0NGYzODliOGE5YTExMWIyMWVkZWUiLCJkZ2kiOiIxIiwiZXhwIjoiMTQwOTc0OTM4MyJ9.FC8FYQPrTmas6PMQWL0TsuH_oAtVF7FOo6DbhYIJQYkB-BGIz8WPnZzk7eZxpw8SozycEbvjJV579VcE-A0oEdukN9MnybAZ833rKULMgotXuA5G78qtLHjbsySus3tk26HdPyfnSGJtC_KJQf7PFKOST1GdXZ8JF56XoPMqYfOfXfg_v7QvVsMjkjuxMrQij5snaXUha82x63Xyiwjo4AjZpfKiSSvpKNwwIYq5HfUX5L5YqqHHZPtcI7TqNarRuknB7m3WfLMcc7avMsgMVfDKvZVdvL6hG7P1apTYqccvUep3TY2qasB47vxpqC81ORBXQNnNFAd-AxjXgXn1vw&context=201407271302589361&connectionToken=hG1RNaFtk8T5IF8E%2BDcCvq1X4bJ1wGwEBSbUrd8MpBQG%2BUmA%2FHWO6WIxP1lx95Vjo4p8I7%2Bp8hUFPSRD%2BmonIgIzqqGdLq8iwXoF%2FkFFEcZTUGa7QVMIR5GrkqKd9pM9&tid=7","onmessage":null},"defaultPrevented":false,"srcElement":{"readyState":1,"onopen":null,"onerror":null,"URL":"http://myserver/Streaming/connection/reconnect?transport=serverSentEvents&messageId=d-9FFA7789-A%2C0%7CX%2C4C%7CY%2C0&clientProtocol=1.4&authorization=eyJhbGciOiJSUzI1NiIsIng1dCI6IkU3QTJEMEE4MDYyQ0IzOUM2RTI4MEVCNDIzOEZGNTUxMUJFOUI0ODkifQ.eyJpc3MiOiJvYSIsImFpZCI6IjciLCJpc2EiOiJUcnVlIiwidGlkIjoiMCIsIm9hYSI6Ijc3Nzc3Iiwic2lkIjoiM2QwYmJkOTFjZTE0NGYzODliOGE5YTExMWIyMWVkZWUiLCJkZ2kiOiIxIiwiZXhwIjoiMTQwOTc0OTM4MyJ9.FC8FYQPrTmas6PMQWL0TsuH_oAtVF7FOo6DbhYIJQYkB-BGIz8WPnZzk7eZxpw8SozycEbvjJV579VcE-A0oEdukN9MnybAZ833rKULMgotXuA5G78qtLHjbsySus3tk26HdPyfnSGJtC_KJQf7PFKOST1GdXZ8JF56XoPMqYfOfXfg_v7QvVsMjkjuxMrQij5snaXUha82x63Xyiwjo4AjZpfKiSSvpKNwwIYq5HfUX5L5YqqHHZPtcI7TqNarRuknB7m3WfLMcc7avMsgMVfDKvZVdvL6hG7P1apTYqccvUep3TY2qasB47vxpqC81ORBXQNnNFAd-AxjXgXn1vw&context=201407271302589361&connectionToken=hG1RNaFtk8T5IF8E%2BDcCvq1X4bJ1wGwEBSbUrd8MpBQG%2BUmA%2FHWO6WIxP1lx95Vjo4p8I7%2Bp8hUFPSRD%2BmonIgIzqqGdLq8iwXoF%2FkFFEcZTUGa7QVMIR5GrkqKd9pM9&tid=7","onmessage":null},"type":"message","cancelable":false,"currentTarget":{"readyState":1,"onopen":null,"onerror":null,"URL":"http://myserver/Streaming/connection/reconnect?transport=serverSentEvents&messageId=d-9FFA7789-A%2C0%7CX%2C4C%7CY%2C0&clientProtocol=1.4&authorization=eyJhbGciOiJSUzI1NiIsIng1dCI6IkU3QTJEMEE4MDYyQ0IzOUM2RTI4MEVCNDIzOEZGNTUxMUJFOUI0ODkifQ.eyJpc3MiOiJvYSIsImFpZCI6IjciLCJpc2EiOiJUcnVlIiwidGlkIjoiMCIsIm9hYSI6Ijc3Nzc3Iiwic2lkIjoiM2QwYmJkOTFjZTE0NGYzODliOGE5YTExMWIyMWVkZWUiLCJkZ2kiOiIxIiwiZXhwIjoiMTQwOTc0OTM4MyJ9.FC8FYQPrTmas6PMQWL0TsuH_oAtVF7FOo6DbhYIJQYkB-BGIz8WPnZzk7eZxpw8SozycEbvjJV579VcE-A0oEdukN9MnybAZ833rKULMgotXuA5G78qtLHjbsySus3tk26HdPyfnSGJtC_KJQf7PFKOST1GdXZ8JF56XoPMqYfOfXfg_v7QvVsMjkjuxMrQij5snaXUha82x63Xyiwjo4AjZpfKiSSvpKNwwIYq5HfUX5L5YqqHHZPtcI7TqNarRuknB7m3WfLMcc7avMsgMVfDKvZVdvL6hG7P1apTYqccvUep3TY2qasB47vxpqC81ORBXQNnNFAd-AxjXgXn1vw&context=201407271302589361&connectionToken=hG1RNaFtk8T5IF8E%2BDcCvq1X4bJ1wGwEBSbUrd8MpBQG%2BUmA%2FHWO6WIxP1lx95Vjo4p8I7%2Bp8hUFPSRD%2BmonIgIzqqGdLq8iwXoF%2FkFFEcZTUGa7QVMIR5GrkqKd9pM9&tid=7","onmessage":null},"bubbles":false,"cancelBubble":false}
[13:04:34 GMT+0000 (Coordinated Universal Time)] SignalR: EventSource readyState: 0.
[13:04:35 GMT+0000 (Coordinated Universal Time)] SignalR: EventSource reconnecting due to the server connection ending.
[13:04:37 GMT+0000 (Coordinated Universal Time)] SignalR: EventSource calling close().
##From connection.stateChanged##Connection State Changed from: 'Connected' to 'Reconnecting'
[13:04:37 GMT+0000 (Coordinated Universal Time)] SignalR: serverSentEvents reconnecting.
[13:04:37 GMT+0000 (Coordinated Universal Time)] SignalR: Attempting to connect to SSE endpoint 'http://myserver/Streaming/connection/reconnect?transport=serverSentEvents&messageId=d-9FFA7789-A%2C0%7CX%2C4C%7CY%2C0&clientProtocol=1.4&authorization=eyJhbGciOiJSUzI1NiIsIng1dCI6IkU3QTJEMEE4MDYyQ0IzOUM2RTI4MEVCNDIzOEZGNTUxMUJFOUI0ODkifQ.eyJpc3MiOiJvYSIsImFpZCI6IjciLCJpc2EiOiJUcnVlIiwidGlkIjoiMCIsIm9hYSI6Ijc3Nzc3Iiwic2lkIjoiM2QwYmJkOTFjZTE0NGYzODliOGE5YTExMWIyMWVkZWUiLCJkZ2kiOiIxIiwiZXhwIjoiMTQwOTc0OTM4MyJ9.FC8FYQPrTmas6PMQWL0TsuH_oAtVF7FOo6DbhYIJQYkB-BGIz8WPnZzk7eZxpw8SozycEbvjJV579VcE-A0oEdukN9MnybAZ833rKULMgotXuA5G78qtLHjbsySus3tk26HdPyfnSGJtC_KJQf7PFKOST1GdXZ8JF56XoPMqYfOfXfg_v7QvVsMjkjuxMrQij5snaXUha82x63Xyiwjo4AjZpfKiSSvpKNwwIYq5HfUX5L5YqqHHZPtcI7TqNarRuknB7m3WfLMcc7avMsgMVfDKvZVdvL6hG7P1apTYqccvUep3TY2qasB47vxpqC81ORBXQNnNFAd-AxjXgXn1vw&context=201407271302589361&connectionToken=hG1RNaFtk8T5IF8E%2BDcCvq1X4bJ1wGwEBSbUrd8MpBQG%2BUmA%2FHWO6WIxP1lx95Vjo4p8I7%2Bp8hUFPSRD%2BmonIgIzqqGdLq8iwXoF%2FkFFEcZTUGa7QVMIR5GrkqKd9pM9&tid=10'.
[13:04:37 GMT+0000 (Coordinated Universal Time)] SignalR: EventSource connected.
##From connection.stateChanged##Connection State Changed from: 'Reconnecting' to 'Connected'
[13:04:37 GMT+0000 (Coordinated Universal Time)] SignalR: SSE data: {"data":"initialized","origin":"file://","ports":null,"source":null,"lastEventId":"","returnValue":true,"timeStamp":1409144677145,"eventPhase":2,"target":{"readyState":1,"onopen":null,"onerror":null,"URL":"http://myserver/Streaming/connection/reconnect?transport=serverSentEvents&messageId=d-9FFA7789-A%2C0%7CX%2C4C%7CY%2C0&clientProtocol=1.4&authorization=eyJhbGciOiJSUzI1NiIsIng1dCI6IkU3QTJEMEE4MDYyQ0IzOUM2RTI4MEVCNDIzOEZGNTUxMUJFOUI0ODkifQ.eyJpc3MiOiJvYSIsImFpZCI6IjciLCJpc2EiOiJUcnVlIiwidGlkIjoiMCIsIm9hYSI6Ijc3Nzc3Iiwic2lkIjoiM2QwYmJkOTFjZTE0NGYzODliOGE5YTExMWIyMWVkZWUiLCJkZ2kiOiIxIiwiZXhwIjoiMTQwOTc0OTM4MyJ9.FC8FYQPrTmas6PMQWL0TsuH_oAtVF7FOo6DbhYIJQYkB-BGIz8WPnZzk7eZxpw8SozycEbvjJV579VcE-A0oEdukN9MnybAZ833rKULMgotXuA5G78qtLHjbsySus3tk26HdPyfnSGJtC_KJQf7PFKOST1GdXZ8JF56XoPMqYfOfXfg_v7QvVsMjkjuxMrQij5snaXUha82x63Xyiwjo4AjZpfKiSSvpKNwwIYq5HfUX5L5YqqHHZPtcI7TqNarRuknB7m3WfLMcc7avMsgMVfDKvZVdvL6hG7P1apTYqccvUep3TY2qasB47vxpqC81ORBXQNnNFAd-AxjXgXn1vw&context=201407271302589361&connectionToken=hG1RNaFtk8T5IF8E%2BDcCvq1X4bJ1wGwEBSbUrd8MpBQG%2BUmA%2FHWO6WIxP1lx95Vjo4p8I7%2Bp8hUFPSRD%2BmonIgIzqqGdLq8iwXoF%2FkFFEcZTUGa7QVMIR5GrkqKd9pM9&tid=10","onmessage":null},"defaultPrevented":false,"srcElement":{"readyState":1,"onopen":null,"onerror":null,"URL":"http://myserver/Streaming/connection/reconnect?transport=serverSentEvents&messageId=d-9FFA7789-A%2C0%7CX%2C4C%7CY%2C0&clientProtocol=1.4&authorization=eyJhbGciOiJSUzI1NiIsIng1dCI6IkU3QTJEMEE4MDYyQ0IzOUM2RTI4MEVCNDIzOEZGNTUxMUJFOUI0ODkifQ.eyJpc3MiOiJvYSIsImFpZCI6IjciLCJpc2EiOiJUcnVlIiwidGlkIjoiMCIsIm9hYSI6Ijc3Nzc3Iiwic2lkIjoiM2QwYmJkOTFjZTE0NGYzODliOGE5YTExMWIyMWVkZWUiLCJkZ2kiOiIxIiwiZXhwIjoiMTQwOTc0OTM4MyJ9.FC8FYQPrTmas6PMQWL0TsuH_oAtVF7FOo6DbhYIJQYkB-BGIz8WPnZzk7eZxpw8SozycEbvjJV579VcE-A0oEdukN9MnybAZ833rKULMgotXuA5G78qtLHjbsySus3tk26HdPyfnSGJtC_KJQf7PFKOST1GdXZ8JF56XoPMqYfOfXfg_v7QvVsMjkjuxMrQij5snaXUha82x63Xyiwjo4AjZpfKiSSvpKNwwIYq5HfUX5L5YqqHHZPtcI7TqNarRuknB7m3WfLMcc7avMsgMVfDKvZVdvL6hG7P1apTYqccvUep3TY2qasB47vxpqC81ORBXQNnNFAd-AxjXgXn1vw&context=201407271302589361&connectionToken=hG1RNaFtk8T5IF8E%2BDcCvq1X4bJ1wGwEBSbUrd8MpBQG%2BUmA%2FHWO6WIxP1lx95Vjo4p8I7%2Bp8hUFPSRD%2BmonIgIzqqGdLq8iwXoF%2FkFFEcZTUGa7QVMIR5GrkqKd9pM9&tid=10","onmessage":null},"type":"message","cancelable":false,"currentTarget":{"readyState":1,"onopen":null,"onerror":null,"URL":"http://myserver/Streaming/connection/reconnect?transport=serverSentEvents&messageId=d-9FFA7789-A%2C0%7CX%2C4C%7CY%2C0&clientProtocol=1.4&authorization=eyJhbGciOiJSUzI1NiIsIng1dCI6IkU3QTJEMEE4MDYyQ0IzOUM2RTI4MEVCNDIzOEZGNTUxMUJFOUI0ODkifQ.eyJpc3MiOiJvYSIsImFpZCI6IjciLCJpc2EiOiJUcnVlIiwidGlkIjoiMCIsIm9hYSI6Ijc3Nzc3Iiwic2lkIjoiM2QwYmJkOTFjZTE0NGYzODliOGE5YTExMWIyMWVkZWUiLCJkZ2kiOiIxIiwiZXhwIjoiMTQwOTc0OTM4MyJ9.FC8FYQPrTmas6PMQWL0TsuH_oAtVF7FOo6DbhYIJQYkB-BGIz8WPnZzk7eZxpw8SozycEbvjJV579VcE-A0oEdukN9MnybAZ833rKULMgotXuA5G78qtLHjbsySus3tk26HdPyfnSGJtC_KJQf7PFKOST1GdXZ8JF56XoPMqYfOfXfg_v7QvVsMjkjuxMrQij5snaXUha82x63Xyiwjo4AjZpfKiSSvpKNwwIYq5HfUX5L5YqqHHZPtcI7TqNarRuknB7m3WfLMcc7avMsgMVfDKvZVdvL6hG7P1apTYqccvUep3TY2qasB47vxpqC81ORBXQNnNFAd-AxjXgXn1vw&context=201407271302589361&connectionToken=hG1RNaFtk8T5IF8E%2BDcCvq1X4bJ1wGwEBSbUrd8MpBQG%2BUmA%2FHWO6WIxP1lx95Vjo4p8I7%2Bp8hUFPSRD%2BmonIgIzqqGdLq8iwXoF%2FkFFEcZTUGa7QVMIR5GrkqKd9pM9&tid=10","onmessage":null},"bubbles":false,"cancelBubble":false}
[13:04:37 GMT+0000 (Coordinated Universal Time)] SignalR: SSE data: {"data":"{\"C\":\"d-F4472558-C,0|f,4|g,0\",\"M\":[[{\"Data\":[{\"Id\":56,\"Text\":\"6\",\"Value\":5},{\"Id\":57,\"Text\":\"Text\",\"Value\":3},{\"Id\":58,\"Text\":\"Text\",\"Value\":55},{\"Id\":59,\"Text\":\"Text\",\"Value\":0},{\"Id\":60,\"Text\":\"Text\",\"Value\":0},{\"Id\":61,\"Text\":\"Text\",\"Value\":1},{\"Id\":62,\"Text\":\"Text\",\"Value\":0},{\"Id\":63,\"Text\":\"Text\",\"Value\":29},{\"Id\":64,\"Text\":\"Text\",\"Value\":0},{\"Id\":65,\"Text\":\"Text\",\"Value\":0}],\"ReferenceId\":\"test_201407271303028421_0\",\"Timestamp\":\"2014-08-27T13:04:37.6500952Z\"}]]}","origin":"file://","ports":null,"source":null,"lastEventId":"","returnValue":true,"timeStamp":1409144677648,"eventPhase":2,"target":{"readyState":1,"onopen":null,"onerror":null,"URL":"http://myserver/Streaming/connection/reconnect?transport=serverSentEvents&messageId=d-9FFA7789-A%2C0%7CX%2C4C%7CY%2C0&clientProtocol=1.4&authorization=eyJhbGciOiJSUzI1NiIsIng1dCI6IkU3QTJEMEE4MDYyQ0IzOUM2RTI4MEVCNDIzOEZGNTUxMUJFOUI0ODkifQ.eyJpc3MiOiJvYSIsImFpZCI6IjciLCJpc2EiOiJUcnVlIiwidGlkIjoiMCIsIm9hYSI6Ijc3Nzc3Iiwic2lkIjoiM2QwYmJkOTFjZTE0NGYzODliOGE5YTExMWIyMWVkZWUiLCJkZ2kiOiIxIiwiZXhwIjoiMTQwOTc0OTM4MyJ9.FC8FYQPrTmas6PMQWL0TsuH_oAtVF7FOo6DbhYIJQYkB-BGIz8WPnZzk7eZxpw8SozycEbvjJV579VcE-A0oEdukN9MnybAZ833rKULMgotXuA5G78qtLHjbsySus3tk26HdPyfnSGJtC_KJQf7PFKOST1GdXZ8JF56XoPMqYfOfXfg_v7QvVsMjkjuxMrQij5snaXUha82x63Xyiwjo4AjZpfKiSSvpKNwwIYq5HfUX5L5YqqHHZPtcI7TqNarRuknB7m3WfLMcc7avMsgMVfDKvZVdvL6hG7P1apTYqccvUep3TY2qasB47vxpqC81ORBXQNnNFAd-AxjXgXn1vw&context=201407271302589361&connectionToken=hG1RNaFtk8T5IF8E%2BDcCvq1X4bJ1wGwEBSbUrd8MpBQG%2BUmA%2FHWO6WIxP1lx95Vjo4p8I7%2Bp8hUFPSRD%2BmonIgIzqqGdLq8iwXoF%2FkFFEcZTUGa7QVMIR5GrkqKd9pM9&tid=10","onmessage":null},"defaultPrevented":false,"srcElement":{"readyState":1,"onopen":null,"onerror":null,"URL":"http://myserver/Streaming/connection/reconnect?transport=serverSentEvents&messageId=d-9FFA7789-A%2C0%7CX%2C4C%7CY%2C0&clientProtocol=1.4&authorization=eyJhbGciOiJSUzI1NiIsIng1dCI6IkU3QTJEMEE4MDYyQ0IzOUM2RTI4MEVCNDIzOEZGNTUxMUJFOUI0ODkifQ.eyJpc3MiOiJvYSIsImFpZCI6IjciLCJpc2EiOiJUcnVlIiwidGlkIjoiMCIsIm9hYSI6Ijc3Nzc3Iiwic2lkIjoiM2QwYmJkOTFjZTE0NGYzODliOGE5YTExMWIyMWVkZWUiLCJkZ2kiOiIxIiwiZXhwIjoiMTQwOTc0OTM4MyJ9.FC8FYQPrTmas6PMQWL0TsuH_oAtVF7FOo6DbhYIJQYkB-BGIz8WPnZzk7eZxpw8SozycEbvjJV579VcE-A0oEdukN9MnybAZ833rKULMgotXuA5G78qtLHjbsySus3tk26HdPyfnSGJtC_KJQf7PFKOST1GdXZ8JF56XoPMqYfOfXfg_v7QvVsMjkjuxMrQij5snaXUha82x63Xyiwjo4AjZpfKiSSvpKNwwIYq5HfUX5L5YqqHHZPtcI7TqNarRuknB7m3WfLMcc7avMsgMVfDKvZVdvL6hG7P1apTYqccvUep3TY2qasB47vxpqC81ORBXQNnNFAd-AxjXgXn1vw&context=201407271302589361&connectionToken=hG1RNaFtk8T5IF8E%2BDcCvq1X4bJ1wGwEBSbUrd8MpBQG%2BUmA%2FHWO6WIxP1lx95Vjo4p8I7%2Bp8hUFPSRD%2BmonIgIzqqGdLq8iwXoF%2FkFFEcZTUGa7QVMIR5GrkqKd9pM9&tid=10","onmessage":null},"type":"message","cancelable":false,"currentTarget":{"readyState":1,"onopen":null,"onerror":null,"URL":"http://myserver/Streaming/connection/reconnect?transport=serverSentEvents&messageId=d-9FFA7789-A%2C0%7CX%2C4C%7CY%2C0&clientProtocol=1.4&authorization=eyJhbGciOiJSUzI1NiIsIng1dCI6IkU3QTJEMEE4MDYyQ0IzOUM2RTI4MEVCNDIzOEZGNTUxMUJFOUI0ODkifQ.eyJpc3MiOiJvYSIsImFpZCI6IjciLCJpc2EiOiJUcnVlIiwidGlkIjoiMCIsIm9hYSI6Ijc3Nzc3Iiwic2lkIjoiM2QwYmJkOTFjZTE0NGYzODliOGE5YTExMWIyMWVkZWUiLCJkZ2kiOiIxIiwiZXhwIjoiMTQwOTc0OTM4MyJ9.FC8FYQPrTmas6PMQWL0TsuH_oAtVF7FOo6DbhYIJQYkB-BGIz8WPnZzk7eZxpw8SozycEbvjJV579VcE-A0oEdukN9MnybAZ833rKULMgotXuA5G78qtLHjbsySus3tk26HdPyfnSGJtC_KJQf7PFKOST1GdXZ8JF56XoPMqYfOfXfg_v7QvVsMjkjuxMrQij5snaXUha82x63Xyiwjo4AjZpfKiSSvpKNwwIYq5HfUX5L5YqqHHZPtcI7TqNarRuknB7m3WfLMcc7avMsgMVfDKvZVdvL6hG7P1apTYqccvUep3TY2qasB47vxpqC81ORBXQNnNFAd-AxjXgXn1vw&context=201407271302589361&connectionToken=hG1RNaFtk8T5IF8E%2BDcCvq1X4bJ1wGwEBSbUrd8MpBQG%2BUmA%2FHWO6WIxP1lx95Vjo4p8I7%2Bp8hUFPSRD%2BmonIgIzqqGdLq8iwXoF%2FkFFEcZTUGa7QVMIR5GrkqKd9pM9&tid=10","onmessage":null},"bubbles":false,"cancelBubble":false}
```

**Comment by halter73** [comment] 2015-01-21 23:35
I am not sure why clients are initially able to re-establish an SSE connection only to have the `EventSource` error handler invoked shortly afterwords without having received any messages. However, I was able to reproduce the other part of this issue (i.e. missing messages) by throwing an exception on `OnReconnected` the first time a client tries to reconnect.

The problem of missing messages stems from the fact that `OnReconnected` is called before the client gets an updated `messageId`. The `messageId` is used to retrieve any messages that are missed while a client is reconnecting.

It is not expected that SignalR will deliver messages sent after the server restarts (or the backplane resets) but *before* a client reconnects. This is because the `messageId` prior to the server restart is invalid and needs to be reset before SignalR can use it again to send messages missed during reconnects.

However, messages sent *after* the client reconnects due to a restart *should* be delivered. Unfortunately, as noted in the issue above, these messages are sometimes still missed if the client reconnects multiple times.

The log shows that the client reconnected again quickly after it appears to have successfully reconnected. The client did not receive an updated `messageId` before it enters the reconnecting state for the second time. This indicates that even though `OnReconnected` was called on the server after the restart, the client still has an invalid `messageId` from before the restart. The `messageId` the client has cannot be used to retrieve messages missed during this second reconnect because it is invalid. This is why messages that were sent to the client due to `OnReconnected` being called the first time may not be received.

One way we could work around this in SignalR is by sending a "reconnected" message for reconnects similar to the "initialize" message we send for normal connect requests. This can be used to ensure the client actually receives an updated `messageId` before calling `OnReconnected`. Unfortunately, this would require substantial changes to both the server and clients.

You could work around this in you own application by only sending important messages to the client after you verify the client has actually received a message following a reconnect. If a client receives a message after a reconnect, it is guaranteed to have an updated `messageId`. It could look something like this.


```c#
public override Task OnReconnected()
{
    return Clients.Caller.ensureReconnected();
}

public Task ReallyReconnected()
{
    // The code that was orignally in OnReconnected
    // If this is called, the client has an updated messageId
}
```

```js
$.connection.myHub.client.ensureReconnected = function () {
    $.connection.myHub.server.reallyReconnected().done(function () {
        // ...
    }).fail(function () {
        // ...
    });
};
```

**Comment by aspnet-hello** [comment] 2018-09-20 22:45
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Closed by aspnet-hello** 2018-09-20 22:45 UTC
