### ISSUE TITLE
System.InvalidOperationException: The stream has been closed.

### ISSUE THREAD

**Issue by JerryBian** [SignalR/SignalR#3113] opened 2014-07-04 07:23 UTC
Recently we met this exception when we called client function like this:

```
 _hubContext.Clients.Group(localGroup.Key).addNewData(...);
```

And we captured exception stack:

<pre>System.InvalidOperationException: The stream has been closed.
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.SendImpl(IEnumerator`1 enumerator, TaskCompletionSource`1 taskCompletionSource)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Send(IList`1 messages)
   at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass1b.<BuildOutgoing>b__19(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipeline.Send(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.SignalProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object , IEnumerable`1 )</pre>

We used Azure Service Bus to scale out, and this exception occurred randomly, can anyone explain what is this exception about and how can we fix it?

**Comment by darakimaia** [comment] 2015-02-12 21:19
I'm running a .Net backend mobile service with signalr scale out (which is configured by default). 
There is one message I'm sending in high frequency.
Currently there is only 1 mobile service instance and when it shuts down, I get this error message.
If I have 1 instance and it goes down, does it mean the "entire" app domain is shut down?

**Comment by niemyjski** [comment] 2015-03-24 12:36
I'm also getting this error recently using the redis scale out (https://github.com/exceptionless/Exceptionless):

```csharp
System.InvalidOperationException: The stream has been closed.
at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(System.Func`2 send, System.Object state) at offset 53
at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(Microsoft.AspNet.SignalR.ConnectionMessage message) at offset 244
at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(Microsoft.AspNet.SignalR.Hubs.IHubOutgoingInvokerContext context) at offset 14
at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass1b.b__19(Microsoft.AspNet.SignalR.Hubs.IHubOutgoingInvokerContext context) at offset 16
at Microsoft.AspNet.SignalR.Hubs.HubPipeline.Send(Microsoft.AspNet.SignalR.Hubs.IHubOutgoingInvokerContext context) at offset 17
at Microsoft.AspNet.SignalR.Hubs.SignalProxy.TryInvokeMember(System.Dynamic.InvokeMemberBinder binder, System.Object[] args, System.Object& result) at offset 0
at ..CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, Exceptionless.Core.Messaging.Models.EntityChanged) at offset -1
at Exceptionless.Api.Hubs.MessageBusHub.OnEntityChanged(Exceptionless.Core.Messaging.Models.EntityChanged entityChanged) at offset 550 in c:\projects\exceptionless\Source\Api\Hubs\MessageBusHub.cs:line 56:col 17
at Foundatio.Redis.Messaging.RedisMessageBus.OnMessage(StackExchange.Redis.RedisChannel channel, StackExchange.Redis.RedisValue value) at offset 283
```

![image](https://cloud.githubusercontent.com/assets/1020579/6801716/5fa81960-d1f8-11e4-9292-d759e4217fa9.png)

We started seeing it when we had a ton of people connected to the site and did a deploy with octopus deploy. It seems like the clients tried to reconnect and we tried sending down notifications but something went wrong.

**Comment by muratg** [comment] 2015-04-06 17:01
@niemyjski Could you provide a simple repro?

**Comment by niemyjski** [comment] 2015-04-06 17:03
All the code is in our repo, I started seeing this when we had 40+ users connected and forced a site reboot. It seemed to happen when some clients couldn't reconnect and the server was attempting to send them data??

**Comment by niemyjski** [comment] 2015-04-06 17:06
I'd be more than happy to help you set up our api server and attempt to reproduce. I've seen this issue happen across three api deployments so I'm sure it's reproducable

**Comment by MaDeRkAn** [comment] 2015-04-10 13:14
I'm also using azure service bus topics for scale out and I'm getting these errors after/while swapping slots.

Can I check the stream is open or not before publishing the message ?

**Comment by groenlid** [comment] 2015-05-11 07:22
We are getting the same error in after every deployment and it seems the only way to fix it is to reset each of the instances.

The stream seems to close when we swap between staging and production.
Have any of you gotten any closer to a solution to this problem?

```
 System.InvalidOperationException: The stream has been closed.
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.SendImpl(IEnumerator`1 enumerator, TaskCompletionSource`1 taskCompletionSource)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Send(IList`1 messages)
   at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.&lt;&gt;c__DisplayClass1b.&lt;BuildOutgoing&gt;b__19(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipeline.Send(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.SignalProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object&amp; result)
   at CallSite.Target(Closure , CallSite , Object , UOWStatus )
   at Services.SignalRBroadcaster.Repositories.BaseHubRepository.Post(UOWStatus unitOfWork, Language language)
   at Services.SignalRBroadcaster.Host.MvcApplication.DoWorkWithQueueMessage(UOWStatus value)
   at Common.Libraries.Queue.Consumer.ProcessMessage[T](Func`2 func, BrokeredMessage message)
   at Common.Libraries.Queue.Consumer.&lt;&gt;c__DisplayClass2`1.&lt;AttachToQueue&gt;b__1(BrokeredMessage message) System.InvalidOperationException: The stream has been closed.
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.SendImpl(IEnumerator`1 enumerator, TaskCompletionSource`1 taskCompletionSource)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Send(IList`1 messages)
   at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.&lt;&gt;c__DisplayClass1b.&lt;BuildOutgoing&gt;b__19(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipeline.Send(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.SignalProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object&amp; result)
   at CallSite.Target(Closure , CallSite , Object , UOWStatus )
   at Services.SignalRBroadcaster.Repositories.BaseHubRepository.Post(UOWStatus unitOfWork, Language language)
   at Services.SignalRBroadcaster.Host.MvcApplication.DoWorkWithQueueMessage(UOWStatus value)
   at Common.Libraries.Queue.Consumer.ProcessMessage[T](Func`2 func, BrokeredMessage message)
   at Common.Libraries.Queue.Consumer.&lt;&gt;c__DisplayClass2`1.&lt;AttachToQueue&gt;b__1(BrokeredMessage message)
```

**Comment by niemyjski** [comment] 2015-05-11 13:33
Nope, but I'm seeing this after every deployment as well.

**Comment by celeronpm** [comment] 2015-05-11 20:47
I'm seeing the same issue with SQL scaleout.

**Comment by Chida82** [comment] 2015-07-31 10:57
Same problem.

In my case if one client with trasport 'serverSentEvents' if client or PROXY truncate comunication

System.InvalidOperationException: The stream has been closed.
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStreamManager.Send(Int32 streamIndex, IList`1 messages)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Send(IList`1 messages)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Publish(Message message)
   at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass1b.<BuildOutgoing>b__19(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipeline.Send(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.SignalProxy.Invoke(String method, Object[] args)
   at Microsoft.AspNet.SignalR.Hubs.SignalProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object , DeployProgressMessage )
   at BlendServer.Signalr.Models.DeployProgressSignalR.Step(DeployProgressStep step)

where  step is basicaly
_context.Value.Clients.Group(_groupCpqId).newDeployProgress(.....
and stop task

i think i can use try...catch, but there is a different approach or a global parameter to ignore errors of communication with the outside of SignlR?

**Comment by matthieuklotz** [comment] 2015-08-03 11:38
Hi,

I have the same issue when sending messages to clients from the server and using Redis Backplane  : 

Server stack trace: 
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
   at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass1b.<BuildOutgoing>b__19(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass1b.<BuildOutgoing>b__19(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipeline.Send(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.SignalProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object , JObject )
   at Web.Api.Hubs.StatusObserver.OnNext(Message value) in d:\7788\47\src\Main\Web\Web.Api\Hubs\StatusObserver.cs:line 56

Code :
```csharp
IHubContext context = GlobalHost.ConnectionManager.GetHubContext<DevicesHub>();
context.Clients.Group((string)key).status(value);
```
The API is hosted on an Azure Web Application with two instances and uses Azure Redis cache as backplane.
SignalR version : 2.2.0
StackExchange.Redis : 1.0.481

Is someone found a workaround for this issue ?

**Comment by groenlid** [comment] 2015-08-03 11:53
> Is someone found a workaround for this issue ?

No, sorry. What are you doing to get your application in that state?

**Comment by matthieuklotz** [comment] 2015-08-03 12:06
This state always occurred after those steps :
1. deploy (or restart or other) the application
2. when a client is connected, its devices will push their status on service bus queue. A service bus client, hosted on the API (StatusObserver) will retrieve the messages and will push those statuses to the client.

So I always have at least one client connected on my Hub. If there isn't any client, we do not see the error.
An other application which uses SignalR 2.1 don't have this issue.

**Comment by groenlid** [comment] 2015-08-03 12:51
> An other application which uses SignalR 2.1 don't have this issue

We're currently running SignalR 2.0.3.0 and are experiencing the same error, so it's strange if v2.1 is excepted from this. It seems we're also running the same architecture ( sb-queue -> queueclient ->  hub -> sb-backplane).

Have you tried to enable tracing to eventlog to see if you get any more information?

@davidfowl wrote in the beginning of the thread: 

> The stream only get closed when the app domain shuts down on the server side. This can happen also if you're self hosting and you dispose the server instance/dependency resolver.

Are you able to see anything in the event log that might indicate that this happens?

**Comment by Chida82** [comment] 2015-08-03 15:58
In other case of Error the CPU is on 100%
Can it be help?

**Comment by MaDeRkAn** [comment] 2015-08-04 07:00
We are using 2.2 and we are getting this error while deploy/swap/restart.
Are you sure it's not occur in 2.1 ?

**Comment by thephoenics** [comment] 2016-01-12 18:17
Hi - has anyone found a workaround for this? Or what happens if this exception happens? - does the SignalR connection retry? Or is there a message loss due to this failure - I can live with a retry, but if there is a message loss which we cannot track, it is a cause for concern.

**Comment by jasoncouture** [comment] 2016-01-22 18:04
Same issue here, SQL Server scaleout, haven't tried with redis.

**Comment by aidanmorgan** [comment] 2017-08-04 07:12
I am getting this issue using a Redis backplane.

**Comment by aspnet-hello** [comment] 2018-09-20 22:47
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Closed by aspnet-hello** 2018-09-20 22:47 UTC
Labels: needs repro

**Comment by thakursagar** [comment] 2021-05-13 21:01
Hi - I know this issue was closed in 2018 but we're still encountering this issue with our application. We are on 2.4.1 version of the Microsoft.AspNet.SignalR library. Has anybody figured out why this is happening and how this can be fixed?
