### ISSUE TITLE
MVC5 - SignalR OnDisconnected work each time i click link ?

### ISSUE THREAD

**Issue by ahmedamen** [SignalR/SignalR#3860] opened 2017-02-08 09:05 UTC
Hi

i try to set user online or offline using SignalR- so i have create hub with Code below:

```
public class LoginHub : Hub
    {
        public override System.Threading.Tasks.Task OnConnected()
        {
            // here will set user to be Online in the database using EF
            var username = Context.User.Identity.Name;
            return base.OnConnected();
        }

        public override System.Threading.Tasks.Task OnReconnected()
        {
            var username = Context.User.Identity.Name;
            return base.OnReconnected();
        }

        public override System.Threading.Tasks.Task OnDisconnected(bool s)
        {
            // here will set user to be Offline in the database using EF
            var xx = Context.Headers.GetValues("Host");
            var oooo = xx.FirstOrDefault();
            var username = Context.User.Identity.Name;
            return base.OnDisconnected(true);
        }
    }
```

and i have add js code in the layout :
```
<script>
             $(function() {
             var loghub = $.connection.loginHub;

            debugger;
             loghub.client.SetOnline = function() {};

        // Start the connection.
        $.connection.hub.start().done(function () {

        });
        });
    </script>
```
now when i click any link on the site menu to go to the view i need OnDisconnected fired and that mean it will set user Offline - and after new page is load OnConnected is fired and set user Online again ??!!

so please how can i make OnDisconnected  works only if user close browser or logoff  - not with each request for any page ?

**Comment by davidfowl** [comment] 2017-02-13 14:57
This is by design. The connection disconnects when the browser navigates or is closed (it's the same thing really). You need to take that into account in your application design. You'll need to add some delay (don't mark users as offline immediately).

**Comment by Jenan** [comment] 2017-07-15 10:31
@davidfowl Can you please some example how implement correctly a delay for this behavior? I can't find any example where is this case implemented.

**Comment by aspnet-hello** [comment] 2018-09-20 21:52
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Closed by aspnet-hello** 2018-09-20 21:52 UTC
