### ISSUE TITLE
SignalR.Client Start Fails with NullReferenceException

### ISSUE THREAD

**Issue by kyleclark171** [SignalR/SignalR#3912] opened 2017-04-13 19:01 UTC
### Client
Using `Microsoft.AspNet.SignalR.Client` v2.2.1 (PCL assembly) within Xamarin IOS
### Server
Using `Microsoft.AspNet.SignalR.Core` v2.2.1 in distributed .NET API
Using `Microsoft.AspNet.SignalR.Redis` v2.2.1 to support a Redis Cache Backplane

## Error Information
When starting my client application I create a new `HubConnection`, and connect to the API, using LongPolling transport (this is the default, since WebSockets cannot be used with SignalR.Client PCL). This has been working flawlessly. The error occurs after stopping the hub connection, and when trying to start it once again, or to open a new `HubConnection` to the original Hub. After trying to connect for about 30s, the `StartAsync()` method on my `HubConnection` fails with a `NullReferenceException` within SignalR's `TransportInitializationHandler`. The stack trace for this exception is provided below.

This error only occurs after calling `Stop()` on a hub connection--specifically when `Stop()` hangs (also for about 30s). This part of this issue appears similar to some closed issues in SignalR, but I am still able to reproduce this in the current version (2.2.1). The SignalR output generated during this stop operation suggests that something went wrong while stopping the connection, and that output is also included below.

### Other notes
* I have been able to avoid this issue locally by disabling the Redis Backplane. However this fix is not viable for our production environment.
* After a long wait (up to 15 minutes) new connections can be achieved, until `Stop()` is called again

#### Stop Failure Logs
```
2017-04-13 13:11:55.164 - b7d15bd4-b417-4c47-a370-907f0bf35ff2 - Stop
...
2017-04-13 13:11:55.614 - b7d15bd4-b417-4c47-a370-907f0bf35ff2 - SSE: OnMessage(Data: {})
...
2017-04-13 13:12:05.623 - b7d15bd4-b417-4c47-a370-907f0bf35ff2 - SSE: OnMessage(Data: {})
...
2017-04-13 13:12:15.708 - b7d15bd4-b417-4c47-a370-907f0bf35ff2 - SSE: OnMessage(Data: {})
...
2017-04-13 13:12:25.235 - b7d15bd4-b417-4c47-a370-907f0bf35ff2 - Abort never fired
2017-04-13 13:12:25.236 - b7d15bd4-b417-4c47-a370-907f0bf35ff2 - Disconnected
2017-04-13 13:12:25.237 - b7d15bd4-b417-4c47-a370-907f0bf35ff2 - Transport.Dispose(b7d15bd4-b417-4c47-a370-907f0bf35ff2)
2017-04-13 13:12:25.238 - b7d15bd4-b417-4c47-a370-907f0bf35ff2 - Closed
```

#### Start Failure StackTrace
```
System.AggregateException: One or more errors occurred. ---> Microsoft.AspNet.SignalR.Client.Infrastructure.StartException: Error during start request. Stopping the connection. ---> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Microsoft.AspNet.SignalR.Client.Infrastructure.TransportInitializationHandler.<InitReceived>b__18_0 (System.String response) [0x0000c] in <ae28fd3b31dc4c469fc9728ba8f8e098>:0 
  at Microsoft.AspNet.SignalR.TaskAsyncHelper+TaskRunners`2+<>c__DisplayClass0_0[T,TResult].<RunTask>b__0 (System.Threading.Tasks.Task`1[TResult] t) [0x0003b] in <ae28fd3b31dc4c469fc9728ba8f8e098>:0 
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 
  at 
... 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.AspNet.SignalR.Client.Infrastructure.StartException: Error during start request. Stopping the connection. ---> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Microsoft.AspNet.SignalR.Client.Infrastructure.TransportInitializationHandler.<InitReceived>b__18_0 (System.String response) [0x0000c] in <ae28fd3b31dc4c469fc9728ba8f8e098>:0 
  at Microsoft.AspNet.SignalR.TaskAsyncHelper+TaskRunners`2+<>c__DisplayClass0_0[T,TResult].<RunTask>b__0 (System.Threading.Tasks.Task`1[TResult] t) [0x0003b] in <ae28fd3b31dc4c469fc9728ba8f8e098>:0 
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 
  at ...```

**Comment by moozzyk** [comment] 2017-04-13 19:35
Can you show your code? I think you might be deadlocking yourself (hence the 30-sec-long delay) and then the init message comes after a timeout.

**Comment by kyleclark171** [comment] 2017-04-17 20:55
Hi Pawel,

I found out what this issue was, and verified it this past Friday. What had happened was our Redis Cache was being cleared after certain API requests. This became an issue when the cache was being cleared while an operation occurred on the hub.

What had happened was our client attempted to disconnect shortly after the cache was flushed. I’m assuming that the hub tried to interact with the backplane, but had a cache key miss, since our backplane had been wiped. This eventually resulted in the null-ref exception.

I fixed our cache flush operation to not interfere with SignalR, and this issue is no longer occurring. I think it would be great for debugging purposes to handle this particular edge case with a different exception (or a more descriptive message), but otherwise the SignalR code is working fine.

Thanks for the quick response,


Kyle Clark
Pariveda Solutions
 20 N. Wacker Dr. | Suite 2600 | Chicago, IL 60606
(M) 630.809.5699

**Comment by moozzyk** [comment] 2017-04-17 21:11
I can only assume that the NRE was caused by started being null here: https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client/Infrastructure/TransportInitializationHandler.cs#L104. Since the object is created by deserializing server response - do you know what the response was?

**Comment by aspnet-hello** [comment] 2018-09-20 21:51
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Closed by aspnet-hello** 2018-09-20 21:51 UTC
