### ISSUE TITLE
SignaR Desktop client not detecting when ethernet is disconnected or wireless is off

### ISSUE THREAD

**Issue by hpanamgipalli** [SignalR/SignalR#3460] opened 2015-04-16 03:01 UTC
Hi 
I am using a Web server and WPF desktop app client on multiple devices to pull device information and display them on the web. I am using SignalR version 2.2.0

The desktop apps send data during first time connect which is shown on the web. However if i unplug the ethernet cable and check, the connection status still is showing connected. I am assuming signalr shud detect the disconnection on fire the connection_StateChanged events but none are taking place.
Pls help

**Comment by moozzyk** [comment] 2015-04-16 15:59
What transport are you using?

**Comment by hpanamgipalli** [comment] 2015-04-17 00:41
HI Please check the logs below... the first one is when i connect to the server
Attached the images also

LOG1:
-----------------------------------------
00:30:33.9227671 - 4a0642d4-a131-445e-a877-27b11269bb5b - WS Connecting to: ws://tsdemoserver.cloudapp.net/Signage/signalr/signalr/connect?clientProtocol=1.4&transport=webSockets&connectionData=[{"Name":"PlayerInfoHub"},{"Name":"RestartHub"}]&connectionToken=efDlldCJjDf7CzY%2Fc4wf8mVUveFZBZhSJdLhguQWohC6q4cF%2FJJmA2s2nmcgmq6vjlEeiDLr2GvmVFzs3oOkT8jtfLsrGCTravLG9NLbxB8w6kFu3Tdolhnhy1wV7ZIK
00:30:39.0810679 - 4a0642d4-a131-445e-a877-27b11269bb5b - Auto: Failed to connect to using transport webSockets. System.TimeoutException: Transport timed out trying to connect
00:30:39.1210699 - 4a0642d4-a131-445e-a877-27b11269bb5b - SSE: GET http://tsdemoserver.cloudapp.net/Signage/signalr/signalr/connect?clientProtocol=1.4&transport=serverSentEvents&connectionData=[{"Name":"PlayerInfoHub"},{"Name":"RestartHub"}]&connectionToken=efDlldCJjDf7CzY%2Fc4wf8mVUveFZBZhSJdLhguQWohC6q4cF%2FJJmA2s2nmcgmq6vjlEeiDLr2GvmVFzs3oOkT8jtfLsrGCTravLG9NLbxB8w6kFu3Tdolhnhy1wV7ZIK
00:30:39.3010789 - 4a0642d4-a131-445e-a877-27b11269bb5b - WS: OnClose()
00:30:44.1683651 - 4a0642d4-a131-445e-a877-27b11269bb5b - Auto: Failed to connect to using transport serverSentEvents. System.TimeoutException: Transport timed out trying to connect
00:30:44.1693642 - 4a0642d4-a131-445e-a877-27b11269bb5b - LP Connect: http://tsdemoserver.cloudapp.net/Signage/signalr/signalr/connect?clientProtocol=1.4&transport=longPolling&connectionData=[{"Name":"PlayerInfoHub"},{"Name":"RestartHub"}]&connectionToken=efDlldCJjDf7CzY%2Fc4wf8mVUveFZBZhSJdLhguQWohC6q4cF%2FJJmA2s2nmcgmq6vjlEeiDLr2GvmVFzs3oOkT8jtfLsrGCTravLG9NLbxB8w6kFu3Tdolhnhy1wV7ZIK
00:30:44.4413819 - 4a0642d4-a131-445e-a877-27b11269bb5b - LP: OnMessage({"C":"d-733D7334-B,0|C,0|D,0|E,0|F,3","S":1,"M":[]})
00:30:44.4893828 - 4a0642d4-a131-445e-a877-27b11269bb5b - LP Poll: http://tsdemoserver.cloudapp.net/Signage/signalr/signalr/poll?clientProtocol=1.4&transport=longPolling&connectionData=[{"Name":"PlayerInfoHub"},{"Name":"RestartHub"}]&connectionToken=efDlldCJjDf7CzY%2Fc4wf8mVUveFZBZhSJdLhguQWohC6q4cF%2FJJmA2s2nmcgmq6vjlEeiDLr2GvmVFzs3oOkT8jtfLsrGCTravLG9NLbxB8w6kFu3Tdolhnhy1wV7ZIK&messageId=d-733D7334-B%2C0%7CC%2C0%7CD%2C0%7CE%2C0%7CF%2C3
00:30:44.7613990 - 4a0642d4-a131-445e-a877-27b11269bb5b - ChangeState(Connecting, Connected)
-----------------------------------------------------------------------------

This happens when i request data from the client (i do this from server)

LOG2:
00:33:16.8162499 - 4a0642d4-a131-445e-a877-27b11269bb5b - LP: OnMessage({"C":"d-733D7334-B,1|C,0|D,0|E,0|F,3","M":[{"H":"PlayerInfoHub","M":"getPlayerInfo","A":[1]}]})
00:33:16.8202486 - 4a0642d4-a131-445e-a877-27b11269bb5b - LP Poll: http://tsdemoserver.cloudapp.net/Signage/signalr/signalr/poll?clientProtocol=1.4&transport=longPolling&connectionData=[{"Name":"PlayerInfoHub"},{"Name":"RestartHub"}]&connectionToken=efDlldCJjDf7CzY%2Fc4wf8mVUveFZBZhSJdLhguQWohC6q4cF%2FJJmA2s2nmcgmq6vjlEeiDLr2GvmVFzs3oOkT8jtfLsrGCTravLG9NLbxB8w6kFu3Tdolhnhy1wV7ZIK&messageId=d-733D7334-B%2C1%7CC%2C0%7CD%2C0%7CE%2C0%7CF%2C3
00:33:17.4652867 - 4a0642d4-a131-445e-a877-27b11269bb5b - LP: OnMessage({"C":"d-733D7334-B,2|C,0|D,0|E,0|F,3","M":[{"H":"PlayerInfoHub","M":"ReceiveInfo","A":["<table align='left' border='1' class='table table-striped table-bordered dataTable'>\r\n<tr><td>MachineName</td><td>TSDEV1</td></tr><tr><td>LocalIPAddress</td><td>192.168.23.155</td></tr><tr><td>AvailableRAM</td><td>2.02GB/ 6GB</td></tr><tr><td>AvailableHardisk</td><td>827.57GB/ 931.17GB</td></tr><tr><td>Version</td><td>2.8</td></tr><tr><td>TimeAlive</td><td>19h:59m:28s</td></tr><tr><td>OSVersion</td><td>Microsoft Windows 8.1 Pro </td></tr></table>"]}]})
00:33:17.4662864 - 4a0642d4-a131-445e-a877-27b11269bb5b - LP Poll: http://tsdemoserver.cloudapp.net/Signage/signalr/signalr/poll?clientProtocol=1.4&transport=longPolling&connectionData=[{"Name":"PlayerInfoHub"},{"Name":"RestartHub"}]&connectionToken=efDlldCJjDf7CzY%2Fc4wf8mVUveFZBZhSJdLhguQWohC6q4cF%2FJJmA2s2nmcgmq6vjlEeiDLr2GvmVFzs3oOkT8jtfLsrGCTravLG9NLbxB8w6kFu3Tdolhnhy1wV7ZIK&messageId=d-733D7334-B%2C2%7CC%2C0%7CD%2C0%7CE%2C0%7CF%2C3
00:33:17.4862881 - 4a0642d4-a131-445e-a877-27b11269bb5b - OnMessage({"I":"0"})

------------------------------------------------------------------------

When I disconnect ethernet port ...unfortunately nothing shows on the log.....i debug the code it says connected...
when i reconnect after sometime....still nothing on the logs but the client does not pass any information

**Comment by moozzyk** [comment] 2015-04-17 05:07
I think the problem is that even though you physically broke the connection the actual HTTP request was not terminated. As a result the client "thinks" it is still connected. Even when you replace the cable the server won't be able to respond to the request pending on the client and it will consider the client to be dead after a timeout. We tried fixing this by introducing keep alive messages to the longPolling transport but it created more problems that it solved (e.g. causing constant reconnects). The ultimate fix is to timeout poll requests from the client side if the server has not terminated the request within an expected period of time. We already implemented it in the JavaScript client (ae2bd7e5675c5028fa42594d0cd6edc01e666d42) but it was too late to fix it in the .NET Client at that time.

**Comment by hpanamgipalli** [comment] 2015-04-17 05:18
Thanks for the explanation. As i am using a desktop client (no javascript) - can you please elaborate on - "timeout poll requests from the client side if the server has not terminated the request within an expected period of time" 
Should i use a task running at continuous interval (say 30 mins) to ping the server IP and if failed then disconnect signalR using code and reconnect through code when ping was successful?

**Comment by moozzyk** [comment] 2015-04-17 06:03
To avoid issues where poll requests are being closed by third parties because they are open too long the server closes open poll requests if they are open for (if I remember correctly) 110 seconds (default, configurable on the server). In the javascript client we provide a timeout when sending the ajax request asking to terminate the request if it has not been closed in 110+10 seconds (again if I remember correctly). This way the JS client does not get hung because if the HTTP request hangs it will be terminated on the client side and the client will try to open a new request. This will should fail if the network cable is removed and the client should start reconnecting and will eventually disconnect if reconnecting fails. In case of C# client you could have a back up mechanism like you describe. You could potentially try to provide your own http client that terminates requests after a timeout (not sure how feasible this is) or you could try using a different transport (especially websockets) which should be more resilient to this kinds of problems thanks to keep alive messages.

**Comment by hpanamgipalli** [comment] 2015-04-17 06:13
Thank you

**Closed** 2015-04-17 06:49 UTC

**Comment by MKahmen** [comment] 2015-09-18 12:57
Hi moozzyk,

do you guys have any update regarding the "pull-the-cable-"problem? I did experience exactly the same...

BR
