### ISSUE TITLE
@microsoft/signalr client (nodejs) needs critical update to present status codes from the signalr server

### ISSUE THREAD

**Issue by knoxgon** [SignalR/SignalR#4669] opened 2023-03-20 14:47 UTC
We are currently using signalr hub server in C# .NET 7 and signalr client @microsoft/signalr in nodejs.

The problem we face today is that whenever there occurs a problem in the server side such as authentication issues or other issues where the authentication pipeline returns different codes such as 401 unauthorized or 400 bad request back the client, the client side does not get the reason of the failure. It only gets a long error which you formulate and present the us.

`Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.`

![image](https://user-images.githubusercontent.com/24989987/226369111-f6b449a3-91a2-46a1-8808-6589aa440f44.png)

This behaviour works flawless in the client version of signalr in C#. There we get the exact reason and the code.

`Response status code does not indicate success: 401 (Unauthorized).`

![image](https://user-images.githubusercontent.com/24989987/226375432-d07f3fcd-104d-45ce-a109-d0436fe42c63.png)

 However, the same behaviour is not present in the nodejs version (@microsoft/signalr). It only returns a string explaining that the connection failed. Not why it failed.

When I debug your code, I see that I actually have access to the reason of the error.

In the event object's property: `event.target._req.res`, I can see `statusCode` and `statusMessage` which were sent from the server.

![image](https://user-images.githubusercontent.com/24989987/226370048-f68f2c41-9915-4fd3-abc4-0143d43f5b18.png)

### Expected  behavior

@microsoft/signalr should also present the status codes and relevant data that are sent from the signalr server. Not just a long message explaning that the connection failed.

### Actual behavior

It should return the relevant parts of the response from the signalr server. Especially the status code and message. Currently, only a long error string is presented.

#### "@microsoft/signalr": "^7.0.3"

```js
import signalR from '@microsoft/signalr';

var connection = new signalR.HubConnectionBuilder()
      .withUrl(http://localhost:4444/signalrhub), {
        skipNegotiation: true,
        transport: signalR.HttpTransportType.WebSockets,
        accessTokenFactory: () => "<<<built_access_token>>>";
      })
      .withAutomaticReconnect()
      .build();

async function start() {
  try {
    await connection.start();
  } catch (err) {
    //Here, we do not get the relevant information... Only the long error string.
    console.log(err);
    setTimeout(start, 2000);
  }
};
start()

```

**Comment by BrennanConroy** [comment] 2023-03-20 15:42
Wrong repository. Also looks like a dupe of https://github.com/dotnet/aspnetcore/issues/39079

**Closed as completed by BrennanConroy** 2023-03-20 15:42 UTC

**Comment by knoxgon** [comment] 2023-03-20 16:27
@BrennanConroy Thank you, it looks awfully similar but it doesn't seem to have an answer for this problem. Although, it shouldn't be dependent on .NET releases. The solution should be to redirect the event object or pick the bits from the object and present it.
The only way to do it today is only by debugging the code.
Currently, we do not have extra resources to clone the repo and do the those specific steps and our product's release date is within 10 days.
