### ISSUE TITLE
websocket function cant run on linux

### ISSUE THREAD

**Issue by 564064202** [SignalR/SignalR#3934] opened 2017-05-11 00:01 UTC
websocket function cant run on linux,
does signalr surpport it?

**Comment by 564064202** [comment] 2017-05-11 03:30
we need transport='websocket'
does it support?

**Comment by moozzyk** [comment] 2017-05-11 06:27
This report is lacking details allowing to tell what the problem is. Closing. Feel free to reopen and provide more details including repro steps, stack traces etc.

**Closed by moozzyk** 2017-05-11 06:27 UTC

**Comment by 564064202** [comment] 2017-05-12 00:22
@moozzyk  you are impolite! do you know signalr cant run linux with websoket

**Comment by moozzyk** [comment] 2017-05-12 02:45
No, you have not filled the template and there is many questions that need to be answered before anyone can spend time on this. For instance: are you talking about server or the client? If this is the client, is it C# or the web client in the browser running on Linux? What version of SignalR are we talking about? Are you trying to use Mono or maybe you tried using AspNet Core version of SignalR or the deprecated port of 2.x? 
Note that SignalR 2.x server and C# client are not officially supported on Mono. Also, [this SO thread](http://stackoverflow.com/questions/30452890/signalr-and-websockets-on-mono) may directly be related to your problem.
