### ISSUE TITLE
JS Warning: Synchronous XMLHttpRequest on the main thread is deprecated

### ISSUE THREAD

**Issue by Jenan** [SignalR/SignalR#3922] opened 2017-05-03 08:14 UTC
Hello,

### Actual behavior

I've used the the `jquery v1.10.2` and `jquery.signalr-2.2.1.min.js` for connection to SignalR hub but I get following warning in chrome console:

`jquery-1.10.2.js:8686 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

**Complete console log:**

```
[10:20:22 GMT+0200 ] SignalR: Window unloading, stopping the connection.
jquery.signalr-2.2.1.min.js:9 

[10:20:22 GMT+0200 ] SignalR: Stopping connection.
jquery.signalr-2.2.1.min.js:9 

[10:20:22 GMT+0200 ] SignalR: Closing the Websocket.
:7700/Scripts/jquery-1.10.2.js:8686 

[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ :7700/Scripts/jquery-1.10.2.js:8686
ajax @ :7700/Scripts/jquery-1.10.2.js:8150
ajax @ ajax.aspnetcdn.com/ajax/signalr/jquery.signalr-2.2.1.min.js:9
ajaxAbort @ ajax.aspnetcdn.com/ajax/signalr/jquery.signalr-2.2.1.min.js:9
abort @ ajax.aspnetcdn.com/ajax/signalr/jquery.signalr-2.2.1.min.js:9
stop @ ajax.aspnetcdn.com/ajax/signalr/jquery.signalr-2.2.1.min.js:9
(anonymous) @ ajax.aspnetcdn.com/ajax/signalr/jquery.signalr-2.2.1.min.js:9
dispatch @ :7700/Scripts/jquery-1.10.2.js:5109
elemData.handle @ :7700/Scripts/jquery-1.10.2.js:4780
ajax.aspnetcdn.com/ajax/signalr/jquery.signalr-2.2.1.min.js:9 

[10:20:22 GMT+0200 ] SignalR: Fired ajax abort async = false.
ajax.aspnetcdn.com/ajax/signalr/jquery.signalr-2.2.1.min.js:9 

[10:20:22 GMT+0200 ] SignalR: Stopping the monitoring of the keep alive.
jquery.signalr-2.2.1.min.js:9 

[10:20:22 GMT+0200 ] SignalR: Client subscribed to hub 'chathub'.
jquery.signalr-2.2.1.min.js:9 

[10:20:22 GMT+0200 ] SignalR: Negotiating with 'http://localhost:7700/signalr/negotiate?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D'.
jquery.signalr-2.2.1.min.js:9 

[10:20:22 GMT+0200 ] SignalR: webSockets transport starting.
jquery.signalr-2.2.1.min.js:9 

[10:20:22 GMT+0200 ] SignalR: Connecting to websocket endpoint 'ws://localhost:7700/signalr/connect?transport=webSockets&clientProtocol=1.5&connectionToken=Iu%2BQ6Y9OhJoGSDi6J%2FoC0duclYpWcU1FtCvGj%2B9Jvg%2BYCW8MbyptAMV5E2MyApaYzucZjotsOQyIIzbAua9WfK4G59tZMn4j%2FNXdLAygbYvgvsUFWF6AhG6YoLiU3Oqy&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D&tid=8'.
jquery.signalr-2.2.1.min.js:9 

[10:20:22 GMT+0200 ] SignalR: Websocket opened.
jquery.signalr-2.2.1.min.js:9 

[10:20:22 GMT+0200 ] SignalR: webSockets transport connected. Initiating start request.
jquery.signalr-2.2.1.min.js:9 

[10:20:22 GMT+0200 ] SignalR: The start request succeeded. Transitioning to the connected state.
jquery.signalr-2.2.1.min.js:9 

[10:20:22 GMT+0200 ] SignalR: Now monitoring keep alive with a warning timeout of 13333.333333333332, keep alive timeout of 20000 and disconnecting timeout of 30000
jquery.signalr-2.2.1.min.js:9 

[10:20:22 GMT+0200 ] SignalR: Triggering client hub event 'SetConnectionId' on hub 'ChatHub'.
```

### Steps to reproduce
I've connected like this:

```
$(function () {

	var chat = $.connection.chatHub;

	chat.client.setConnectionId = function (connectionId) {
		console.log("ConnectionId: ", connectionId);
	};

	$.connection.hub.url = 'http://localhost:7700/signalr';
	$.connection.hub.logging = true;
	$.connection.hub.start().done(function () {

	});

});
```

How can I fix this warning?

Thank you

**Comment by garrettloy** [comment] 2017-05-05 23:16
duplicate of #3624

**Comment by nomorechickenstrips** [comment] 2017-06-03 16:33
I'm experiencing this as well.

**Comment by moozzyk** [comment] 2017-06-05 16:41
Dupe.

**Closed by moozzyk** 2017-06-05 16:41 UTC
