### ISSUE TITLE
Error: Failed to execute 'close' on 'WebSocket': The code must be either 1000, or between 3000 and 4999. 0 is neither.

### ISSUE THREAD

**Issue by AbeGeMS** [SignalR/SignalR#3712] opened 2016-06-12 08:34 UTC
```
private responseNotificationConnection: SignalR.Hub.Connection;

            if (this.responseNotificationConnection) {
                this.responseNotificationConnection.stop();
            }
```

Exception at calling "stop" method, 

The error detail are below

```
"stack" : "Error: Failed to execute 'close' on 'WebSocket': The code must be either 1000, or between 3000 and 4999. 0 is neither.
    at Error (native)
    at EventTarget.Object.create.close.value [as close] (<anonymous>:320:33)
    at Object.r.transports.webSockets.stop (https://forms.office.com/Scripts/Vendors/SignalR/jquery.signalR-2.2.0.min.js:8:24044)
    at Object.r.fn.r.stop (https://forms.office.com/Scripts/Vendors/SignalR/jquery.signalR-2.2.0.min.js:8:12923)
    at c.stop (https://forms.office.com/Scripts/OfficeForm/design-page.min.js?v=d50f115:4:10419)
    at e.componentWillUnmount (https://forms.office.com/Scripts/OfficeForm/design-page.min.js?v=d50f115:10:2739)
    at null.componentWillUnmount (https://forms.office.com/Scripts/OfficeForm/design-page.min.js?v=d50f115:2:3518)
    at y.unmountComponent (https://forms.office.com/Scripts/Vendors/react-0.14.6/react.min.js:13:11364)
    at Object.a.unmountComponent (https://forms.office.com/Scripts/Vendors/react-0.14.6/react.min.js:14:31752)
    at Object.s.updateChildren (https://forms.office.com/Scripts/Vendors/react-0.14.6/react.min.js:13:2900)"
```

**Comment by moozzyk** [comment] 2016-09-08 05:05
Is it easy to reproduce? What browser is it? It's interesting since SignalR [does not set the status code](https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.transports.webSockets.js#L147) when closing the webSocket when the connection is stopped.

**Comment by aspnet-hello** [comment] 2018-09-20 21:55
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Closed by aspnet-hello** 2018-09-20 21:55 UTC

**Comment by Gursewak-Uppal** [comment] 2022-01-13 12:44
Same error 

`Uncaught (in promise) DOMException: Failed to execute 'close' on 'WebSocket': The code must be either 1000, or between 3000 and 4999. 1001 is neither.`
