### ISSUE TITLE
HubConnection does not properly set the authorization header for every request. - Blazor WASM 2.0 Preview 2

### ISSUE THREAD

**Issue by MaxxDelusional** [SignalR/SignalR#4452] opened 2020-03-19 01:44 UTC
### Expected  behavior
I am using the latest preview of Blazor Web Assembly v3.2.0-preview2.20160.5, and SignalR Client v3.1.2

When using an `AcessTokenProvider`, the Authorization header should be set for every request made to the SignalR server, but my custom AuthenticationHandler is not recieving the header.

[According to the documentation](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.1), under Bearer Authentication, it says

> The access token function you provide is called before every HTTP request made by SignalR. 

```
hubConnection = new HubConnectionBuilder()
    .WithUrl("https://localhost:44344/hub"", options =>
     {
        options.AccessTokenProvider = async () =>
        {
            return Task.FromResult(token);
         };
     })
     .Build();

try
{
    await hubConnection.StartAsync();
}
catch (Exception ex)
{
   //Writes the Exception Message to the browser's console
    await Logger.Log(ex.Message);
}
```

### Actual behavior
I am noticing that some of the SignalR requests do not contain the Authorization header when the request is received by my AuthenticationHandler .

```
protected override async Task<AuthenticateResult> HandleAuthenticateAsync()
{
    if (Request.Headers.TryGetValue("Authorization", out StringValues headerValues))
    {
        //Header isn't present. This line does not get hit
    }
    else
    {
       //Without the header, authentication has to fail
        return AuthenticateResult.Fail("Missing Authorization header");
     }
}
```
The following Exception message is written to my browser's console.
 
```
WebSocket connection to 'wss://localhost:44344/hub?id=WZxtjbkdGegI7TZiy6yaOg' failed: HTTP Authentication failed; no valid credentials available
allocator @ dotnet.3.2.0-preview2.20159.2.js:1
```

The documentation also states that;

> In standard web APIs, bearer tokens are sent in an HTTP header. However, SignalR is unable to set these headers in browsers when using some transports. When using WebSockets and Server-Sent Events, the token is transmitted as a query string parameter. 

I checked, and the token is not being sent as a query parameter either.

During the initial hub connection, SignalR makes about 5 requests to my server. In all of the requests, only 1 of them is missing the Authorization header. The client eventually connects properly, and everything works, but an Exception is thrown during hubConnection.StartAsync, so the client thinks that the connection has failed.

At this point, I am not entirely sure if this is a SignalR issue, a Blazor WASM issue, or a ASP.Net issue.

**Comment by BrennanConroy** [comment] 2020-03-19 02:08
This is an issue with SignalR. The .NET client was initially written without any expectations of being run in a browser environment :P

Dupe of https://github.com/dotnet/aspnetcore/issues/18697

**Closed by BrennanConroy** 2020-03-19 02:08 UTC
