### ISSUE TITLE
signalr conflicts with pace.js and abort in the end

### ISSUE THREAD

**Issue by vikasNew** [SignalR/SignalR#4066] opened 2018-01-19 06:18 UTC
# Singnalr conflictes with pace.js when hub connection starts.

when i start the hub connection then i get the following issue in browser.

`$(function () {

    var chat = $.connection.notificationHub;
    // Create a function that the hub can call to broadcast messages.
    chat.client.broadcastMessage = function (message) {
        toastr.warning(message);
    };

    // Start the connection.
    $.connection.hub.start();
});
`

![screenshot_1](https://user-images.githubusercontent.com/19794408/35137182-04ec45ca-fd0e-11e7-8c5b-21f54ee4c7c5.png)

it looks like that this issue is because of conflicts with pace.js. although push notifications are working fine.

when i comment the below line then issue disappears. but signalr stops working.
`$.connection.hub.start();`

please help me to short out this.

**Comment by anurse** [comment] 2018-06-28 18:55
Duplicate of #4075

**Closed by anurse** 2018-06-28 18:55 UTC
