### ISSUE TITLE
Strange new message about multiple service endpoints

### ISSUE THREAD

**Issue by johnkwaters** [SignalR/SignalR#4335] opened 2019-03-13 02:24 UTC
Just noticed this in the log output, this is new:

 Microsoft.Azure.SignalR.ServiceEndpointManager[1]
      2 endpoints to https://northstardevsignalr.service.signalr.net found, use the one https://northstardevsignalr.service.signalr.net

Using Azure SignalR - what gives?

**Comment by halter73** [comment] 2019-03-13 18:16
@chenkennt ideas?

**Comment by chenkennt** [comment] 2019-03-14 03:31
Yes, we just changed the way how connection strings are read from configuration to support multiple instances. The most probable reason you see this is that you have two Azure_SignalR_ConnectionString in configuration (for example, one in env variable, one in app settings).

With this multiple instance support you'll be able to connect multiple SignalR instances together to handle more connections. Some docs can be found here:
https://github.com/Azure/azure-signalr/blob/dev/docs/sharding.md

/cc @vicancy

**Comment by johnkwaters** [comment] 2019-03-14 18:55
Hmm. So my code optionally uses either SignalR or AzureSignalR based on configuration:

`        /// <summary>
        /// Add AzureSignalR or embedded SignalR depending on options
        /// </summary>
        /// <param name="services">T</param>
        /// <param name="configuration"></param>
        /// <returns></returns>
        public static IServiceCollection AddAppropriateSignalR(
            this IServiceCollection services,
            IConfiguration configuration)
        {
            
            var soptions = new SignalROptions();
            configuration.Bind("Azure:SignalR", soptions);

            var useAzureSignalR = soptions.UseAzureSignalR;
            if (useAzureSignalR)
            {
                var signalRConnectionString = soptions.ConnectionString;
                services.AddSignalR().AddAzureSignalR(signalRConnectionString).AddJsonProtocol(
                    options =>
                    {
                        options.PayloadSerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                    });
            }
            else
            {
                services.AddSignalR().AddJsonProtocol(
                    options =>
                    {
                        options.PayloadSerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                    });
            }

            return services;
        }`

My appSettings.json might look like this:

`  "Azure": {
    "SignalR": {
      "UseAzureSignalR": true
    }
  },
`
And then this in user secrets or keyvault:

`"Azure:SignalR:ConnectionString": "Endpoint=https://northstardevsignalr.service.signalr.net;AccessKey=xxxx=;Version=1.0;",`

So it seems you see this connection string and use it... and additionally, since I configure this in code, you think I am adding it twice? But I am only adding it once. and there is only one connection string... bug?

**Comment by johnkwaters** [comment] 2019-03-14 22:26
I have narrowed it down further. I only have one connection string (if I change it's name, AddAzureSignalR throws the appropriate exception for a missing connection string).
But: I do AddSignalR when configuring DI:

`                services.AddSignalR().AddAzureSignalR().AddJsonProtocol(
                    options =>
                    {
                        options.PayloadSerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                    });
`
And later, UseSignalR when configuring the HTTP pipeline:

`app.UseAzureSignalR(routes => { routes.MapHub<StopsHub>("/stops"); });`

This is when I get that warning.

Should one no longer do Add and Use like this?

**Comment by vicancy** [comment] 2019-03-18 06:37
Hi @johnkwaters Thanks for reporting this, we will fix it. Created https://github.com/Azure/azure-signalr/issues/439 to track it.

**Comment by anurse** [comment] 2019-04-17 02:38
Closing this as the issue is in the Azure SignalR Service SDK. See the linked issue for more details on the progress!

**Closed by anurse** 2019-04-17 02:38 UTC
