### ISSUE TITLE
Random cors error in 2.1.1

### ISSUE THREAD

**Issue by peters** [SignalR/SignalR#3213] opened 2014-08-13 13:46 UTC
Hi,

There is something strange happening to our javascript client based signalr connections where some requests suddenly does not have a **CORS** header present. The client connects successfully but and after a couple of minutes it gets disconnected with the following error: "No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.odinoffice.no' is therefore not allowed access."

Signalr is configured with **CorsOption.AllowAll**. We are using **redis** as our backplane in Azure. Also api.odinoffice.no is also load balanced using azure traffic manager.

Reconnecting the client immediately resolves the problem :(

Version: 2.1.1

Console output

```
[15:40:00 GMT+0200 (W. Europe Daylight Time)] SignalR: Invoked yggdrasilhub.GetApplicationsConnected
XMLHttpRequest cannot load https://api.odinoffice.no/signalr/start?transport=webSockets&clientProtocol…connectionData=%5B%7B%22name%22%3A%22yggdrasilhub%22%7D%5D&_=1407937168230. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.odinoffice.no' is therefore not allowed access. www.odinoffice.no/yggdrasil/overview/52d6790c36678e09f8729192:1
signalr error 
Error
[15:40:01 GMT+0200 (W. Europe Daylight Time)] SignalR: Stopping connection.
[15:40:01 GMT+0200 (W. Europe Daylight Time)] SignalR: EventSource calling close().
[15:40:01 GMT+0200 (W. Europe Daylight Time)] SignalR: Fired ajax abort async = true.
[15:40:01 GMT+0200 (W. Europe Daylight Time)] SignalR: Stopping the monitoring of the keep alive.
disconnected from yggdrasilHub, attempting to reconnect.
[15:40:06 GMT+0200 (W. Europe Daylight Time)] SignalR: Auto detected cross domain url.
[15:40:06 GMT+0200 (W. Europe Daylight Time)] SignalR: Client subscribed to hub 'yggdrasilhub'.
[15:40:06 GMT+0200 (W. Europe Daylight Time)] SignalR: Negotiating with 'https://api.odinoffice.no/signalr/negotiate?clientProtocol=1.4&organization…57imt7yk1WggriB&connectionData=%5B%7B%22name%22%3A%22yggdrasilhub%22%7D%5D'.
[15:40:06 GMT+0200 (W. Europe Daylight Time)] SignalR: Connecting to websocket endpoint 'wss://api.odinoffice.no/signalr/connect?transport=webSockets&clientProtocol…ldsBNVJtN&connectionData=%5B%7B%22name%22%3A%22yggdrasilhub%22%7D%5D&tid=7'.
[15:40:06 GMT+0200 (W. Europe Daylight Time)] SignalR: Websocket opened.
[15:40:06 GMT+0200 (W. Europe Daylight Time)] SignalR: Now monitoring keep alive with a warning timeout of 13333.333333333332 and a connection lost timeout of 20000.
signalr connection id is now:  c4417b5f-fc36-42a6-baec-25e51a70cf21
[15:40:07 GMT+0200 (W. Europe Daylight Time)] SignalR: Invoking yggdrasilhub.GetApplicationsConnected
[15:40:07 GMT+0200 (W. Europe Daylight Time)] SignalR: Invoked yggdrasilhub.GetApplicationsConnected
```

**Comment by Shahrooze** [comment] 2016-01-31 06:38
I have same problem.
When my signalr app is ok it returns these heasers:

Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:https://x.com
Content-Type:application/json; charset=UTF-8
Date:Sun, 31 Jan 2016 06:28:27 GMT
Server:Microsoft-HTTPAPI/2.0
Transfer-Encoding:chunked
X-Content-Type-Options:nosniff

but when the app is broken does not returns  Access-Control-Allow-Origin and Access-Control-Allow-Credentials.
and just returns 
Content-Length:0
Date:Sun, 31 Jan 2016 06:28:26 GMT
Server:Microsoft-HTTPAPI/2.0


I use self host.

**Comment by Shahrooze** [comment] 2016-01-31 07:24
I know the problem is not related for cors.I write a new console application and try to connect the signal r app but again I get the error but 500 and not cors:

`InnerException = {"StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:\r\n{\r\n  Date: Sun, 31 Jan 2016 07:10:06 GMT\r\n  Server: Microsoft-HTTPAPI/2.0\r\n  Content-Length: 0\r\n}"}
`

**Comment by matthewma** [comment] 2016-03-03 15:08
I think it is not related to CORS too. My case seems related to Ninject, which cause some 500 before CORS kicks in. Didn't find a solution yet.

**Comment by raybooysen** [comment] 2017-01-04 16:00
This has just started happening to me today.  First request to an endpoint works, second fails (both different hosts).  Exactly the same as @Shahrooze's outpu

**Comment by aspnet-hello** [comment] 2018-09-20 22:46
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Closed by aspnet-hello** 2018-09-20 22:46 UTC
Labels: needs repro
