### ISSUE TITLE
$.connection.hub.start() request /null

### ISSUE THREAD

**Issue by suifengshiqu** [SignalR/SignalR#3918] opened 2017-04-26 02:38 UTC
v2.2.1
### Expected  behavior
$.connection.hub.start().done(function () {
        connectionId = $.connection.hub.id;
    }).fail(function () {
    });
it will send a request which the url is /null，who can help me resolve it?

Request URL:http://localhost:18198/null
Request Method:GET
Status Code:404 Not Found
Remote Address:[::1]:18198
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Cache-Control:private
Content-Length:3083
Content-Type:text/html; charset=utf-8
Date:Wed, 26 Apr 2017 02:31:47 GMT
Server:Microsoft-IIS/10.0
X-AspNet-Version:4.0.30319
X-Powered-By:ASP.NET
X-SourceFiles:=?UTF-8?B?Rjpc5YWs5Y+46aG555uuXGNlcnAtZGV2...
Request Headers
view source
Accept:image/webp,image/apng,image/*,*/*;q=0.8
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-CN,zh;q=0.8
Connection:keep-alive
Cookie:
Host:localhost:18198
Referer:http://localhost:18198/Main
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3063.4 Safari/537.36

**Comment by moozzyk** [comment] 2017-04-26 16:06
Please provide a full repro - server and client code. There isn't enough details in your report to investigate.

**Comment by suifengshiqu** [comment] 2017-04-27 01:03
this is code in hub.cs 
~~~cs
/// <summary>
        /// Called when [connected].
        /// </summary>
        /// <returns>Task.</returns>
        public override Task OnConnected()
        {
            string connectionId = Context.ConnectionId;
            var user = SignalRConfig.Connections.GetOrAdd(LoginUserId, _ => new SignalRConnection
            {
                UserId = LoginUserId,
                ConnectionIds = new HashSet<string>()
            });
            lock (user.ConnectionIds)
            {
                user.ConnectionIds.Add(connectionId);
            }
            GetOnlineUserTree();
            GetAllUserTree();
            if (user.ConnectionIds.Count == 1)//第一次上线发送提醒
            {
                Clients.All.updateOnline(LoginUserId, true);
            }
            return base.OnConnected();
        }

        /// <summary>
        /// Called when [disconnected].
        /// </summary>
        /// <param name="stopCalled">if set to <c>true</c> [stop called].</param>
        /// <returns>Task.</returns>
        public override Task OnDisconnected(bool stopCalled)
        {
            try
            {
                string connectionId = Context.ConnectionId;
                var user = SignalRConfig.Connections.FirstOrDefault(x => x.Value.ConnectionIds.Contains(Context.ConnectionId)).Value;
                lock (user.ConnectionIds)
                {
                    user.ConnectionIds.Remove(connectionId);
                }
                if (user.ConnectionIds.Count == 0 && user.DeviceIds.Count == 0)
                {
                    if (SignalRConfig.Connections.TryRemove(user.UserId, out user))
                    {
                        GetOnlineUserTree();
                        Clients.All.updateOnline(user.UserId, false);
                    }
                }
            }
            catch (Exception ex)
            {
                File.AppendAllLines("D:\\cerpLog.txt", new string[] { ex.Message });
            }
            return base.OnDisconnected(stopCalled);
        }
        /// <summary>
        /// Called when [reconnected].
        /// </summary>
        /// <returns>Task.</returns>
        public override Task OnReconnected()
        {
            string connectionId = Context.ConnectionId;

            var user = SignalRConfig.Connections.GetOrAdd(LoginUserId, _ => new SignalRConnection
            {
                UserId = LoginUserId,
                ConnectionIds = new HashSet<string>()
            });
            lock (user.ConnectionIds)
            {
                if (!user.ConnectionIds.Contains(connectionId))
                    user.ConnectionIds.Add(connectionId);
            }
            GetOnlineUserTree();
            GetAllUserTree();//(需要修改为只更新用户状态不重新获取)
            if (user.ConnectionIds.Count == 1)//第一次上线发送提醒
            {
                Clients.All.updateOnline(LoginUserId, true);
            }
            return base.OnReconnected();
        }
~~~
the client js
~~~js
//申明一个signalr集线器的代理（名称一定要以小写字母开头）
var sysChat = $.connection.sysChatHub;
$(function () {
    //系统连接成功
    $.connection.hub.start().done(function () {
        //console.log("第一次连接Id:" + $.connection.hub.id);
        $("#txtContant").on("keyup", function () {
            searchUser();
        })
        $("#btnSearchUser").on("click", function () {
            searchUser();
        })
        $("#testtt").on("click", function () {
            sysChat.server.pushMsg();
        })
        connectionId = $.connection.hub.id;
    }).fail(function () {
        //console.log("已离线，正在重新连接服务器！");
    });
    isReconnected = false;
    //重新连接服务端（与服务端断开的第一时间触发）
    $.connection.hub.reconnecting(function () {
        if (!isReconnected) {
            //离线后的事件处理
            $(".chat-send").removeAttr("disabled").attr("title", "已与服务器断开连接，无法发送消息！");
        }
        //console.log("正在重新连接");
    });
    //重新连接成功时触发
    $.connection.hub.reconnected(function () {
        //console.log("重新连接后的Id:"+$.connection.hub.id);
        $(".chat-send").attr("disabled", true).attr("title", "点击发送");
        isReconnected = false;
        //console.log("已重新连接");
    });
     //与服务端断开连接（在reconnecting事件执行失败后触发，在这里定时重新创建连接）
    $.connection.hub.disconnected(function () {
        //console.log("已离线")
        connectInterval = setInterval(function () {
            $.connection.hub.start().done(function () {
                //console.log("第一次连接Id:" + $.connection.hub.id);
                $("#txtContant").on("keyup", function () {
                    searchUser();
                })
                $("#btnSearchUser").on("click", function () {
                    searchUser();
                })
                $("#testtt").on("click", function () {
                    sysChat.server.pushMsg();
                })
                if (connectInterval) {
                    clearInterval(connectInterval);
                }
                if (connectionId != $.connection.hub.id)
                    sysChat.server.removeConnection(connectionId)
                connectionId = $.connection.hub.id;
            }).fail(function () {
                if (connectInterval) {
                    clearInterval(connectInterval);
                }
                //console.log("已离线，正在重新连接服务器！");
            });
        }, 5000)
    });
});
~~~
when i have comment out the code in  **$.connection.hub.start().done(function () {})** the problem is remain

**Comment by moozzyk** [comment] 2017-04-27 17:18
Can you provide something that can be run? You showed a bunch of code but I would have to add more code to be able to run it and if I couldn't repro the issue I wouldn't know if the issue is with the code that you did not show. So, ideally the repro you provide is minimal repro and it is a github repo which I can just clone and run.
One more thought - are you running this with IIS, IISExpress or selfhost? If IIS/IISExpress - can you run it as selfhost and see if it fails the same way? This would remove one more variable from the equation.

**Comment by aspnet-hello** [comment] 2018-09-20 21:51
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Closed by aspnet-hello** 2018-09-20 21:51 UTC
