### ISSUE TITLE
All websocket connections are reconnected unexpectedly

### ISSUE THREAD

**Issue by vikas-idealconcepts** [SignalR/SignalR#4261] opened 2018-11-06 16:41 UTC
We have a asp.net website developed in .net 4.7.2 and signalr and is deployed in IIS. This website makes websocket connections using signalr from client browser (99% clients are using Chrome) to IIS. We generally have 200-300 clients working on this app on their browser at a time. Each client works for hours on our web application. So far, we never had any issue with these long lasting web socket connections for last several years. Starting last month, we have started to face a very strange issue on production server. Production server works for hours without any issue and then suddenly all 200-300 websocket connections disappear in IIS worker process. Then within 500ms-2s, new connections appear (with 'reconnect' in URL) in IIS web worker process for all clients and then in 1-3 seconds all websocket connections disappear again. This disappear-reappear cycle continues until I reset IIS. Once I reset IIS, this issue goes away and new websocket connections stay. Issue also goes away if I wait for 20-30 minutes. This issue is happening 1-3 times a day. Always happens in day time on week days when we have maximum traffic. Please note that other non-websocket connections in same  worker process are not effected at all.

### Expected  behavior
All websocket connections should not disappear and reappear for  no apparent reason.

### Actual behavior
All websocket connections disappear and reappear continuously for 20-30 minutes.

### Steps to reproduce
Not sure if this is reproducible in test environment or not. We have 200-300 websocket connections and connections are long lasting (like 1-5 hours). This happens all of a sudden for no apparent reason.

**Comment by anurse** [comment] 2018-11-06 16:47
Do you have any errors on the client that correlate with this? There are a lot of things that can cause connections to be disrupted. If all your connections are terminating, it sounds like something on your server could be terminating them. What do your server resources look like when this occurs? Are there CPU or Memory spikes? I suggest enabling some of the [server-side tracing](https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing#server) options in SignalR.

**Comment by vikas-idealconcepts** [comment] 2018-11-06 16:52
As you mention, all web socket connections disappear at the same time so I am assuming this is something on server side. There is no change in CPU, memory, internet traffic etc when this issue occurs. We have changed our internet line to new provider but did not help. We captured wireshark when this issue is going on but we could not find anything special in it. We enabled signalr tracing already and have those logs.

**Comment by anurse** [comment] 2018-11-06 17:13
Is there anything useful in the WebSocketTransport log? If SignalR is the one terminating the connection, I'd expect to see an error or disconnect log there. More likely it seems like something in IIS might be terminating the connections (perhaps due to a connection limit being exhausted).

> Starting last month, we have started to face a very strange issue on production server.

Do you have any idea what you might have changed in that time? Did you change versions of ASP.NET SignalR? Redeploy the app? Install Windows Update patches on your servers?

**Comment by anurse** [comment] 2018-11-06 19:05
> I prepared a new web server with .net 4.5.2 and degraded application to .net 4.5.2/signalr 2.2 and installed application on this new web server.

So you downgraded back to your previous code and nothing changed? That's odd since it seems like this was brought on by a specific event, given that it was working a month ago. Has your traffic load changed? Does the number of TCP connections to your server spike around the time that the disconnects occur?

> Also want to add that restarting website in IIS also makes this issue to go away immediately but recycling application pool DOES NOT help.

So let me restate things so I can make sure I understand the situation :)

1. When your WebSocket traffic is high, you see all your WebSocket connections get immediately terminated.
1. At this point, the clients all reconnect, but fail a few seconds later.
1. Clients continue to reconnect in a loop.
1. Recycling the app pool **does not** stop this looping.
1. Fully restarting IIS **does** stop this looping and connections begin behaving correctly again.
1. Waiting 20-30mins **without** restarting anything **also** restores normal functionality

The fact that either waiting or fully restarting IIS restores the connections indicates to me that some resource in IIS itself might be being exhausted (Sockets, Concurrent Request Limit, etc.). @shirhatti, @davidfowl does this behavior look like anything you've seen before with IIS and/or SignalR?

The loop of reconnecting, disconnecting, reconnecting again is not uncommon (sometimes called a "reconnect storm") because you have a lot of connections attempting to reconnect simultaneously. @halter73, @davidfowl I know you've mentioned this before, is this something that can be mitigated?

**Comment by anurse** [comment] 2018-11-06 19:07
> Please note that other non-websocket connections in same worker process are not effected at all.

By this, do you mean HTTP connections? HTTP connections are generally short-lived (often less than a few seconds) so if they are similarly disconnecting after a few seconds, you wouldn't see a problem since the response would be sent out in time. What you would see is that your clients would keep having to re-establish new connections since they can't reuse existing ones (since they are being terminated).

**Comment by vikas-idealconcepts** [comment] 2018-11-07 13:59
I have following in my web.config. Is this enough to catch any potential issue?

  ```
<system.diagnostics>
    <sources>
      <source name="SignalR.SqlMessageBus">
        <listeners>
          <add name="SignalR-Bus" />
        </listeners>
      </source>
     <source name="SignalR.ServiceBusMessageBus">
        <listeners>
            <add name="SignalR-Bus" />
        </listeners>
     </source>
      <source name="SignalR.RedisMessageBus">
        <listeners>
          <add name="SignalR-Bus" />
        </listeners>
      </source>
     <source name="SignalR.ScaleoutMessageBus">
        <listeners>
            <add name="SignalR-Bus" />
        </listeners>
      </source>
      <source name="SignalR.Transports.WebSocketTransport">
        <listeners>
          <add name="SignalR-Transports" />
        </listeners>
      </source>
      <source name="SignalR.Transports.ServerSentEventsTransport">
          <listeners>
              <add name="SignalR-Transports" />
          </listeners>
      </source>
      <source name="SignalR.Transports.ForeverFrameTransport">
          <listeners>
              <add name="SignalR-Transports" />
          </listeners>
      </source>
      <source name="SignalR.Transports.LongPollingTransport">
        <listeners>
            <add name="SignalR-Transports" />
        </listeners>
      </source>
      <source name="SignalR.Transports.TransportHeartBeat">
        <listeners>
            <add name="SignalR-Transports" />
        </listeners>
      </source>
      <source name="SignalR.ReflectedHubDescriptorProvider">
        <listeners>
          <add name="SignalR-Init" />
        </listeners>
      </source>
    </sources>
    <!-- Sets the trace verbosity level -->
    <switches>
      <add name="SignalRSwitch" value="Verbose" />
    </switches>
    <!-- Specifies the trace writer for output -->
    <sharedListeners>
      <!-- Listener for transport events -->
      <add name="SignalR-Transports" type="System.Diagnostics.TextWriterTraceListener" initializeData="C:\SignalR\transports.log.txt" />
      <!-- Listener for scaleout provider events -->
      <add name="SignalR-Bus" type="System.Diagnostics.TextWriterTraceListener" initializeData="C:\SignalR\bus.log.txt" />
		   <!-- Listener for hub discovery events -->
      <add name="SignalR-Init" type="System.Diagnostics.TextWriterTraceListener" initializeData="C:\SignalR\init.log.txt" />
   </sharedListeners>
    <trace autoflush="true" />
  </system.diagnostics>
```

**Comment by anurse** [comment] 2018-11-07 17:39
The `SignalR.Transports.WebSocketTransport` trace source is where I'd expect to see an error if SignalR is the one terminating the connection. So yes, that should be sufficient tracing. If you aren't seeing an error there, it would indicate something else is terminating the connection outside of SignalR.

**Comment by vikas-idealconcepts** [comment] 2018-11-07 20:09
To rule out Firefox, I blocked Firefox today. It just happened again. 
Can you I send you today's traces to analyse?. I can upload logs on dropbox and send you a dropbox link to your email.

**Comment by vikas-idealconcepts** [comment] 2018-11-07 22:19
I notice this line in log
SignalR.Transports.TransportHeartBeat Information: 0 : Dispose(). Closing all connections
Does it mean that all connections are being closed by Signalr for some reason?

**Comment by anurse** [comment] 2018-11-07 23:10
Yes, TransportHeartBeat Dispose will terminate all connections. Is this log occurring at the time that all the connections dispose? You can add the `Timestamp` option to the `traceOutputOptions` in your web.config. See the [docs on TraceOptions](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.traceoptions?view=netframework-4.7.2#remarks) for more info.

The Dispose method on TransportHeartBeat is called when the App Pool is being recycled, specifically to shutdown existing SignalR connections.

**Comment by vikas-idealconcepts** [comment] 2018-11-08 15:58
I have added timestamp option in web.config. Next time this issue occurs, I will be able to tell if above 'dispose' log entry happens right before the issue or not.

**Comment by vikas-idealconcepts** [comment] 2018-11-08 23:44
It is now confirmed that following log entry occurs right before our issue starts and this log entry keeps on appearing until I reset IIS.
SignalR.Transports.TransportHeartBeat Information: 0 : Dispose(). Closing all connections

Any clues what may cause above code to be executed?

**Comment by vikas-idealconcepts** [comment] 2018-11-09 13:50
I am running out of ideas now. Need suggestions to make progress to further diagnose this issue. Will it help if I add few lines of code in Signalr code in dispose method of TransportHeartBeat to log stack trace?This way we will know which code is causing this dispose to execute.

**Comment by anurse** [comment] 2018-11-09 17:38
You can include the Stacktrace just like the Timestamp: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.traceoptions?view=netframework-4.7.2

**Comment by vikas-idealconcepts** [comment] 2018-11-09 18:17
Good pointer. I will add Stacktrace option in config tonight.
Any other log (like app domain traces) which I can enable to get more insights?

**Comment by vikas-idealconcepts** [comment] 2018-11-21 21:51
We are still facing this issue continuously. 
Today we added added Health Monitoring in asp.net application and when this issue occurred today, events similar to following were logged in event viewer every few second until I restarted the website.

Event code: 1002 
Event message: Application is shutting down. Reason: Configuration changed. 
Event time: 11/21/2018 4:33:14 PM 
Event time (UTC): 11/21/2018 9:33:14 PM 
Event ID: d22b5cceb78648a88c2e21e04ce5ca1e 
Event sequence: 193 
Event occurrence: 1 
Event detail code: 50004 
 
Application information: 
    Application domain: /LM/W3SVC/9/ROOT-48-131873095908090891 
    Trust level: Full 
    Application Virtual Path: / 
    Application Path: c:\inetpub\wwwroot\SalesRadix\ 
    Machine name: WEB080518 
 
Process information: 
    Process ID: 7788 
    Process name: w3wp.exe 
    Account name: IDCPROD\salesradixvd 
 
Custom event details:

**Comment by anurse** [comment] 2018-11-21 23:46
That event is usually fired when `web.config` is changed (or any of the other IIS configuration options). Is it possible something in your application or deployment environment is doing this?

**Comment by vikas-idealconcepts** [comment] 2018-11-23 15:52
web.config file timestamp is not changing.
I looked for any new file/folder or modified file/folder in entire application folder but found nothing.

**Comment by vikas-idealconcepts** [comment] 2018-11-27 17:45
I added following in web.config and issue has not re-occurred in last more than 24 hours.
`<httpRuntime fcnMode="Disabled"/>`

**Comment by anurse** [comment] 2018-11-27 22:39
That certainly indicates that something was triggering a file change notification. If the file isn't being touched during that time, it seems odd that a file change notification would be triggered, but if one was being triggered that would definitely cause the app to keep restarting and SignalR to reconnect all the sockets.

**Comment by vikas-idealconcepts** [comment] 2018-11-27 22:45
There is a virtual directory under website which points to a shared location in network. This shared location has static files only (like images) but files are being added continuously in that location. We have this configuration for last several years and never had any issue. Next I am going to remove that virtual directory from website to see if this issue occurs or not.

**Comment by idealconcepts** [comment] 2019-01-08 14:06
This is now confirmed that issue was happening because entire website was getting restarted. This is not signalr issue.

**Comment by anurse** [comment] 2019-01-08 18:11
Thanks for the update. I'll close this issue then.

**Closed by anurse** 2019-01-08 18:11 UTC
