### ISSUE TITLE
Self-Hosted SignalR 2.2: An operation was attempted on a nonexistent network connection

### ISSUE THREAD

**Issue by digital11** [SignalR/SignalR#3397] opened 2015-01-27 17:24 UTC
Environment:
- SignalR 2.2 OWIN Self-Hosted in a Windows service on Server 2012
- Redis ScaleOut Backplane

We are seeing lots of these exceptions caught by our TaskScheduler_UnobservedTaskException handler:

```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Net.HttpListenerException: An operation was attempted on a nonexistent network connection
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteAsyncFast(HttpListenerAsyncEventArgs eventArgs)
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.<WriteAsyncCore>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<SendFrameAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<CloseOutputAsyncCore>d__17.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.HttpListenerException (0x80004005): An operation was attempted on a nonexistent network connection
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteAsyncFast(HttpListenerAsyncEventArgs eventArgs)
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.<WriteAsyncCore>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<SendFrameAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<CloseOutputAsyncCore>d__17.MoveNext()<---
```

**Comment by AdamCaviness** [comment] 2015-01-30 19:06
We also get this on SignalR 2.2 OWIN Self-Hosted in Windows service on Server 2008 R2 with ServerSentEvents transport.  I have not seen this with WebSockets transport.  Based on https://github.com/SignalR/SignalR/issues/2788 and http://forums.asp.net/t/1940397.aspx?How+do+you+stop+restart+self+hosted+SignalR+properly, I presume at some point it will be swallowed.

**Comment by niemyjski** [comment] 2015-02-13 20:54
We are using WebSocked and Redis and we are also seeing this behavior...

**Comment by niemyjski** [comment] 2015-02-13 20:55
5,617 TOTAL so far 

		System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
		 ---> System.NullReferenceException: Object reference not set to an instance of an object.
		at System.Web.ThreadContext.AssociateWithCurrentThread
		at System.Web.HttpApplication.OnThreadEnterPrivate
		at System.Web.HttpApplication.System.Web.Util.ISyncContext.Enter
		at System.Web.Util.SynchronizationHelper.SafeWrapCallback
		at System.Threading.Tasks.Task.Execute
		--- End of inner exception stack trace ---

**Comment by DamianEdwards** [comment] 2015-02-13 22:09
@niemyjski @digital11 can you provide some more details around the history of the app? Was it working OK and then you upgraded to 2.2 or added Redis scale-out?

You both have different stacks and different hosting stories (one is self-host, the other is System.Web) so it's not yet clear if these are related.

**Comment by DamianEdwards** [comment] 2015-02-13 22:12
@niemyjski do you by any chance have any async/await methods that are void returning? Can you share a repro application? That error indicates that you have an async callback that "escaped" the ASP.NET request context, which is bad. It's often caused by bad async code in the app, but it is possible we introduced this in the 2.2.0 Redis scale-out provider, but we could really do with more details and/or troubleshooting from your end to get to narrow it down.

**Comment by niemyjski** [comment] 2015-02-13 22:13
Yes, was working before and then we upgraded and started using redis scale out:
Commit when this was added:
https://github.com/exceptionless/Exceptionless/commit/3152a9f7d25f0f8cbf29cfd29981d6fb27999531

Repo can be found here: https://github.com/exceptionless/Exceptionless Requires a little bit of setup but I can enter a meeting with you and help you get it setup.

**Comment by niemyjski** [comment] 2015-02-13 22:14
I've been keeping an eye out for this and turned on stop on all null reference exceptions today.. Seems to happen more when I'm really pushing notifications.

**Comment by niemyjski** [comment] 2015-02-13 22:15
![image](https://cloud.githubusercontent.com/assets/1020579/6196167/80ccf0d2-b39b-11e4-9d7d-8de3853dc678.png)

**Comment by niemyjski** [comment] 2015-02-13 22:16
I noticed that it's usually associated with this error (WebSocket connection to 'wss://api-preview.exceptionless.com/api/v2/push/connect?transport=webSocket…WNT03w%3D%3D&connectionData=%5B%7B%22name%22%3A%22messages%22%7D%5D&tid=10' failed: WebSocket opening handshake was canceled).. I started seeing this when I started getting this exception.

**Comment by EnCey** [comment] 2015-05-21 08:08
We are also getting a lot of `TaskScheduler_UnobservedTaskException`, SignalR 2.2 OWIN Self-Hosted but no Redis Backplane. We only use WebSocket Transport mode, no long polling or other modes. 

```
AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
HttpListenerException: An operation was attempted on a nonexistent network connection
at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteAsyncFast(HttpListenerAsyncEventArgs eventArgs)
at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.<WriteAsyncCore>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Net.WebSockets.WebSocketBase.<SendFrameAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Net.WebSockets.WebSocketBase.<CloseOutputAsyncCore>d__17.MoveNext()
```

**Comment by aspnet-hello** [comment] 2018-09-20 22:09
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Closed by aspnet-hello** 2018-09-20 22:09 UTC
