### ISSUE TITLE
Ondisconnect not being called immediately when navigating to another page within project (but is when navigating to another website or closing tab)

### ISSUE THREAD

**Issue by westcode** [SignalR/SignalR#2719] opened 2013-11-20 10:45 UTC
Hi,

After we upgraded our project to SignalR v2 the behaviour of ondisconnect seems changed. 
When navigating away to another website e.g. google.com, the ondisconnect is called immediately (same goes when closing the tab its running in). But when we navigate to another page in our webproject, the ondisconnect is called much later, supposedly after the timeout runs out. We have validated this behaviour by creating a fresh MVC4 project  and the chatHub example to exclude user error on our behalf (tested with google chrome).
Our application heavily relies on the ondisconnect being fired when users navigate away from the page (for user cleanup i.e. leaving chatroom).

Could you tell me if this is by design and what options we have to make ondisconnect fire immediately when a user navigates to another page (same as closing a tab)? We have not changed the default timeout/keepalive settings. Added we would like not to have to rely on a method like beforeunload to make this work as it has previously.

Much thanks in advance!

**Comment by firephantomassasin** [comment] 2021-01-21 14:42
It looks like this issue is happening again, and 

using this workaround resolve the issue in chrome Version 87.0.4280.141 (Official Build) (64-bit)

window.onbeforeunload = function (e) {
    $.connection.hub.stop();
};

**Comment by BrennanConroy** [comment] 2021-02-18 22:04
Dupe of https://github.com/SignalR/SignalR/issues/4365

**Closed by BrennanConroy** 2021-02-18 22:04 UTC
Labels: type: Bug
