### ISSUE TITLE
SignalR.Client 2.2.0 not compatible with Xamarin PCL

### ISSUE THREAD

**Issue by WillemMali** [SignalR/SignalR#3675] opened 2016-04-06 12:09 UTC
Hi,

I'm trying to use the Microsoft.AspNet.SignalR.Client library in a Xamarin PCL and have succeeded in using version 2.1.2, however, when I try to install the newest version on NuGet (2.2.0) I get the following error:

`Could not install package 'Microsoft.AspNet.SignalR.Client 2.2.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
`

I'm assuming this is a regression and not an intentional choice to drop support for this profile between 2.1.2 and 2.2.0.

I have also tried using the latest Microsoft.AspNet.SignalR.Client.Portable (2.0.1) because it's supposed to have slimmer dependencies, however trying to install this I get a similar error, except it's from one of the package's dependencies:

`Could not install package 'Microsoft.Net.Http 2.2.18'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
`

Which is ironic, I guess. It'd be nice if this package "just worked" and was up-to-date.

If there's anything I can do to help I'd be glad to! I have a fair amount of experience with C# and and a bit of experience with the nitty-gritty of assemblies and PCL's but I won't be much help on the NuGet-packaging side.

P.S.: For good measure I tried some other up-to-date SignalR packages on my PCL, I couldn't install any of these:
* Microsoft.AspNet.SignalR 2.2.0
* Microsoft.AspNet.SignalR.Core 2.2.0
* Microsoft.AspNet.SignalR.SystemWeb 2.2.0
* Microsoft.AspNet.SignalR.Owin 1.2.2
* Microsoft.AspNet.SignalR.SelfHost 2.2.0
* Microsoft.AspNet.SignalR.Client.Portable 2.0.1

I could install:
* Microsoft.AspNet.SignalR.JS 2.2.0
* Microsoft.AspNet.SignalR.Client 2.1.2

### Repro steps:
1. Make a new Blank App (Xamarin.Forms Portable)
2. Try to install Microsoft.AspNet.SignalR.Client 2.2.0
3. Error!
4. Try to install Microsoft.AspNet.SignalR.Client.Portable
5. Error!
6. Try to install Microsoft.AspNet.SignalR.Client 2.1.2
7. Success!

I have a Xamarin Business license but you shouldn't need it. I don't have the time to set up a VM with VS 2015 CE & Xamarin right now, if you'd really need me to I could find the time in ~4 work days.

### Project info:
.NET Framework 4.5
ASP.NET Core 5.0
Xamarin Android
Xamarin Business license

### Environment info:

Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual C# 2015   00322-20000-00000-AA384
Microsoft Visual C# 2015

NuGet Package Manager   3.4.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Xamarin   4.0.3.214 (0dd817c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.0.3.5 (a94a03b)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   9.6.1.8 (3a25bf1)
Visual Studio extension to enable development for Xamarin.iOS.

**Comment by kjeremy** [comment] 2016-05-04 19:33
I'm seeing this too.  It says it's not compatible with PCL profile 259.

**Comment by artfuldev** [comment] 2016-06-15 08:45
Actually, we can't get it to install in Xamarin.Android and Xamarin.iOS projects either. We get this error: 

> Could not install package 'Microsoft.Bcl.Build 1.0.14'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by moozzyk** [comment] 2016-06-15 16:58
Can you try 2.2.1 from the nightly build (https://github.com/SignalR/SignalR/issues/3393#issuecomment-173964492)

**Comment by artfuldev** [comment] 2016-06-15 20:46
I'm not able to get the myget package feed to work.

> [SignalR Nightly] Invalid portable frameworks.

This is the error on the Android package
> Could not install package 'Microsoft.AspNet.SignalR.Client 2.2.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by nanexo** [comment] 2016-06-22 13:28
Ran into the same issue. I tried adding 2.2.0 to the Xamarin PCL (Profile111) as well as Xamarin.Android directly. Had the same errors as described here.

Adding the 2.2.1 prelease package from the nightlies worked without issues.

**Comment by noocyte** [comment] 2016-07-07 07:07
When will 2.2.1 package be released? @moozzyk?

**Comment by moozzyk** [comment] 2016-07-07 13:42
Working on it (again) as we speak - so it should be soon.

**Comment by wpbest** [comment] 2016-07-07 16:27
Will that also work with Profile259?

**Comment by moozzyk** [comment] 2016-07-11 18:37
Yes. I tried and it installed correctly.

**Comment by moozzyk** [comment] 2016-07-11 19:01
Looks like a dupe of https://github.com/SignalR/SignalR/issues/3393.

**Closed by moozzyk** 2016-07-11 19:01 UTC
Labels: dupe
