### ISSUE TITLE
Which transport to use for 100,000 objects

### ISSUE THREAD

**Issue by AwsomeCode** [SignalR/SignalR#3835] opened 2017-01-11 15:20 UTC
I have tried webSocket but it has limits of 64Kb, serverSentEvents worked in setup environment but I am worried about slow connection. Size of the message is about 10Mb, will it be timeout? I am not worried about how slow it will go but will it reach after 2 min or 5min over 2g or 3g mobile connection?

**Comment by moozzyk** [comment] 2017-01-11 17:46
stackoverflow is a much better place to as questions. 

You can change the size limit of websocket messages. Also I am not sure if sending messages of 10MB in size using SignalR is a good idea. This sounds more like a download than realtime messaging. What is your scenario? 

Closing since it is not a bug in SignalR.

**Closed by moozzyk** 2017-01-11 17:46 UTC

**Comment by AwsomeCode** [comment] 2017-01-12 04:50
Hi @moozzyk , Most of the time message size will be under 10kb, its like some message 1 out 1000 will be around between 10Kb to 10mb. Its vary upon how much time client is disconnected for.

**Comment by moozzyk** [comment] 2017-01-12 17:11
You can configure the maximum size of a websocket message with this property https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Core/Configuration/IConfigurationManager.cs#L51.

**Comment by AwsomeCode** [comment] 2017-01-13 05:04
@moozzyk Thanks but. I encounter one more problem Xamarin does not support webockets. So I have to use serverSentEvents only. Is it fine?

**Comment by moozzyk** [comment] 2017-01-13 19:08
I guess you need to try it. Regardless of how you do it 10MB messages are much bigger than 10KB messages and it will take longer to transfer and process them. They will also be buffered on the server until they get overwritten by new messages (the buffer is a ring buffer and is kept per connection). Maybe you need to look whether you absolutely need to transfer all the data?
