### ISSUE TITLE
Dangling HubConnection after calling Stop

### ISSUE THREAD

**Issue by ralsu091** [SignalR/SignalR#4173] opened 2018-08-16 18:22 UTC
After taking a memory dump of one of the production services, I found more than 16k instances of SignalR HubConnection and HubProxy. This caused our service to degrade and eventually die. The service acts as a SignalR client and receives messages from our API servers.

![image](https://user-images.githubusercontent.com/5394171/44227257-28e79c80-a160-11e8-800b-ab7e31bf6383.png)

### Expected  behavior
Optimally, there should not be more than two HubConnection instances. 
### Actual behavior
After calling Stop on the hubConnection and instantiating another instance, the old instance is still in memory and is not collected by the garbage collector.
### Steps to reproduce
I have created a sample Console App that demonstrates the issue.
https://github.com/ralsu091/SignalR.HubConnection.Leak

### More Information
We need to create a new instance of the Hubconnection because we need to pass a bearer token as a query string. This bearer token needs to be refreshed every 24 hours.
We also have a watchdog Task that monitors the connection and messages. If we haven't received a message in x minutes then we know something is wrong and we need to stop the connection and create a new one, or if the connection is down (No internet, Server is down etc.) In the sample app I connect to a bogus server address to simplify things.

1- Are we supposed to keep one HubConnection for the life time of the application?
2- If yes, how do we handle disconnection and the need to update the query string?

I appreciate your help, please let me know if this is not the right place for this issue :)

**Comment by ralsu091** [comment] 2018-08-23 20:58
I would like to add that in Event Viewer I saw the following:
`A request to allocate an ephemeral port number from the global TCP port space has failed due to all such ports being in use.` 

**And**
 `TCP/IP failed to establish an outgoing connection because the selected local endpoint was recently used to connect to the same remote endpoint. This error typically occurs when outgoing connections are opened and closed at a high rate, causing all available local ports to be used and forcing TCP/IP to reuse a local port for an outgoing connection. To minimize the risk of data corruption, the TCP/IP standard requires a minimum time period to elapse between successive connections from a given local endpoint to a given remote endpoint.`

I wonder if all these SignalR connection are still in use and not closed. Any suggestions on how to proceed with issue is appreciated.

**Comment by anurse** [comment] 2018-09-24 18:56
I'm not able to build the sample you provided, it looks like there are missing types:

```
ralsu091\SignalR.HubConnection.Leak\SignalR.HubConnection.Leak\Program.cs(12,13,12,25): error CS0103: The name 'AsyncContext' does not exist in the current context
ralsu091\SignalR.HubConnection.Leak\SignalR.HubConnection.Leak\Program.cs(77,76,77,91): error CS0103: The name 'ConnectionState' does not exist in the current context
ralsu091\SignalR.HubConnection.Leak\SignalR.HubConnection.Leak\Program.cs(85,64,85,79): error CS0103: The name 'ConnectionState' does not exist in the current context
```

Also it looks like there's no server app to go along with this sample, so I'm not really able to run the sample in order to reproduce the issue.

Can you provide more context on how this sample illustrates your usage? For example, I can see that the sample app you provided appears to connect a subscriber but will never shut it down, so I can't see where the leak is supposed to be occurring.


> A request to allocate an ephemeral port number from the global TCP port space has failed due to all such ports being in use.

This error indicates that the connection isn't even being stopped, since the TCP port isn't being released, so every time you are creating a new one, the existing one is still around and you eventually run out of ephemeral ports (which happens at 16K ports). It sounds like the problems isn't that the connections are leaking but that they aren't shutting down. Do you have logs that can track the shutdown of the connection and verify that you're calling `Stop` prior to starting the new connection?

> Are we supposed to keep one HubConnection for the life time of the application?

Generally yes, you should be able to use a single HubConnection for the life of the app. However, as long as you Stop the connection and ensure all references to the old one are gone, it should be safe to create a brand new connection.

> If yes, how do we handle disconnection and the need to update the query string?

I believe you can stop the connection, change the public `QueryString` property (which is the full query string without the starting `?` value, so you'll have to convert your dictionary into `key=value&key=value` manually) and re-start it to update query string values.

**Comment by ralsu091** [comment] 2018-09-24 21:00
@anurse Thank you for taking the time to look at this issue. As @danburke-fidlar mentioned, it's a nuget issue that is not restoring the packages correctly. In the sample project, we call Stop in https://github.com/ralsu091/SignalR.HubConnection.Leak/blob/3bff63d9d8cd85ca2abc0b68ecb022f98a4fed96/SignalR.HubConnection.Leak/Subscriber.cs#L61 

As for the `QueryString`, We cannot set it after calling the constructor as it has a private setter.

@danburke-fidlar Do you have more information on your work around? Where do you provide your HttpClient?

**Comment by danburke-fidlar** [comment] 2018-09-24 21:08
The HttpClient can be specified in the Start method (Subscriber.cs - ConnectForSignalAsync).  Based on this:

https://github.com/SignalR/SignalR/blob/f5544f24c4a79bf2cca8850830a81bcfb67e1feb/src/Microsoft.AspNet.SignalR.Client45/Http/DefaultHttpClient.cs#L143

I recreated that class locally (which requires also recreating the Disposer, HttpHelper, and UrlEncoder internal classes, as well as reworking the .Then from the custom Task Async class), then modified the if/else statement to:

```
var responseMessage = await httpClient.SendAsync(requestMessage, HttpCompletionOption.ResponseHeadersRead, cts.Token);

            if (responseMessage != null)
            {
                if (lvResult.IsSuccessStatusCode)
                {
                    responseDisposer.Set(responseMessage);
                }
                else
                {
                    var lvError = responseMessage.ToString();

                    responseMessage.RequestMessage.Dispose();
                    responseMessage.Dispose();

                    throw new HttpClientException(lvError);
                }

                return (IResponse)new HttpResponseMessageWrapper(responseMessage);
            }
```

**Comment by ralsu091** [comment] 2018-09-24 21:27
@danburke-fidlar I will try it out and test it! Are you interested in sending a pull-request if @anurse approves it? I can also submit a pull-request to fix this issue :)

**Comment by anurse** [comment] 2018-09-24 22:34
Ah ok, so if this is the same root cause as https://github.com/SignalR/SignalR/issues/4092 then we can probably close this out if the workaround @danburke-fidlar provided works for you @ralsu091 . We are planning on fixing that issue in the 2.4.0 release.

A PR would certainly be welcome, but isn't required.

**Comment by anurse** [comment] 2018-09-24 22:35
> As for the `QueryString`, We cannot set it after calling the constructor as it has a private setter.

Ah yeah, I just noticed that too. I think re-creating the connection would be your best choice here then. As I said above, we shouldn't be leaking these anyway, so once we fix the underlying issue, you'll be all set to recreate the connection.

**Comment by ralsu091** [comment] 2018-09-26 14:32
Thanks @anurse, the workaround involves a lot of copying and pasting internal classes from the SignalR solution to our solutions, which is kinda ugly. I will wait for the 2.4.0 release :)

**Comment by anurse** [comment] 2018-09-26 16:09
Ok, I'll try to let you know when we have a preview build available with the fix and would appreciate it if you could give it a try!

**Comment by anurse** [comment] 2018-10-11 16:54
Closed, as #4092 has been merged. The fix should be available in the latest version of the SignalR packages on the https://dotnet.myget.org/gallery/aspnet-signalr MyGet feed. Feel free to comment further if the issue still occurs after updating. The fix will be released in Preview 2 of ASP.NET SignalR 2.4.0

**Closed by anurse** 2018-10-11 16:54 UTC

**Comment by ralsu091** [comment] 2018-11-21 17:15
@anurse Thank you for the update and the release! It does fix the port leak issue if the connection is dropped or interrupted. However, without the ability to update the query string, we will have to create a new HubConnection every time the connection drops and the Bearer Token changes. This means that we will have HubConnections that are not GC'd.
I'm not sure if the HubConnection are not supposed to be GC'd or if it is a bug. The work around that I can think of is to stop the connection, update the query string and start it again. but SignalR doesn't allow us to update the query string. 
I would like to hear your input.
Thanks again!

**Comment by ralsu091** [comment] 2018-11-21 18:41
I will create a new issue with a working sample. Thank you for following up.
