### ISSUE TITLE
Silverlight Clients on a Mac cannot connect to a Hub on Azure Webs App using SSL.

### ISSUE THREAD

**Issue by FinVamp1** [SignalR/SignalR#3500] opened 2015-06-08 17:12 UTC
**Impact**
Clients cannot connect to the Hub and messages will not be sent. 
Version 2.1.2

**Repro Steps**
Implement a Silverlight MVVM Application using the HubConnection in a ViewModel.

E.G.

In your Silverlight Application Create a Hub Class that defines the HubConnection, Proxy etc.

Then call this from your ViewModel.

The Hub itself is hosted on Azure Web Apps and secured with SSL. 

If you connect to the application using the port number in the URL then you cannot connect to the Hub.

this.hubConnection = new HubConnection("https://testdev.azurewebsites.net:443");
this.hubProxy = this.hubConnection.CreateHubProxy("TestHub");
await this.hubConnection.Start();

However, if we change the URL to "https://testdev.azurewebsites.net" it works.

**Expected Results**
The connection should succeed if you specify the port number or not. 

**Actual Results** 
The connection is never made.

**Comment by moozzyk** [comment] 2015-06-08 17:23
Is there any error? What does the log say?

**Comment by FinVamp1** [comment] 2015-06-08 17:34
The exception that occurs on the Mac contains:
[net_cookie_parse_header]
Argument: https://testdev.azurewebsites.net/signalr/negotiate?noCache=fb235e03-2d50-6d69-a5ad-59bf0882972e&clientProtocol=1.4&connectionData=%5B%7B%22Name%22:%22TestHub%22%7D%5D
Resource strings for debugging is not available. Often the key and arguments contain sufficient information for problem diagnosis.http://go.microsoft.com/fwlink/?linkid=106663&Version=5.1.30514.00&File=System.Net.dll&Key=net_cookie_parse_header

The tracing was enabled and this is what we saw. 

__This is the result from PC:__
11:06:41.6373917 - null - ChangeState(Disconnected, Connecting)
11:06:43.5280170 - da72f847-835a-45e5-a047-f492f050a2d2 - SSE: GET https://testdev.azurewebsites.net:443/signalr/connect?transport=serverSentEvents&clientProtocol=1.4&connectionToken=qmG2O5zPP2oJCKf5MKtbjTam37DFKe0J3NWWMWEjV3SGOGiI4A84SaA4n23PtPLzd7M0x%2FU%2BnGTMUbzko8MrUB%2BtYl4SuwhafD4yGy7Bfaxsv%2FWMT2cdkZoe4vFMJQVW&connectionData=[{"Name":"TestHub"}]&noCache=d4f235cf-1038-47d8-b9fa-955a57e663e2
11:06:43.6842737 - da72f847-835a-45e5-a047-f492f050a2d2 - SSE: OnMessage(Data: initialized)
11:06:43.6842737 - da72f847-835a-45e5-a047-f492f050a2d2 - SSE: OnMessage(Data: {"C":"d-180E320-A,0|B,0|C,1|D,0","S":1,"M":[]})
11:06:44.4669602 - da72f847-835a-45e5-a047-f492f050a2d2 - ChangeState(Connecting, Connected)  

__This is the result from Mac:__
21:54:48.4314120 - null - ChangeState(Disconnected, Connecting)
21:54:48.9372000 - null - Disconnected
21:54:48.9379750 - null - Transport.Dispose()
21:54:48.9382670 - null - Closed

**Comment by moozzyk** [comment] 2015-06-08 17:58
The resource for net_cookie_parse_header error is "An error occurred when parsing the Cookie header for Uri '{0}'.". Can you provide/investigate what cookie causes this issue and who and how sets it? Also there should be an inner exception that would provide more details about the failure.

**Comment by michael-bergman** [comment] 2015-12-17 13:05
I have been able to reproduce this issue in a small sample application that is hosted on Azure. The problem is related to the presence of one line of code in the application startup:
```csharp
WebRequest.RegisterPrefix("http://", WebRequestCreator.ClientHttp);
```
When running from a Mac, the client will be disconnected if the line is present. If you remove the line the client will be able to connect.
When running from a PC, the client can connect regardless of the presence of that line of code.

What is the cause of this different behavior between the platforms?
Is this something that can be fixed?

Please let me know if you need the sample application.

Thanks,
Michael

**Comment by aspnet-hello** [comment] 2018-09-20 22:04
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Closed by aspnet-hello** 2018-09-20 22:04 UTC
