### ISSUE TITLE
IPrincipal gets cached in ServerRequest that causes an issue when overriding AuthorizeAttribute

### ISSUE THREAD

**Issue by sergei-d** [SignalR/SignalR#3351] opened 2014-11-28 17:37 UTC
I need a custom implementation of AuthorizeAttribute. I do the following
public override bool AuthorizeHubConnection(Microsoft.AspNet.SignalR.Hubs.HubDescriptor hubDescriptor, IRequest request)
        {
            var authorizationHeaderValue = request.Headers[AuthorizationHeader];
            if (IsValid(authorizationHeaderValue))
            {
                var principal = new GenericPrincipal(new GenericIdentity("user"), new string[0]());
                request.Environment["server.User"] = principal;
            }
            return base.AuthorizeHubConnection(hubDescriptor, request);
        }

I expect that the request object has an updated principal which is passed in to UserAuthorized(IPrincipal user) method but i get null for user parameter.
The reason is that the User gets cached in ServerRequest object instead of reading the user from environment variable like all other properties in that object.

Thanks,
Sergei

**Comment by orand** [comment] 2015-03-17 00:11
I also ran into this and used reflection to get around it.

        private static FieldInfo _userFieldInfo;

        static MyAuthModule()
        {
            _userFieldInfo = typeof(ServerRequest).GetField("_user", BindingFlags.NonPublic | BindingFlags.Instance);
        }

In your AuthorizeHubConnection method you can then set the private _user field of ServerRequest like this:

            // optional guard code
            if (_userFieldInfo == null)
            {
                throw new ApplicationException("The private field ServerRequest._user no longer exists, please update the reflection code");
            }
            
            if (!(request is ServerRequest))
            {
                throw new ApplicationException("SignalR IRequest must be a ServerRequest");
            }

            _userFieldInfo.SetValue(request, principal);

**Comment by aspnet-hello** [comment] 2018-09-20 22:10
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Closed by aspnet-hello** 2018-09-20 22:10 UTC

**Comment by anilrp** [comment] 2019-02-28 05:06
AuthorizeAttribute is ignored by AzureSignalrService. I am using .net framework not core

**Comment by anurse** [comment] 2019-03-01 20:53
> AuthorizeAttribute is ignored by AzureSignalrService. I am using .net framework not core

I'd suggest filing this on https://github.com/azure/azure-signalr first. If the issue is limited to the Azure SignalR server, you should start in that repository. We work closely with them and they'll let us know if there's something we need to fix :).
