### ISSUE TITLE
massive /signalr/connect errors for a few users.

### ISSUE THREAD

**Issue by OlympicLarry** [SignalR/SignalR#4321] opened 2019-02-28 23:32 UTC
### Expected  behavior
Attempt to connect and down grade to longPolling etc...

### Actual behavior
1-3 users per day are throwing massive numbers of /signalr/connect 400 errors
I'm not sure what the expected behavior is when this happens but it seems like the client just keeps trying to connect and fails non stop.

![image](https://user-images.githubusercontent.com/10212320/53605678-84fe9500-3b75-11e9-9b96-1bdd743f61f3.png)

### Steps to reproduce
Not reproducible by me. I think it might be related to the user's network?

How can I limit the number of retries and force it to give up connecting to signalr ?

**Comment by clifton-collins3iii** [comment] 2019-03-07 14:37
We have experienced this in virtual machines with their network incorrectly configured.  While it is a networking issue to be resolved, it is desirable to have a signalr server function to stop the connect storm and remove the queued reconnect messages that cause the memory usage to climb to the GBytes.

When the memory starts leaking in this scenario, the timeouts do not appear to be working and the messages stay in memory with no method of removing/releasing other than restart the service.

**Comment by clifton-collins3iii** [comment] 2019-03-07 14:52
I have several memory dumps from our encounter with memory climbing after a network event. When we stop all of the clients, disconnect and wait for the signalr timeouts, nothing ever happens. It is like the messages are stuck in a queue with no way to clear and release memory. It seems that if you are using send.all then the entire group is attempting the reconnect and resend because the memory grows non-linear, increasing in growth each time.

https://pts1-my.sharepoint.com/:f:/g/personal/ccollins_ptssolutions_com/EriJrQTRYyZHkkv5VHSQMjwBoDX8ZT779gNfhvSOmgmSnQ

**Comment by OlympicLarry** [comment] 2019-03-07 17:46
This issue severely affects the server response time.

![image](https://user-images.githubusercontent.com/10212320/53977444-45c8ca80-40c6-11e9-9b1a-b0f4ad5fb3ee.png)

**Comment by clifton-collins3iii** [comment] 2019-03-11 16:26
Today we had a client attempt to connect to the signalr-owin server.  The message gets to the server and the server attempts to reply, but cannot, (due to a routing issue).  The client attempts to connect again, because it thinks it never connected because the message from the server never arrived, but the server attempts reconnect, not connect.  This continues until the signalr-owin process consumes all of the memory.  I have been unable to build in a hub monitor to 'shift' the reconnect back to a connect or even better, start blocking/dropping the reconnect and cleaning/releasing memory.  The network issue can be resolved, but signalr should be configurable or at least a method to find stuck messages, remove them and release memory.

**Comment by chiranjeevi-puvvula-ascendlearning-com** [comment] 2019-04-02 18:40
I'm seeing the same thing when load testing our app and monitoring with new relic. I'm using SQL server as the back plane. 
![image](https://user-images.githubusercontent.com/47794875/55427534-d02d0e80-554c-11e9-815a-4aa485c6f89d.png)
I thought connect call should only happen during the initialization of the connection . Do you guys have any info?

**Comment by halter73** [comment] 2019-04-09 21:30
> This issue severely affects the server response time.

/signalr/connect requests are meant to last indefinitely because that request is kept open and used to send messages to the client in real time. Seeing these request last minutes, hours or days is not unusual.

> 1-3 users per day are throwing massive numbers of /signalr/connect 400 errors

SignalR itself responds with a 400, you can look at the [SignalR's server tracing](https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing#enabling-tracing-on-the-server) to figure out why. It's also possible that a front-end is rejecting the request, so I'd also look at IIS logs. If you can, logging the raw rejected request could also assist in the investigation.

**Comment by OlympicLarry** [comment] 2019-04-09 21:58
@halter73 Thanks for replying. I thought I'd update this with what I found out so far and how I've had to combat it.

The clients that were generating all the errors were behind firewalls that block web sockets. 

I updated the suggested $.connection.hub.disconnected javascript code to keep track of how many attempts and to stop trying to connect after so many tries.

**Comment by anurse** [comment] 2019-04-17 02:36
> The clients that were generating all the errors were behind network firewalls that block web sockets.

So was the firewall triggering the `400` errors? I want to make sure we aren't missing a possible SignalR issue :).

**Comment by OlympicLarry** [comment] 2019-04-17 02:47
@anurse I believe it was some network security software by McAfee. I mentioned it to our client and they fixed their security settings. So yes, If anyone else has a misconfigured proxy server it would create the 400 errors. 

The biggest problem with this issue was the sheer number of errors it would throw. If you look at the image I posted (Mar 7) you can see how it affected the response time of our server. Those errors were generated from only 3-4 users.

**Comment by anurse** [comment] 2019-04-17 14:56
> So yes, If anyone else has a misconfigured proxy server it would create the 400 errors.

Yeah, this is somewhat expected. If the client (or security software on the client) is mangling the WebSocket connection, the server will issue `400` errors.

> you can see how it affected the response time of our server.

Are you tracking `/signalr/connect` as part of your response time tracking? I'd **strongly** advise excluding that URL (as well as `/signalr/ping` and `/signalr/reconnect`) from any response time tracking. These are the requests SignalR uses to establish and maintain the persistent connection and so they last for the duration of the **connection** by design. Most response time tracking tools see this as a very long running request, and flag it as a problem, but it is in fact exactly what you want out of a persistent connection :).

> The biggest problem with this issue was the sheer number of errors it would throw.

By default SignalR attempts to retry indefinitely, you could hook the [`reconnecting`](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client#connectionlifetime) event on the client and track a counter of reconnect attempts and use that to disconnect entirely if the client is reconnecting too frequently.

Since it looks like this was a client-side machine config issue, I'm going to close this. Feel free to comment further with any questions and/or file a new bug if something comes up!

**Closed by anurse** 2019-04-17 14:56 UTC
Labels: waiting

**Comment by halter73** [comment] 2019-04-18 19:04
> I'd strongly advise excluding that URL (as well as /signalr/ping and /signalr/reconnect)

/signalr/poll is the long-running request should be excluded along with signalr/connect and /signalr/reconnect.

/signalr/ping should complete quickly, but it might be best just to exclude all requests starting with /signalr/
