### ISSUE TITLE
Retrieving Remote IP throws ArgumentException in Hub.OnDisconnected

### ISSUE THREAD

**Issue by pseabury** [SignalR/SignalR#3446] opened 2015-04-06 19:57 UTC
Hub.OnDisconnected throws ArgumentException when trying to retrieve the remote IP a couple of different ways.

```
Value does not fall within the expected range.     at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at System.Web.Util.Misc.ThrowIfFailedHr(Int32 hresult)
   at System.Web.Hosting.IIS7WorkerRequest.GetServerVariableInternal(String name)
   at System.Web.Hosting.IIS7WorkerRequest.GetServerVariable(String name)
   at System.Web.Hosting.IIS7WorkerRequest.GetRemoteAddress()
   at System.Web.HttpRequest.get_UserHostAddress()
   at System.Web.HttpRequestWrapper.get_UserHostAddress()
```

```
public override async Task OnDisconnected(bool stopCalled)
{
    // Always throws ArgumentException
    Context.Request.GetHttpContext().Request.UserHostAddress;
    ...
}
```

```
public override async Task OnDisconnected(bool stopCalled)
{
    // OWIN - Works for WebSockets, Throws for non-WebSockets
    var env = Context.Request.Environment; 
    object value;
    env.TryGetValue("server.RemoteIpAddress", out value);
    ...
}
```

**Comment by kestelle** [comment] 2015-04-06 19:59
+1

**Comment by Jiwei** [comment] 2015-08-05 12:44
I encountered exactly the same problem (with the second sample). Did you find any solutions? Please let me know.

**Comment by pseabury** [comment] 2015-08-05 13:15
For now I just try/catch and throw away the exception.

**Comment by Jiwei** [comment] 2015-08-05 14:41
Hi, I found a workaround on this. It seems like you are not supposed to retrieve IP in OnDisconnected() since sometime when you call Context.Request there the page itself is already closed, hence the request doesn't work. Basically this is caused by the latency between closing the page and disconnection.

However, the connectionId from context should be available until the very end. Hence, what you could do is to retrieve IP address OnConnected and map IP with connectionId. And OnDisconnected you can access IP through connectionId, without making the request.

**Comment by aspnet-hello** [comment] 2018-09-20 22:06
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Closed by aspnet-hello** 2018-09-20 22:06 UTC
