### ISSUE TITLE
Negotiate calls failing: The invoked member is not supported in a dynamic assembly.

### ISSUE THREAD

**Issue by saasen** [SignalR/SignalR#3967] opened 2017-07-11 08:48 UTC
Hi.

We have an issue where we're getting the following exception:

```
System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
   at System.Reflection.Emit.InternalAssemblyBuilder.get_Location()
   at Microsoft.AspNet.SignalR.Hubs.ReflectedHubDescriptorProvider.GetTypesSafe(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.AspNet.SignalR.Hubs.ReflectedHubDescriptorProvider.BuildHubsCache()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.get_Value()
   at Microsoft.AspNet.SignalR.Hubs.ReflectedHubDescriptorProvider.TryGetHub(String hubName, HubDescriptor& descriptor)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.AspNet.SignalR.Hubs.DefaultHubManager.GetHub(String hubName)
   at Microsoft.AspNet.SignalR.Hubs.HubManagerExtensions.EnsureHub(IHubManager hubManager, String hubName, IPerformanceCounter[] counters)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.AuthorizeRequest(IRequest request)
   at Microsoft.AspNet.SignalR.PersistentConnection.ProcessRequest(IDictionary`2 environment)
   at Microsoft.Owin.Mapping.MapMiddleware.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

This happens every time a client tries to call `/signalr/negotiate`. We get a 500 from the server with the exception above.
This started happening one week after we upgraded from SignalR 2.2.0 to 2.2.2 and may be related.

This is our startup class:
```
public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            AppDomain.CurrentDomain.Load(typeof (SignalR.MessagingHub).Assembly.FullName); // Loads an assembly which contains hubs in another project
            app.MapSignalR();
        }
    }
```

* I can reproduce the problem, but it's one of those issues that sometimes happens at startup.
* Operating System: Windows Server 2012 R2
* IIS: Version 8.5.9600.16384
* Visual Studio 2017

Versions of NuGet packages:
* `Microsoft.Owin: 2.1.0`
* `Microsoft.Owin.Host.SystemWeb: 2.1.0`
* `Microsoft.Owin.Security: 2.1.0`
* `Owin: 1.0.0`

* `Microsoft.AspNet.SignalR: 2.2.2`
* `Microsoft.AspNet.SignalR.Core: 2.2.2`
* `Microsoft.AspNet.SignalR.JS: 2.2.2`
* `Microsoft.AspNet.SignalR.SystemWeb: 2.2.2`

### Expected  behavior
SignalR working properly.

### Actual behavior
SignalR negotiate call failing and is throwing 500 errors on the server side.

### Steps to reproduce
? Can reproduce, as it looks like something wrong happens at startup. Our project is emitting some dynamic assemblies, but shouldn't crash SignalR. My guess is that has something to do with it.

**Comment by saasen** [comment] 2017-07-11 08:48
I just noticed. May be related to #3963.

**Comment by saasen** [comment] 2017-07-11 11:42
We tried to downgrade to 2.2.0 (to the version we had before seeing this problem). This problem still happens.

**Comment by moozzyk** [comment] 2017-07-11 15:38
Yes, it's a dupe of #3963.

**Comment by saasen** [comment] 2017-07-12 15:52
@moozzyk: Should I close this one?

**Comment by moozzyk** [comment] 2017-07-12 16:17
Yeah, let's close this one. I assigned #3963 to the vNext milestone meaning we we will consider it for the next servicing release.

**Closed by moozzyk** 2017-07-12 16:17 UTC
