### ISSUE TITLE
Message ordering is not preserved even when awaiting calls.

### ISSUE THREAD

**Issue by rowanG077** [SignalR/SignalR#4099] opened 2018-04-20 12:51 UTC
### Expected  behavior
Message order send from server to client and vice versa should be preserved.

### Actual behavior
An awaited RPC in an SignalR endpoint is arriving after the return of the method in the hub in rare cases.

### Steps to reproduce

I have an SignalR endpoint:

```
public async Task Ping()
{
    await Clients.Caller.Pong();
}
```

Then in my javascript client I call the Ping function:

```
this.hubProxy.on('pong', function() {
    console.log('Pong was called by server');
});

console.log('Calling ping on the server');
this.hubProxy.invoke('ping')
    .then(function() {
        console.log('Ping called returned');
    })
```
I expect the following logs to occur:

```
Calling ping on the server
Pong was called by server
Ping called returned
```

But once every so often this is logged:

```
Calling ping on the server
Ping called returned
Pong was called by server
```

I investigated by watching the websocket datastream in chrome and indeed the messages are reversed in some cases:

Everything goes well:
```
Send: {"H":"pingHub","M":"ping","A":[],"I":3}
Recieved: {"C":".....","M":[{"H":"PingHub","M":"Pong","A":[]}]}
Recieved: {"I":"3"}
```

Message order is not preserved:
```
Send: {"H":"pingHub","M":"ping","A":[],"I":11}
Recieved: {"I":"11"}
Recieved: {"C":".....","M":[{"H":"PingHub","M":"Pong","A":[]}]}
```

SignalR version both js client and server: 2.2.3

I have attached a project which automatically demonstrates this issue just run it and watch the console for the error. It continously sends ping messages and stops when ordering isn't preserved.

[signalrOrdering.zip](https://github.com/SignalR/SignalR/files/1932565/signalrOrdering.zip)

To be sure I deployed the test application to a remote web server and watched the TCP stream and sure enough the message order is not preserved on the networking level. 

The problem seems to occur a lot more when you switch windows/tabs in the browser. But I can't imagine why that would have an effect...

**Comment by rowanG077** [comment] 2018-05-09 13:12
Is SignalR dead and we should just switch to .Net Core? If so then please put this information on the site because I don't know whether I should invest a lot of time to migrate to core.

**Comment by davidfowl** [comment] 2018-05-21 07:47
This isn't a bug. There's no guaranteed order between outgoing invocations from client to server and messages sent from server to client. The only guarantee is that messages sent to the same "signal" if awaited will be sent to the client in the same order. So if you have out of order calls to `Pong was called by server` that would be a problem.

> Is SignalR dead and we should just switch to .Net Core? If so then please put this information on the site because I don't know whether I should invest a lot of time to migrate to core.

SignalR is in maintenance mode and only critical fixes are being looked at.

**Comment by rowanG077** [comment] 2018-05-21 14:30
'Clients.Caller' is the same "signal" as where the return of the function ends up. Is the behavior the same in SignalR for .NET Core? Because this basically makes promise/Task returned from an invocation meaningless.

**Comment by davidfowl** [comment] 2018-05-21 15:51
> 'Clients.Caller' is the same "signal" as where the return of the function ends up. 

It's not. Values returned from methods are not signals.

> Is the behavior the same in SignalR for .NET Core? Because this basically makes promise/Task returned from an invocation meaningless.

It's a little different in ASP.NET Core SignalR but the behavior and it'll likely do what you want when you're running on a single server but all bets are off when you use a backplane. The Task returned from server -> client calls represents what it takes to get data enqueued so that order is preserved. When you're using a backplane, messages aren't delivered inline, they get enqueued and delivered later and the Task might fail if the message didn't get enqueued. 

Regardless, it's by design so I'm closing this issue out.

**Closed by davidfowl** 2018-05-21 15:51 UTC
