### ISSUE TITLE
CRITICAL: Disconnected. Reason: The client has been inactive since XXX and it has exceeded the inactivity timeout of 50000 ms. Stopping the connection.

### ISSUE THREAD

**Issue by firephantomassasin** [SignalR/SignalR#4546] opened 2021-03-22 07:24 UTC
In using google chrome latest version: Version 89.0.4389.90 (Official Build) (64-bit)

It is weird that if the tab is being minimized / inactive for a long time (after few mins, my observation was 5-20 mins), the disconnection will trigger and it will keep on disconnecting every 2 mins.

This is the error message - signalrService.lastError:

The client has been inactive since Mon Mar 22 2021 15:01:33 GMT+0800 (China Standard Time) and it has exceeded the inactivity timeout of 50000 ms. Stopping the connection.

It is only happening to Chrome so far, Will observe w/ Edge.

It is happening to our localhost and Prod.

So far it is not happening to Edge / Firefox. We experienced this issue in Google Chrome. Upon checking the JS library code, there is a weird thing happening in the setTimeout, it doesn't call right away after the specified interval if the tab has been inactive for X minutes, then i saw this article regarding new updates on Chrome:

https://developer.chrome.com/blog/timer-throttling-in-chrome-88/

I hope this library should have a workaround fix for the Intensive throttling of chrome.

**Comment by BrennanConroy** [comment] 2021-03-22 16:14
Dupe of https://github.com/SignalR/SignalR/issues/4536

**Closed by BrennanConroy** 2021-03-22 16:14 UTC
