### ISSUE TITLE
XML parsing error: Hub reply does not define a root element 

### ISSUE THREAD

**Issue by kblok** [SignalR/SignalR#4075] opened 2018-02-13 19:51 UTC
I'm replicating the [issue reported in the SignalR Core repo](https://github.com/aspnet/SignalR/issues/1106)

>This doesn't present a problem of the function, it is just not pretty; when invoking a method on the server my FF Developer tab reports:
>XML Parsing Error: no root element found
>Location: https://localhost:44311/signalr?id=ff8ff481-439a-4bcc-8f1f-67941a5ca331
>Line Number 1, Column 1:

>Again, not a bug per se but it does clutter the dev window. Not sure if it can be changed or if the browser is wrong.

I'm getting the same issue on FF when SignalR calls the close function. I'm getting this when the page is unloaded. It's not a big deal, but nobody like getting errors on the dev tools.

**Comment by isaacplmann** [comment] 2018-02-15 20:13
I'm experiencing the same issue.

**Comment by Nath0s** [comment] 2018-02-16 09:11
Having the same issue too...

**Comment by electricessence** [comment] 2018-02-16 21:18
Same here.  It seemed to not be this way not but yesterday.  Then I changed my hubs to reduce the number of methods.  In fact, eliminating all methods because only want to emit events.

I tried adding methods, to see if the XML changed, but no dice.

**Comment by molo9966** [comment] 2018-02-23 20:20
Using .NET MVC SIGNALR and jquery signalR 2.2.2 and, in firefox, getting following in console...

XML Parsing Error: no root element found
Location: http://l-mmoloney2.qvidiancorp.com/Qvidian.WOPI/signalr/signalr/abort?transport=we.......

This seems to then stop any SIGNALR messaging for the browser.  
Is there a new release upcoming to fix this?

**Comment by omaximenco** [comment] 2018-04-17 05:52
2.2.3 - same issue. It seems like SignalR for asp.net is a forgotten project...

**Comment by electricessence** [comment] 2018-04-17 16:05
@omaximenco It's definitely not.   It's in NPM without jQuery.  As the new Core version.
The issue is kinda jQuery because a request without a response body is fine, but only works without throwing in jQuery if you specify the content to be text and not json. :(

**Comment by Nath0s** [comment] 2018-04-18 06:59
@molo9966 Apparently, firefox is losing the connection right after the first connection attempt, the only fix i found was to call the connection function after the disconnection is detected
`//Only for firefox
    $.connection.hub.disconnected(function () {
        setTimeout(function () {
            $.connection.hub.start().done(function () {
            });
        }, 1);
    });`
With this it should be alright ;)

**Comment by electricessence** [comment] 2018-04-18 15:06
lol  I think the right fix is not to use jQuery (which is exactly how the new signalR works).  But again, if jquery for this version is a must, then the underlying request needs to specify the expected return type as text if no data is to be returned and only a 200.

**Comment by anurse** [comment] 2018-10-11 20:41
This was fixed in https://github.com/SignalR/SignalR/commit/a0b4b4b74ce35d9359182ad654c8c9453e06685f

**Closed by anurse** 2018-10-11 20:41 UTC
