### ISSUE TITLE
Windows phone. SSE connection falls after random time and don't rise up

### ISSUE THREAD

**Issue by gzroman** [SignalR/SignalR#3400] opened 2015-01-29 14:51 UTC
I decide use SSE because can't connect to hub via long polling with my WP Lumia. It works but sometimes device lose connection and can't reconnect. 
There is detailed log from visual studio:

[HUB] StateChanged (OldState: Connected - NewState: Reconnecting)
[HUB] Reconnect...
[HUB] Fatal Error: Error HRESULT E_FAIL has been returned from a call to a COM component.
[HUB] Detail logs: 13:13:18.0197087 - null - ChangeState(Disconnected, Connecting)
13:13:20.1474841 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: GET http://my_server_name.azurewebsites.net/signalr/connect?clientProtocol=1.4&transport=serverSentEvents&connectionData=[{"Name":"my_hub_name"}]&connectionToken=my_connection_token&noCache=c3c5a9cc-abbc-4005-99ce-e3eca924c24c
13:13:20.4620066 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: OnMessage(Data: initialized)
13:13:20.4660351 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: OnMessage(Data: {"C":"d-D7BC854F-IS,0|J0,0|IU,0|J1,1","S":1,"M":[]})
13:13:21.3040620 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: OnMessage(Data: {"C":"d-D7BC854F-IS,0|J0,2|IU,0|J1,1","M":[{"$id":"3948","$type":"Microsoft.AspNet.SignalR.Hubs.ClientHubInvocation, Microsoft.AspNet.SignalR.Core","H":"my_hub_name","M":"getConnectionId","A":["023c6e4e-9ae8-4b91-aaa5-7517038d10e6"]},{"$id":"3949","$type":"Microsoft.AspNet.SignalR.Hubs.ClientHubInvocation, Microsoft.AspNet.SignalR.Core","H":"my_hub_name","M":"getMachineName","A":["RD00155D88B53F"]}]})
13:13:21.4592370 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: OnMessage(Data: {"C":"d-D7BC854F-IS,0|J0,2|IU,0|J1,B|Ia,1|Ib,2|Ic,1|Id,1|Ie,1|If,1|Ig,1|Ih,1|Ii,1|Ij,1","G":some_string,"M":[]})
13:13:21.4773678 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: OnMessage(Data: {"C":"d-D7BC854F-IS,0|J0,2|IU,0|J1,15|Ia,1|Ib,2|Ic,1|Id,1|Ie,1|If,1|Ig,1|Ih,1|Ii,1|Ij,1|Ik,1|Il,1|Im,1|In,1|Io,1|Ip,1|Iq,1|Ir,1|Is,1|It,1","G":some_string,"M":[]})
13:13:21.4793810 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: OnMessage(Data: {"C":"d-D7BC854F-IS,0|J0,2|IU,0|J1,1F|Ia,1|Ib,2|Ic,1|Id,1|Ie,1|If,1|Ig,1|Ih,1|Ii,1|Ij,1|Ik,1|Il,1|Im,1|In,1|Io,1|Ip,1|Iq,1|Ir,1|Is,1|It,1|Iu,1|Iv,1|Iw,1|Ix,1|Iy,1|Iz,1|I0,1|I1,1|I2,1|I3,1","G":some_string,"M":[]})
13:13:21.4834077 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: OnMessage(Data: {"C":"d-D7BC854F-IS,0|J0,2|IU,0|J1,29|Ia,1|Ib,2|Ic,1|Id,1|Ie,1|If,1|Ig,1|Ih,1|Ii,1|Ij,1|Ik,1|Il,1|Im,1|In,1|Io,1|Ip,1|Iq,1|Ir,1|Is,1|It,1|Iu,1|Iv,1|Iw,1|Ix,1|Iy,1|Iz,1|I0,1|I1,1|I2,1|I3,1|I4,1|I5,1|I6,1|I7,1|I8,1|I9,1|I_,1|I:,1|JA,1|JB,1","G":some_string,"M":[]})
13:13:21.5160890 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: OnMessage(Data: {"C":"d-D7BC854F-IS,0|J0,2|IU,0|J1,33|Ia,1|Ib,2|Ic,1|Id,1|Ie,1|If,1|Ig,1|Ih,1|Ii,1|Ij,1|Ik,1|Il,1|Im,1|In,1|Io,1|Ip,1|Iq,1|Ir,1|Is,1|It,1|Iu,1|Iv,1|Iw,1|Ix,1|Iy,1|Iz,1|I0,1|I1,1|I2,1|I3,1|I4,1|I5,1|I6,1|I7,1|I8,1|I9,1|I_,1|I:,1|JA,1|JB,1|JC,1|JD,1|JE,1|JF,1|JG,1|JH,1|JI,1|JJ,1|JK,1|JL,1","G":some_string,"M":[]})
13:13:21.5332126 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: OnMessage(Data: {"C":"d-D7BC854F-IS,0|J0,2|IU,0|J1,3D|Ia,1|Ib,2|Ic,1|Id,1|Ie,1|If,1|Ig,1|Ih,1|Ii,1|Ij,1|Ik,1|Il,1|Im,1|In,1|Io,1|Ip,1|Iq,1|Ir,1|Is,1|It,1|Iu,1|Iv,1|Iw,1|Ix,1|Iy,1|Iz,1|I0,1|I1,1|I2,1|I3,1|I4,1|I5,1|I6,1|I7,1|I8,1|I9,1|I_,1|I:,1|JA,1|JB,1|JC,1|JD,1|JE,1|JF,1|JG,1|JH,1|JI,1|JJ,1|JK,1|JL,1|JM,1|JN,1|JO,1|JP,1|JQ,1|JR,1|JS,1|JT,1|JU,1|JV,1","G":some_string,"M":[]})
13:13:21.5352232 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: OnMessage(Data: {"C":"d-D7BC854F-IS,0|J0,2|IU,0|J1,47|Ia,1|Ib,2|Ic,1|Id,1|Ie,1|If,1|Ig,1|Ih,1|Ii,1|Ij,1|Ik,1|Il,1|Im,1|In,1|Io,1|Ip,1|Iq,1|Ir,1|Is,1|It,1|Iu,1|Iv,1|Iw,1|Ix,1|Iy,1|Iz,1|I0,1|I1,1|I2,1|I3,1|I4,1|I5,1|I6,1|I7,1|I8,1|I9,1|I_,1|I:,1|JA,1|JB,1|JC,1|JD,1|JE,1|JF,1|JG,1|JH,1|JI,1|JJ,1|JK,1|JL,1|JM,1|JN,1|JO,1|JP,1|JQ,1|JR,1|JS,1|JT,1|JU,1|JV,1|JW,1|JX,1|JY,1|JZ,1|Ja,1|Jb,1|Jc,1|Jd,1|Je,1|Jf,1","G":some_string,"M":[]})
13:13:21.5815579 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - ChangeState(Connecting, Connected)
13:13:21.6137841 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: OnMessage(Data: {"C":"d-D7BC854F-IS,0|J0,2|IU,0|J1,51|Ia,1|Ib,2|Ic,1|Id,1|Ie,1|If,1|Ig,1|Ih,1|Ii,1|Ij,1|Ik,1|Il,1|Im,1|In,1|Io,1|Ip,1|Iq,1|Ir,1|Is,1|It,1|Iu,1|Iv,1|Iw,1|Ix,1|Iy,1|Iz,1|I0,1|I1,1|I2,1|I3,1|I4,1|I5,1|I6,1|I7,1|I8,1|I9,1|I_,1|I:,1|JA,1|JB,1|JC,1|JD,1|JE,1|JF,1|JG,1|JH,1|JI,1|JJ,1|JK,1|JL,1|JM,1|JN,1|JO,1|JP,1|JQ,1|JR,1|JS,1|JT,1|JU,1|JV,1|JW,1|JX,1|JY,1|JZ,1|Ja,1|Jb,1|Jc,1|Jd,1|Je,1|Jf,1|Jg,1|Jh,1|Ji,1|Jj,1|Jk,1|Jl,1|Jm,1|Jn,2|Jo,2|Jp,1","G":some_string,"M":[]})
13:13:21.6147942 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: OnMessage(Data: {"C":"d-D7BC854F-IS,0|J0,2|IU,0|J1,52|Ia,1|Ib,2|Ic,1|Id,1|Ie,1|If,1|Ig,1|Ih,1|Ii,1|Ij,1|Ik,1|Il,1|Im,1|In,1|Io,1|Ip,1|Iq,1|Ir,1|Is,1|It,1|Iu,1|Iv,1|Iw,1|Ix,1|Iy,1|Iz,1|I0,1|I1,1|I2,1|I3,1|I4,1|I5,1|I6,1|I7,1|I8,1|I9,1|I_,1|I:,1|JA,1|JB,1|JC,1|JD,1|JE,1|JF,1|JG,1|JH,1|JI,1|JJ,1|JK,1|JL,1|JM,1|JN,1|JO,1|JP,1|JQ,1|JR,1|JS,1|JT,1|JU,1|JV,1|JW,1|JX,1|JY,1|JZ,1|Ja,1|Jb,1|Jc,1|Jd,1|Je,1|Jf,1|Jg,1|Jh,1|Ji,1|Jj,1|Jk,1|Jl,1|Jm,1|Jn,2|Jo,2|Jp,1|Jq,1","G":some_string,"M":[]})
13:13:29.9646700 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: OnMessage(Data: {})
13:13:39.5451568 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: OnMessage(Data: {})
13:13:49.5151863 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: OnMessage(Data: {"C":"d-D7BC854F-IS,0|J0,2|IU,0|J1,52|Ia,1|Ib,3|Ic,1|Id,1|Ie,1|If,1|Ig,1|Ih,1|Ii,1|Ij,1|Ik,1|Il,1|Im,1|In,1|Io,1|Ip,1|Iq,1|Ir,1|Is,1|It,1|Iu,1|Iv,1|Iw,1|Ix,1|Iy,1|Iz,1|I0,1|I1,1|I2,1|I3,1|I4,1|I5,1|I6,1|I7,1|I8,1|I9,1|I_,1|I:,1|JA,1|JB,1|JC,1|JD,1|JE,1|JF,1|JG,1|JH,1|JI,1|JJ,1|JK,1|JL,1|JM,1|JN,1|JO,1|JP,1|JQ,1|JR,1|JS,1|JT,1|JU,1|JV,1|JW,1|JX,1|JY,1|JZ,1|Ja,1|Jb,1|Jc,1|Jd,1|Je,1|Jf,1|Jg,1|Jh,1|Ji,1|Jj,1|Jk,1|Jl,1|Jm,1|Jn,3|Jo,3|Jp,1|Jq,1","M":[{"$id":"4115","$type":"Microsoft.AspNet.SignalR.Hubs.ClientHubInvocation, Microsoft.AspNet.SignalR.Core","H":"my_hub_name","M":"userIsOffline","A":[1]},{"$id":"4129","$type":"Microsoft.AspNet.SignalR.Hubs.ClientHubInvocation, Microsoft.AspNet.SignalR.Core","H":"my_hub_name","M":"userIsOffline","A":[1]},{"$id":"4131","$type":"Microsoft.AspNet.SignalR.Hubs.ClientHubInvocation, Microsoft.AspNet.SignalR.Core","H":"my_hub_name","M":"userIsOffline","A":[1]}]})
13:13:49.5202214 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: OnMessage(Data: {})
13:13:59.5416868 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: OnMessage(Data: {})
13:14:12.9982736 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - Connection Timeout Warning : Notifying user
13:14:13.0002896 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - OnConnectionSlow
13:14:19.6825656 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - Connection Timed-out : Transport Lost Connection
13:14:22.2961958 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - ChangeState(Connected, Reconnecting)
13:14:22.4174819 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: GET http://my_server_name.azurewebsites.net/signalr/reconnect?clientProtocol=1.4&transport=serverSentEvents&connectionData=[{"Name":"my_hub_name"}]&connectionToken=my_connection_token&messageId=my_message_id&groupsToken=my_groups_token&noCache=bff57efd-7c33-4a5f-8e3f-447d19adf371
13:14:23.1802365 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - OnError(System.Exception: Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Net.Browser.ClientHttpWebRequest.InternalEndGetResponse(IAsyncResult asyncResult)
   at System.Net.Browser.ClientHttpWebRequest.<>c__DisplayClasse.<EndGetResponse>b__d(Object sendState)
   at System.Net.Browser.AsyncHelper.<>c__DisplayClass1.<BeginOnUI>b__0(Object sendState))

[HUB] Fatal Error: Error HRESULT E_FAIL has been returned from a call to a COM component.
[HUB] Detail logs: 13:14:25.3380923 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: GET http://my_server_name.azurewebsites.net/signalr/reconnect?clientProtocol=1.4&transport=serverSentEvents&connectionData=[{"Name":"my_hub_name"}]&connectionToken=my_connection_token&messageId=my_message_id&groupsToken=my_groups_token&noCache=5a63fae2-905b-4575-897e-4031561bac0c
13:14:26.1523921 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - OnError(System.Exception: Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Net.Browser.ClientHttpWebRequest.InternalEndGetResponse(IAsyncResult asyncResult)
   at System.Net.Browser.ClientHttpWebRequest.<>c__DisplayClasse.<EndGetResponse>b__d(Object sendState)
   at System.Net.Browser.AsyncHelper.<>c__DisplayClass1.<BeginOnUI>b__0(Object sendState))

[HUB] Fatal Error: Error HRESULT E_FAIL has been returned from a call to a COM component.
[HUB] Detail logs: 13:14:28.2183207 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - SSE: GET http://my_server_name.azurewebsites.net/signalr/reconnect?clientProtocol=1.4&transport=serverSentEvents&connectionData=[{"Name":"my_hub_name"}]&connectionToken=my_connection_token&messageId=my_message_id&groupsToken=my_groups_token&noCache=01d9f1e9-ea70-4894-8519-3d63bf42555e
13:14:29.0324653 - 023c6e4e-9ae8-4b91-aaa5-7517038d10e6 - OnError(System.Exception: Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Net.Browser.ClientHttpWebRequest.InternalEndGetResponse(IAsyncResult asyncResult)
   at System.Net.Browser.ClientHttpWebRequest.<>c__DisplayClasse.<EndGetResponse>b__d(Object sendState)
   at System.Net.Browser.AsyncHelper.<>c__DisplayClass1.<BeginOnUI>b__0(Object sendState))

**Comment by moozzyk** [comment] 2015-01-29 17:42
Can you show how you send messages from your app? [This](http://stackoverflow.com/questions/4162368/webclient-error-random-and-very-very-annoying) SO thread indicates that a similar problem may happen when requests are sent from the UI thread and the UI thread is blocked.

**Comment by gzroman** [comment] 2015-01-30 09:52
We don't send messages from client to hub. What we really do with signalr on client it is connection to hub with this code:

public async Task Connect()
{
    Response resp = await ChatApi.Instance.Login();
    if (resp.IsCompleted)
    {
        var cookies = ((HttpWebResponse)resp.WebResp).Cookies;
        _connectHub.CookieContainer = new CookieContainer();
        _connectHub.CookieContainer.Add(new Uri(_url), cookies);

        await _connectHub.Start(new ServerSentEventsTransport());
        Debug.WriteLine("[HUB] Transport: " + _connectHub.Transport.Name);
    }
    else
    {
        Debug.WriteLine("[HUB] Login failed");
    }
}

Client is builded with VS2013 ARM architecture.
Cilent/Server versions are 2.2.0/2.2.0

**Comment by moozzyk** [comment] 2015-02-11 18:24
This is a dupe of #3408

**Closed** 2015-02-11 18:24 UTC
Labels: dupe
