### ISSUE TITLE
Hub OnDisconnected - Context.User.Identity.Name throwing an ObjectDisposedException in IE

### ISSUE THREAD

**Issue by n1ghtmare** [SignalR/SignalR#2972] opened 2014-04-06 18:14 UTC
Hi guys, first of all SignalR is awesome. Also I'm sorry if this has been documented before - couldn't find anything.

Steps to reproduce the issue:
1. Create an ASP.NET MVC project using Windows Authentication
2. Create a Hub:

``` C#
public class ChatHub : Hub {
   public override Task OnDisconnected() {
      // throws an ObjectDisposedException if you open the app in IE (not in Chrome)
      string name = Context.User.Identity.Name; 
      return base.OnDisconnected();
   }
}
```

I've tested this on 2 different machines (Windows 8 and Windows 7). I should also note that it works fine on an app that uses Forms Authentication. Let me know if I can provide more details.

**EDIT**

After some more fiddling, it turns out it happens in IE10 and IE9 as well.

**Comment by sisterray** [comment] 2015-09-10 10:29
HI, Is this issue fixed. I am still getting the issue in version 2.1.2, Is it in 2.2.0?

**Comment by Lakritzator** [comment] 2016-04-26 14:24
Although it's not a problem to catch the exception, I was also wondering if this issue has a chance of being solved.

Maybe you are all tied-up in dotnet core?

On a side note, the README.md points to a none existing ci server:
> We have a CI Server (http://ci.signalr.net/)

--> https://ci.asp.net/ no such host

**Comment by michaelschmit** [comment] 2017-03-29 21:06
I am still seeing this issue today on SignalR 2.2.1

**Comment by ysmoradi** [comment] 2017-05-09 11:35
When you'll fix this issue? Thanks in advance

**Comment by Lakritzator** [comment] 2017-05-09 14:09
FYI: With SignalR 2.2.2 the issue is still there.

**Comment by johnfabian** [comment] 2017-11-20 16:08
What are you supposed to with OnDisconnected with the "Safe Handle" exception being throwed to update that the user is no longer online. How do you track users with this exception. ConnectionIds? That's it? No username?

**Comment by sisterray** [comment] 2017-11-20 17:00
You have to manage the mapping between usernames and connectionIds yourself, for example updating a database table when the user first makes the connection. In the OnDisconnected event you will get the connectionId, you need to use this to look up which user had that connectionId

**Comment by johnfabian** [comment] 2017-11-20 18:23
That's what I figured, I was following MS documentation : https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/mapping-users-to-connections#inmemory

**Comment by aspnet-hello** [comment] 2018-09-20 22:48
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Closed by aspnet-hello** 2018-09-20 22:48 UTC
Labels: type: Bug

**Comment by rajeevBlr** [comment] 2019-03-11 07:52
I am still facing the issue. I am using WPF client and when the user disconnects, it runs into the same error when I try to access Context.User.Identity.Name; 

`  public override Task OnDisconnected(bool stopCalled)
        {
            var userConnection = new UserConnection
                                     {
                                         UserName = this.Context.User.Identity.Name,
                                         ConnectionID = this.Context.ConnectionId
                                     };
            this.ScenarioHubContainer.OnDisconnected(userConnection);
            return base.OnDisconnected(stopCalled);
        }
`

Above is the code where I am running into the issue. 

Please note:

- SignalR is hosted within WebApi project. 

- Windows Authentication has been enabled for the WebAPI.

- using Microsoft.AspNet.SignalR  version="2.2.2" targetFramework="net472"

**Comment by Suresh9sb** [comment] 2019-11-07 20:35
Hi, I am facing this issue as well, 
I am using WPF Client with MVC 5 which connects to Signalr (version 2.3.0.0) Hub hosted on IIS. I see below error which is sporadic in nature in OnDisconnected

System.ObjectDisposedException: 'Safe handle has been closed' when I call Context.User.Identity.Name

Exception Details : 
System.ObjectDisposedException
  HResult=0x80131622
  Message=Safe handle has been closed
  Source=mscorlib
  StackTrace:
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.Win32Native.GetTokenInformation(SafeAccessTokenHandle TokenHandle, UInt32 TokenInformationClass, SafeLocalAllocHandle TokenInformation, UInt32 TokenInformationLength, UInt32& ReturnLength)
   at System.Security.Principal.WindowsIdentity.GetTokenInformation(SafeAccessTokenHandle tokenHandle, TokenInformationClass tokenInformationClass)
   at System.Security.Principal.WindowsIdentity.get_User()
   at System.Security.Principal.WindowsIdentity.GetName()
   at System.Security.Principal.WindowsIdentity.get_Name()
   at Hub.OnDisconnected(Boolean stopCalled) in C:\pathoftheProject\Hub.cs:line 146
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Disconnect(IHub hub, Boolean stopCalled)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass3_0.<BuildDisconnect>b__0(IHub hub, Boolean stopCalled)
   at Microsoft.AspNet.SignalR.Hubs.HubPipeline.Disconnect(IHub hub, Boolean stopCalled)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.<>c__DisplayClass33_0.<OnDisconnected>b__0(IHub hub)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.<>c__DisplayClass35_0.<ExecuteHubEvent>b__0(IHub instance)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.ExecuteHubEvent(IRequest request, String connectionId, Func`2 action)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.OnDisconnected(IRequest request, String connectionId, Boolean stopCalled)
   at Microsoft.AspNet.SignalR.PersistentConnection.<>c__DisplayClass64_2.<ProcessRequestPostGroupRead>b__7()
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod(Func`1 func)
