### ISSUE TITLE
Connection Error : System.Net.WebSockets.WebSocketException

### ISSUE THREAD

**Issue by KalpeshChheda** [SignalR/SignalR#4272] opened 2018-11-27 08:11 UTC
UWP App is not able to connect via WebSocket Transport. SSE is working fine.

System : Windows 10 1803 Build 17134
UWP Min Build : 16299
UWP Target Build : 17134
Visual Studio 15.9

Signalr Server 2.4.0
Signalr Client  2.4.0

Connection Error : System.Net.WebSockets.WebSocketException (203): An exception caused the WebSocket to enter the Aborted state. Please see the InnerException, if present, for more details. ---> System.ArgumentException: The specified buffer index is not within the buffer capacity.
at System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeBufferExtensions.CopyTo(IBuffer source, UInt32 sourceIndex, Byte[] destination, Int32 destinationIndex, Int32 count)
at System.Net.WebSockets.WinRTWebSocket.OnMessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)
at System.Net.WebSockets.WinRTWebSocket.ReceiveAsync(ArraySegment1 buffer, CancellationToken cancellationToken) at Microsoft.AspNet.SignalR.WebSockets.WebSocketMessageReader.ReadMessageAsync(WebSocket webSocket, Int32 bufferSize, Nullable1 maxMessageSize, CancellationToken disconnectToken)
at Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.ProcessWebSocketRequestAsync(WebSocket webSocket, CancellationToken disconnectToken, Func`2 messageRetriever, Object state)

https://github.com/dotnet/corefx/issues/33704

**Comment by anurse** [comment] 2018-11-27 22:43
Looking at the linked issue, it seems like this bug is a regression in ClientWebSocket and being tracked by the corefx team. I'm closing this issue for now and we should take further investigation/discussion to the corefx issue: dotnet/corefx#33704

If it turns out a SignalR issue is the root cause, we can re-open this bug.

**Closed by anurse** 2018-11-27 22:43 UTC

**Comment by corradocavalli** [comment] 2019-01-11 11:23
I have the same problem after moving SignalR code inside a netstandard 2.0 lib (thus forced to use SignalR client v 2.4)
This is a showstopper for us, any new or workaround?
