### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.

### ISSUE THREAD

**Issue by matmiranda** [SignalR/SignalR#4001] opened 2017-08-28 19:12 UTC
Hi, I'm having a console problem:

> jquery-3.1.1.js:9425 
> [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Image: https://s26.postimg.org/iqu3h95uh/chrome_2017-08-28_16-10-25.jpg

I have jQuery installed: 3.1.1 and SignalR: 2.2.2.

Please follow code:

```
<!--SignalR-->
<script type="text/javascript" src="~/Scripts/jquery.signalR-2.2.2.min.js"></script>
<script type="text/javascript" src="~/signalr/hubs"></script>
<script type="text/javascript">
    $(function () {
        // Start hub
        $.connection.hub.start().done(); // <---Here
    });
</script>
```

If I comment the line:

`//$.connection.hub.start().done();`

The console log warning disappears. Any solution ?

**Comment by moozzyk** [comment] 2017-08-28 20:27
This is a duplicate of https://github.com/SignalR/SignalR/issues/3624

**Closed by moozzyk** 2017-08-28 20:27 UTC
