### ISSUE TITLE
ASP.NET slow startup after adding signalr

### ISSUE THREAD

**Issue by jitbit** [SignalR/SignalR#3958] opened 2017-06-24 09:17 UTC
I have a **precompiled** ASP.NET 4.5 app used by 1000s of companies, and it literally used to take 1second to update the app with a new version (overwriting all the files).

After adding SignalR it now takes 10-15 seconds which is unacceptable. We overwrite the files and the app becomes unresponsive. w3wp cpu load is at 100%

What is SignalR doing and how can I speed it up? We tried `EnableJavaScriptProxies = false;` we also tried our own `IAssemblyLocator` - no help.

I also posted a question at StackoverFlow, but noone seem to know what's going on https://stackoverflow.com/questions/44658233/asp-net-precompiled-but-still-long-startup

**Comment by IanYates** [comment] 2017-06-27 01:56
Do you know if it's startup of new code, or the shutdown of old code, taking a while?

My guess is that IIS is letting your outstanding HTTP requests conclude.  With a typical MVC/API setup this is quick.  With SignalR, particularly with something like long polling, this is by design.

What I'd do to investigate

a) Try to stop the site & app pool in IIS.  Does that take a while?
b) If you have never had any SignalR clients connected is it still slow to stop & start?
c) If you have SignalR clients connected, and then let them disconnect (leave disconnected for several minutes), is it still slow to stop & start?

What communication transport(s) are you using - websockets, long polling, server-sent-events, forever frame?  What version of IIS is in use?  Are you clients web browsers , native or mixed?

Hopefully the above considerations will shed light on your issue.

The other thing you can do is use procmon to watch what w3wp.exe is doing at that time (and perhaps during the various scenarios above).

Finally, is this reproducible in a test environment?

**Comment by IanYates** [comment] 2017-06-27 01:58
Oh, and reading your SO post, the `System.Runtime.CompilerServices.AsyncMethodBuilderCore` stuff is part of the async state machine built by the C# compiler.  It's not actually compiling things.  The class is named because it is meant to be used by code written by the C# compiler (ie not code you write yourself).

**Comment by jitbit** [comment] 2017-06-27 10:14
Thanks for taking the time to answer. But if it's just IIS waiting for "outstanding connections to conclude" - why the 100% cpu load for w3wp? I will check with procmon though, thanks for the idea. Will get back to you.

**Comment by aspnet-hello** [comment] 2018-09-20 21:50
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Closed by aspnet-hello** 2018-09-20 21:50 UTC
