### ISSUE TITLE
Is parallel processing of hub messages possible? They seem to be sequential

### ISSUE THREAD

**Issue by jetic83** [SignalR/SignalR#4136] opened 2018-06-14 14:52 UTC
I want to use SignalR to query for image tiles (rather than using http requests).

My query function is following and executed, say, 50 times "in parallel" (or immediatly one after the other):

Javascript:

    self.signalRHub.server.getTile(args).done(function (data) {
        console.log(data.DebugMessage);
    }

C#

    private ImageResponse GetTile(string args)
    {
        var watch = System.Diagnostics.Stopwatch.StartNew();
        string _time0 = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff");
        // ... create image tile
        long _time1 = watch.ElapsedMilliseconds;
        return ImageResponse; // contains DebugMessage with time0 and time1.
    }

Each generation of a tile would take several dozens or hundreds ms.

Then, I wait for long time (10-20 s) that SignalR gets the response back.
When packing the execution time and duration of each call of the hub function getTile on the server, I saw that all those 50 requests are done sequentially, and not in parallel (see table below for 18 requests):

TIME FUN START | TIME FUN DURATION [ms]
10:08:31.487 | 51
10:08:31.550 | 50
10:08:31.597 | 74
10:08:31.675 | 64
10:08:31.753 | 52
10:08:31.800 | 44
10:08:31.862 | 70
10:08:31.925 | 826
10:08:32.770 | 203
10:08:32.973 | 703
10:08:33.677 | 245
10:08:33.927 | 897
10:08:34.834 | 156
10:08:34.990 | 402
10:08:35.396 | 207
10:08:35.615 | 282
10:08:35.896 | 170
10:08:36.084 | 466

It tells me that each function call waits for the previous function fall to finish (the ms roughly sum up, modulo some times not measured here).

Also SignalR logging messages tell me:

    50x "SignalR: Invoking myhub.GetTile"
    then wait 20 seconds
    then 50x "SignalR: Invoked myhub.GetTile"

My question is if this by design from SignalR, or if I can switch somehow parallel processing on?

**Comment by anurse** [comment] 2018-06-26 00:00
Yes, it's by design. Hub methods from the same connection are invoked sequentially. If you want to support parallel processing, you could have your Hub method start a background process that calls a client method when it completes (using [`HubContext`](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server#how-to-call-client-methods-and-manage-groups-from-outside-the-hub-class)).

Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.

**Closed by anurse** 2018-06-26 00:00 UTC

**Comment by Niproblema** [comment] 2021-02-18 11:41
Is this still correct with newest version of .NET 5.0? 
I find it inconvenient to have to call client methods and match request/responses there.
Does the same principle apply to streaming methods? If I stream a file, then the same client cannot execute any other methods until stream is complete??

**Comment by BrennanConroy** [comment] 2021-02-18 23:45
ASP.NET Core SignalR lives at https://github.com/dotnet/aspnetcore

As of 5.0, parallel invocations are supported. You need to set a property for how much parallelization you want.
https://docs.microsoft.com/aspnet/core/signalr/configuration?view=aspnetcore-5.0&tabs=dotnet#configure-server-options
`MaximumParallelInvocationsPerClient`

**Comment by Niproblema** [comment] 2021-02-21 11:23
Discovered that stream methods works in parallel with 3.1 already. May I use them just as invoke methods ?? Is there any downside? I don't understand this reasoning
