### ISSUE TITLE
WebSockets silent fail calling server methods in Firefox

### ISSUE THREAD

**Issue by circuitrider** [SignalR/SignalR#3543] opened 2015-09-02 19:10 UTC
This may be due to the latest Firefox patch, since I know for a fact this was working earlier in August. But I just had to disable WebSockets for Firefox because it is no longer able to call server methods. I am using the generated proxy /signalr/hubs

With logging turned on I see the expected message "SignalR: Invoking server method XXXX" but after that, it goes into a black hole. 

I tested previous releases of the app from my source control that I can assure you did work properly, so this wasn't a code change I made that broke this.

I ensured all javascript minification was disabled.

All I have not done is use fiddler to observe if it is actually leaving the browser, because I had to move to higher priority tasks and for now am fine with Firefox users connecting with Server Sent Events. 

This still works 100% fine in every other browser.

Has anyone else seen this issue? It is going to haunt my dreams until I figure it out.

**Comment by AndrewFreese** [comment] 2015-10-07 19:09
Doubt this helps but:
I had a narrower issue with Firefox (38,40 and 41). 
SignalR failed silently with firefox but ONLY with https AND using my load balancer (Kemp). 
FF worked via ngrok with https and never had a problem via http.

So whatever the problem is, I bet it's gob smackingly subtle. 
The silence of the fail is severely alarming. No indication of sadness on client or server.

I got FF to be happy by switching to server sent events for FF only. And I'm hoping that lame hack wont haunt my dreams :)

**Comment by circuitrider** [comment] 2015-10-23 14:53
I wish I had the expertise to know how to begin debugging this issue. It is beyond my experience.

**Comment by renzosal** [comment] 2016-10-12 15:13
@AndrewFreese were you able to resolve the issue without switching to server sent events only?

**Comment by AndrewFreese** [comment] 2016-10-12 15:18
No and I've not tried anything else since then. It was only necessary for Firefox which is a minority of my users and SSE works so I've not worried about it since then.

**Comment by circuitrider** [comment] 2016-10-12 16:02
Mimics my experience. Firefox was a minority so for that browser I just made the client not use websockets. Definitely not preferred but none of my efforts made an inch of progress.

**Comment by renzosal** [comment] 2016-10-12 16:05
@circuitrider were you also using Kemp(using that now) as your load balancer? If i bypass the loadbalancer then it works fine in firefox. I'll try using nginx and see how that goes.

**Comment by circuitrider** [comment] 2016-10-12 16:13
Negative, was a Windows server cluster, so just IIS ARR. I was able to reproduce the error on my local environment as well. Only commonality now that I think of it was the fact both were set up with a Redis backplane, but I was monitoring it during debugging and no messages were being published when the problem occurred. 

But it was a corporate network that had some custom security policies on terminals and network wide security tools operating which may have complicated this. I'm just surprised that Firefox only and not Chrome too would have this problem if that was the case since the policies would only be singling out IE or non-IE browsers for custom network behavior for calls not leaving the terminal. Unfortunately I've moved on from that contract and don't have the kind of access to the network anymore where I could do further diagnostics.

**Comment by moozzyk** [comment] 2016-10-17 21:16
I wonder if this is somehow related to: https://github.com/aspnet/KestrelHttpServer/issues/1170#issuecomment-254334825

**Comment by aspnet-hello** [comment] 2018-09-20 22:01
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Closed by aspnet-hello** 2018-09-20 22:01 UTC
