### ISSUE TITLE
Client stops receiving data from server randomly on production server but always works on development server

### ISSUE THREAD

**Issue by mustafajavid** [SignalR/SignalR#4189] opened 2018-09-03 12:32 UTC
Client is successfully connected to hub through web-sockets but only receives data from production server sometimes. While on the development server (IIS Express) it always receives the data.

I have enabled web-sockets on the production server (Windows server 2012, signalr version 2.3.0). The client should receive data from the server every time the connection is made but it doesn't receive the data sometimes and there are no errors in client logs and server logs.

I have also enabled signalr file tracing on the server.
Which shows the following logs in trasports.log.txt:

```
SignalR.Transports.TransportHeartBeat Verbose: 0 : KeepAlive(064cb5fb-6607-4cb8-904f-5486d9ad09cf)
SignalR.Transports.WebSocketTransport Information: 0 : CloseSocket(064cb5fb-6607-4cb8-904f-5486d9ad09cf)
SignalR.Transports.WebSocketTransport Information: 0 : Abort(064cb5fb-6607-4cb8-904f-5486d9ad09cf)
SignalR.Transports.TransportHeartBeat Information: 0 : Removing connection 064cb5fb-6607-4cb8-904f-5486d9ad09cf
SignalR.Transports.WebSocketTransport Information: 0 : End(064cb5fb-6607-4cb8-904f-5486d9ad09cf)
SignalR.Transports.WebSocketTransport Verbose: 0 : DrainWrites(064cb5fb-6607-4cb8-904f-5486d9ad09cf)
SignalR.Transports.WebSocketTransport Information: 0 : CompleteRequest (064cb5fb-6607-4cb8-904f-5486d9ad09cf)
```

Where the connection-id in the logs above is: 064cb5fb-6607-4cb8-904f-5486d9ad09cf 
And the client is showing the connection-id: 14b6dc5c-3beb-41f1-92fe-00b7ad2e36e1

This happens when i'm using signalr to communicate from server to client and during an open connection i navigate away from the page upon which i stop the hub by `$.connection.hub.stop();
` but when i navigate to the same page again i connect to signalr by `$.connection.hub.start()` and the client log show a valid connection-id but now the client doesn't receive any data from server.

**Comment by anurse** [comment] 2018-09-04 17:43
Does this only happen with the WebSockets transport? Can you try forcing a different transport and see if it reproduces there? Also, could you collect network traces from the client using a tool like [Fiddler](https://www.telerik.com/fiddler) so we can see how the client is sending the message?

**Comment by mustafajavid** [comment] 2018-09-05 08:49
Hi @anurse i tried with serverSentEvents this time and the same thing is happening. Client receives data from server as seen in the screenshot below:
![capture 5](https://user-images.githubusercontent.com/35831655/45081965-c4da4780-b111-11e8-857e-382b10bbc79e.PNG)

and after a few disconnections when i connect to the signalr hub again then the client doesn't receive any data no matter how many times i try with the same connection-id:

Network calls of SignalR:
![capture 1](https://user-images.githubusercontent.com/35831655/45082078-fe12b780-b111-11e8-9d97-976e9a4c0a16.PNG)

Response of negotiate call:
![capture 2](https://user-images.githubusercontent.com/35831655/45082116-0ec32d80-b112-11e8-8a75-b07101526a7b.PNG)

Response of start call:
![capture 4](https://user-images.githubusercontent.com/35831655/45082222-47fb9d80-b112-11e8-9602-98457dc24316.PNG)

Response of connect call with no data:
![capture 3](https://user-images.githubusercontent.com/35831655/45082242-534ec900-b112-11e8-88ec-57ca9e9e9fc7.PNG)
![capture 6](https://user-images.githubusercontent.com/35831655/45082272-65306c00-b112-11e8-8827-43f64584c269.PNG)

**Comment by anurse** [comment] 2018-09-05 17:06
Can you send the full logs and traces to me? I realize there might be data you'd rather not disclose on a public GitHub site. You can send them privately to me at `[my github username]@microsoft.com`.

**Comment by mustafajavid** [comment] 2018-09-06 11:26
@anurse I have sent you an email with client and server logs. Let me know if you need any more data.

**Comment by mustafajavid** [comment] 2018-10-02 16:20
@anurse any progress regarding this issue?

**Comment by anurse** [comment] 2018-10-11 16:53
After investigation it appears this was caused by having multiple server processes running on the same physical server (aka a "Web Garden") without a backplane. Closing this as a backplane is required any time there are multiple server processes (even if they are on the same server). Feel free to comment further if there's still an issue to investigate here.

**Closed by anurse** 2018-10-11 16:53 UTC
Labels: status: Investigate
