### ISSUE TITLE
Version 2.2.3 released to NuGet has an invalid FileVersion.

### ISSUE THREAD

**Issue by HeathJared** [SignalR/SignalR#4124] opened 2018-05-31 17:47 UTC
### Expected  behavior
The FileVersion for version 2.2.3 should be higher than version 2.2.2.

### Actual behavior
The FileVersion for version 2.2.3 is lower than version 2.2.2.

### Steps to Reproduce

View the details of each DLL.

Version 2.2.2 has a FileVersion of 2.2.60504.11741
Version 2.2.3 has a FileVersion of 2.2.10306.1417

This is a botched release. It currently breaks MSI based installers and deployments.

**Comment by BrennanConroy** [comment] 2018-05-31 17:49
Dupe of https://github.com/SignalR/SignalR/issues/4090

**Closed by BrennanConroy** 2018-05-31 17:49 UTC
