### ISSUE TITLE
Connection stop on event unload NOT WORK with SignalR JS 2.4.1 and Chrome v80

### ISSUE THREAD

**Issue by CedricInfeeny** [SignalR/SignalR#4453] opened 2020-03-23 10:30 UTC
Hello,

```js
With Chrome v80 and SignalR Javascript 2.4.1, the following code does not work :
                        // wire the stop handler for when the user leaves the page
                        _pageWindow.bind("unload", function () {
                            connection.log("Window unloading, stopping the connection.");

                            connection.stop(asyncAbort);
                        });
```

I found this article from Google : https://developers.google.com/web/updates/2019/12/chrome-80-deps-rems

If the following parameter is enabled, the operation is correct :
Allows synchronous XHR requests in page dismissal
Allows synchronous XHR requests during page dismissal when the page is being navigated away or closed by the user. – Mac, Windows, Linux, Chrome OS, Android

However Google specifies : This is a temporary "opt-out" measure, and we expect to remove this flag in Chrome 82...

Can this be fixed permanently?

Thank you. 

Regards,

**Comment by BrennanConroy** [comment] 2020-05-13 21:00
Dupe of https://github.com/SignalR/SignalR/issues/4365

**Closed by BrennanConroy** 2020-05-13 21:00 UTC
