### ISSUE TITLE
SQL UPDATE on Message_Id table locking itself

### ISSUE THREAD

**Issue by mujicadiazr** [SignalR/SignalR#4402] opened 2019-08-23 17:48 UTC
### **Environment:**
**SQL Server:** 
       version: 12.0.5214.6
       memory: 2096698 MB
       processors: 128
**Web Servers: 2**
**SqlScaleoutConfiguration:**
TableCount = 3,
MaxQueueLength = 50

We are experiencing a lot of locking certain days in our backplane server in the Messages_Id table, which worries us because when this happens these operations consume a lot of CPU time in the DB server instance affecting the overall performance and the rest of the applications using that server. We momentarily fix the issue by recycling the AppPool but the issue comes back again.

The SQL query which is locking is following:
`UPDATE TOP(1) [SignalR].[Messages_0_Id] SET @NewPayloadId = [PayloadId] = [PayloadId] + 1
OUTPUT INSERTED.[PayloadId], @Payload, GETDATE()
-- Insert payload
INTO [SignalR].[Messages_0] ([PayloadId], [Payload], [InsertedOn]);`

Bellow, you can find a historical trend of this SQL and you will notice the enormous increase of the number of executions in certain days even though
 the user load in the website is the same.
![image](https://user-images.githubusercontent.com/13793957/63609946-37079e80-c5a6-11e9-80bd-743821eb5b4b.png)

The number of calls from clients to the /signalr/ endpoint at the same time range proving that the user load is the same.
![image](https://user-images.githubusercontent.com/13793957/63719847-e00aff00-c81b-11e9-9237-8665ea4a0fb5.png)

Here, I'm attaching a small portion of the **bus.log** captured when the issue was happening.
[bus2.log.txt](https://github.com/SignalR/SignalR/files/3535635/bus2.log.txt)

What could be causing that increase in the number of executions?

**Comment by mujicadiazr** [comment] 2019-08-29 18:04
Since this increase in the frequency on what the messages are being sent is not happening all the time and just occasional days even though the user load in the website is the same, and it gets fixed after we recycle the AppPool because the Hubs get disposed and re-instantiated, we're thinking of it more like an internal bug in SignalR core code which is sending more messages than expected at that time.

Could we confirm based on the logs that Hubs are not sending unnecessary messages at certain times?
For example, from the logs bellow line is repeated a lot of times:
```
SignalR.SqlMessageBus Verbose: 0 : Stream 0 : No records received
SignalR.SqlMessageBus Verbose: 0 : Stream 0 : Waiting 10ms before checking for messages again
SignalR.SqlMessageBus Verbose: 0 : Created DbCommand: CommandType=Text, CommandText=SELECT [PayloadId], [Payload], [InsertedOn] FROM [SignalR].[Messages_0] WHERE [PayloadId] > @PayloadId, Parameters= [Name=PayloadId, Value=223877856]
```

The change to Redis is already on the table, but we wanted to check this out for any clue on what could be the root cause.

**Comment by halter73** [comment] 2019-08-29 19:55
Since the logs don't contain the actual payloads, I'm not sure that's enough to determine who's responsible for sending the messages. You could try dumping the messages table itself when you recycle the app pool to see what the messages are.

What version of SignalR are you using? I can remember one [bug similar to this](https://github.com/SignalR/SignalR/issues/2958) where if you had a lot of long polling clients, broadcasts could create a lot of load on the backplane, because each long polling client would result in an extra message being published to the backplane for each broadcast. This issue was fixed in 2.1 though.

**Comment by mujicadiazr** [comment] 2019-08-29 20:13
Will try to get a dump of the messages table when the issue happens again.
We are using version 2.4.1.

**Comment by ckulisz** [comment] 2019-09-13 17:44
The major locking issues are due to the SQL code being used is not optimized for any Specific vendor backend of SQL "Oracle, MS, SQlLite, Postgree, etc.." It meets the working conditions of sitting on top of any of them since it's basic compatibility with ISO/IEC 9075 for SQL +
The problem is that each vendor has different ways to handle identity/AutoIncrementing columns so you cannot standardize this code.  You would need to rewrite the SQL to be specific to each backend so that handling is not through a 2 table but 1 table with PK and Autoincrementing column. 
Also due to the nature of how the SQL is being handled you have the Query which self cleans data every Modulo of 2500 which is not efficient .. There are vastly different ways to shard the data and drop older records "Micro second operations vs current millisecond +lock contention". But again you would have to spend some time and customize for each SQL vendor. Saying that it should not be hard work to change the signalR to call SP's rather then Query. This would make the code vendor agnostic. Only on start do you check what type of Vendor connection you have "Or even configure and deploy the vendor specific schema/Sp's to handle this work load.

When it deletes from the table The Query has obtained a Shared Lock and then is trying to Upgrade said lock to Exclusive due to the delete operation "And you are doing this in a serialized connection" . In a very busy system you might have multiple query's doing the same just due to the message load and this would cause deadlocks etc to happen. Also throw in Replication and latency and you have huge smorgasbord of issues.

**Comment by anurse** [comment] 2019-09-25 17:41
We don't have plans to make significant changes to our SQL Backplane at this time. In general, Azure SignalR is our primary recommendation for scale-out now (SQL is provided for fallback, and Redis for on-premise deployments that can't use Azure).

**Closed by anurse** 2019-09-25 17:41 UTC
