### ISSUE TITLE
 Cannot access a disposed object. Object name '#serverMachineName'

### ISSUE THREAD

**Issue by samywat11** [SignalR/SignalR#3718] opened 2016-06-14 20:52 UTC
Following is the exception that we are experiencing while sending the notification or calling the client function hubClients.Group(group).clientFunction(context,payload). Recently we are recycling app pool  depending on load on server. Whenever the app pool is recycled , it seems one of the signalr object is not created properly or is corrupt. Although It is strange that it doesn't fails on every app pool recycles. After one of the app pool recycle it fails continuously to send the notification and then on following recycle it works fine.  
We are on 2.2.0 and redis for backplane. 

Exception: System.ObjectDisposedException: Cannot access a disposed object. Object name: '#servermachinename' .  
 at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)  
 at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)  
 at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context)  
 at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass1b.<BuildOutgoing>b__19(IHubOutgoingInvokerContext context)  
 at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass1b.<BuildOutgoing>b__19(IHubOutgoingInvokerContext context)  
 at Microsoft.AspNet.SignalR.Hubs.HubPipeline.Send(IHubOutgoingInvokerContext context)  
 at Microsoft.AspNet.SignalR.Hubs.SignalProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)

**Comment by marcomorain** [comment] 2016-07-12 14:03
I'm having the same issue:

```
ObjectDisposedException: Cannot access a disposed object.
Object name: 'RD00155D86F636'.
  File "C:\projects\web\FlipdishWeb\Flipdish.Web\Controllers\CronMonitorController.cs", line 48, col 17, in GetLastExecutionTimes
    System.Web.Mvc.ActionResult GetLastExecutionTimes(System.String)
  File "C:\projects\web\FlipdishWeb\Flipdish.Domain\DomainModel\Services\AdminBroadcastService.cs", line 27, col 13, in Test
    Void Test()
  Module "System.Collections.Generic.List`1", line 54, col 0, in ForEach
    Void ForEach(System.Action`1[T])
  File "C:\projects\web\FlipdishWeb\Flipdish.Domain\DomainModel\Services\AdminBroadcastService.cs", line 27, col 37, in <Test>b__3_0
    Void <Test>b__3_0(Flipdish.Domain.DomainModel.Services.OrderCallbacks)
  File "C:\projects\web\FlipdishWeb\Flipdish.Web\Concerns\SignalrOrderListener.cs", line 21, col 13, in Test
    Void Test()
  ?, col 0, in CallSite.Target
  Module "Microsoft.AspNet.SignalR.Hubs.ClientProxy", line 0, col 0, in TryInvokeMember
    Boolean TryInvokeMember(System.Dynamic.InvokeMemberBinder, System.Object[], System.Object ByRef)
  Module "Microsoft.AspNet.SignalR.Hubs.HubPipelineModule+<>c__DisplayClass1b", line 16, col 0, in <BuildOutgoing>b__19
    System.Threading.Tasks.Task <BuildOutgoing>b__19(Microsoft.AspNet.SignalR.Hubs.IHubOutgoingInvokerContext)
  Module "Microsoft.AspNet.SignalR.Hubs.HubDispatcher", line 7, col 0, in Outgoing
    System.Threading.Tasks.Task Outgoing(Microsoft.AspNet.SignalR.Hubs.IHubOutgoingInvokerContext)
  Module "Microsoft.AspNet.SignalR.Infrastructure.Connection", line 232, col 0, in Send
    System.Threading.Tasks.Task Send(Microsoft.AspNet.SignalR.ConnectionMessage)
  Module "Microsoft.AspNet.SignalR.Messaging.ScaleoutStream", line 26, col 0, in Send
    System.Threading.Tasks.Task Send(System.Func`2[System.Object,System.Threading.Tasks.Task], System.Object)
```

**Comment by accomplix** [comment] 2016-07-14 20:18
Same problem. I'm running on Azure App Services with Redis for backplane.

`System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'RD0003FFB00F8F'.
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStreamManager.Send(Int32 streamIndex, IList`1 messages)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Send(IList`1 messages)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Publish(Message message)
   at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
   at Microsoft.AspNet.SignalR.Transports.TransportConnectionExtensions.SendCommand(ITransportConnection connection, String connectionId, CommandType commandType)
   at Microsoft.AspNet.SignalR.Transports.ForeverTransport.<>c__DisplayClass1f.<ProcessReceiveRequest>b__18()
   at Microsoft.AspNet.SignalR.Transports.ForeverTransport.<>c__DisplayClass1f.<ProcessReceiveRequest>b__1c()
   at Microsoft.AspNet.SignalR.Transports.ForeverTransport.ProcessMessages(ITransportConnection connection, Func`1 initialize)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Cors.CorsMiddleware.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Mapping.MapMiddleware.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.<DoFinalWork>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)`

**Comment by marcomorain** [comment] 2016-07-14 20:22
Is too — an Azure Web Site with Redis as a backplane for signalr. 

I was calling signalR from inside a LINQ ForEach block that I was worried could be lazily evaluated after the request had ended. If since changed my code to use a foreach keyword loop to see if that has any effect. I'll update if it makes any difference.

**Comment by halter73** [comment] 2016-09-23 22:05
This could be a dupe of https://github.com/SignalR/SignalR/issues/3093

**Comment by moozzyk** [comment] 2016-09-23 23:10
https://github.com/SignalR/SignalR/issues/3093#issuecomment-249322831

**Comment by moozzyk** [comment] 2017-02-13 17:40
Closing as a duplicate

**Closed by moozzyk** 2017-02-13 17:40 UTC
